/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/PostCore.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export type Result_2 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface PostKeyProperties {
    bucketCanisterId: string;
    created: string;
    principal: string;
    modified: string;
    views: string;
    publishedDate: string;
    claps: string;
    tags: Array<PostTagModel>;
    isDraft: boolean;
    category: string;
    handle: string;
    postId: string;
}
export interface Icrc28TrustedOriginsResponse {
    trusted_origins: Array<string>;
}
export type Result_5 = {
    __kind__: "ok";
    ok: PostKeyProperties;
} | {
    __kind__: "err";
    err: string;
};
export interface TagModel {
    id: string;
    value: string;
    createdDate: string;
}
export type Validate = {
    __kind__: "Ok";
    Ok: string;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface PostTagModel {
    tagId: string;
    tagName: string;
}
export type Result_4 = {
    __kind__: "ok";
    ok: Post;
} | {
    __kind__: "err";
    err: string;
};
export interface Post {
    url: string;
    bucketCanisterId: string;
    title: string;
    created: string;
    modified: string;
    content: string;
    views: string;
    wordCount: string;
    isPremium: boolean;
    publishedDate: string;
    claps: string;
    tags: Array<PostTagModel>;
    nftCanisterId?: string;
    isDraft: boolean;
    creatorPrincipal: string;
    category: string;
    handle: string;
    creatorHandle: string;
    headerImage: string;
    isMembersOnly: boolean;
    subtitle: string;
    isPublication: boolean;
    postId: string;
}
export type List = [string, List] | null;
export interface GetPostsByFollowers {
    totalCount: string;
    posts: Array<PostKeyProperties__1>;
}
export type Result_7 = {
    __kind__: "ok";
    ok: Uint8Array;
} | {
    __kind__: "err";
    err: string;
};
export interface ContentResult {
    status: ContentStatus;
    approvedCount: bigint;
    sourceId: string;
    violatedRules: Array<ViolatedRules>;
    rejectedCount: bigint;
}
export interface PostSaveModel {
    title: string;
    content: string;
    premium?: {
        thumbnail: string;
        icpPrice: bigint;
        maxSupply: bigint;
    };
    isDraft: boolean;
    tagIds: Array<string>;
    category: string;
    handle: string;
    creatorHandle: string;
    headerImage: string;
    isMembersOnly: boolean;
    scheduledPublishedDate?: bigint;
    subtitle: string;
    isPublication: boolean;
    postId: string;
}
export interface PostTagModel__1 {
    tagId: string;
    tagName: string;
}
export type Result_6 = {
    __kind__: "ok";
    ok: [Array<[string, Array<string>]>, Array<[string, Array<string>]>];
} | {
    __kind__: "err";
    err: string;
};
export interface ViolatedRules {
    id: string;
    rejectionCount: bigint;
}
export interface PostTag {
    tagId: string;
    createdDate: bigint;
    isActive: boolean;
    modifiedDate: bigint;
}
export interface UserPostCounts {
    totalViewCount: string;
    plannedCount: string;
    uniqueClaps: string;
    draftCount: string;
    uniqueReaderCount: string;
    publishedCount: string;
    handle: string;
    premiumCount: string;
    submittedToReviewCount: string;
    totalPostCount: string;
}
export interface SupportedStandard {
    url: string;
    name: string;
}
export type Result_9 = {
    __kind__: "ok";
    ok: TagModel;
} | {
    __kind__: "err";
    err: string;
};
export type Result = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export type Result_10 = {
    __kind__: "ok";
    ok: Array<[string, string]>;
} | {
    __kind__: "err";
    err: string;
};
export type Result_8 = {
    __kind__: "ok";
    ok: Array<string>;
} | {
    __kind__: "err";
    err: string;
};
export interface PostBucketType {
    url: string;
    bucketCanisterId: string;
    title: string;
    created: string;
    modified: string;
    content: string;
    wordCount: string;
    isPremium: boolean;
    publishedDate: string;
    nftCanisterId?: string;
    isDraft: boolean;
    creatorPrincipal: string;
    category: string;
    handle: string;
    postOwnerPrincipal: string;
    creatorHandle: string;
    headerImage: string;
    isMembersOnly: boolean;
    subtitle: string;
    isPublication: boolean;
    postId: string;
}
export interface PostKeyProperties__1 {
    bucketCanisterId: string;
    created: string;
    principal: string;
    modified: string;
    views: string;
    publishedDate: string;
    claps: string;
    tags: Array<PostTagModel>;
    isDraft: boolean;
    category: string;
    handle: string;
    postId: string;
}
export enum PopularityType {
    month = "month",
    today = "today",
    ever = "ever",
    week = "week"
}
export enum PostModerationStatusV2 {
    new_ = "new",
    approved = "approved",
    rejected = "rejected"
}
export enum RecallOptions {
    sixtydays = "sixtydays",
    today = "today",
    thisWeek = "thisWeek",
    thisYear = "thisYear",
    allTime = "allTime",
    ninetydays = "ninetydays",
    thisMonth = "thisMonth"
}
export interface PostCoreInterface {
    acceptCycles(): Promise<void>;
    addCanisterToCyclesDispenser(arg0: string, arg1: bigint, arg2: bigint): Promise<Result_1>;
    addNewRules(arg0: Array<string>): Promise<void>;
    addPostCategory(arg0: string, arg1: string, arg2: bigint): Promise<void>;
    addPostIdToUserDebug(arg0: string, arg1: string): Promise<Result_1>;
    addWasmChunk(arg0: Uint8Array): Promise<Result_1>;
    availableCycles(): Promise<bigint>;
    checkViewsLast24Hours(): Promise<void>;
    clapPost(arg0: string): Promise<void>;
    copyPublicationCanisters(arg0: string): Promise<Result_10>;
    copyTrustedCanisters(arg0: string): Promise<Result_8>;
    createNewBucketCanister(): Promise<Result_2>;
    createTag(arg0: string): Promise<Result_9>;
    currentId(): Promise<bigint>;
    debugApplaudsHashMap(): Promise<Array<[string, bigint]>>;
    debugGetApplaudsHashMap(): Promise<Array<[string, bigint]>>;
    debugMembersOnlyStatusOfExistingDraftArticles(): Promise<Result_8>;
    debugSaveMultiplePosts(arg0: Array<PostSaveModel>): Promise<Array<Result_4>>;
    delete_(arg0: string): Promise<Result_3>;
    deletePostFromUserDebug(arg0: string, arg1: string): Promise<Result_8>;
    deleteUserPosts(arg0: string): Promise<Result_3>;
    dumpIds(): Promise<Result_1>;
    dumpPosts(): Promise<Result_1>;
    dumpUserIds(): Promise<Result_1>;
    followTag(arg0: string): Promise<Result_1>;
    followTags(arg0: Array<string>): Promise<Result_1>;
    generateLatestPosts(): Promise<void>;
    generatePublishedDates(): Promise<void>;
    getActiveBucketCanisterId(): Promise<Result_2>;
    getAdmins(): Promise<Result_8>;
    getAllBuckets(): Promise<Result_8>;
    getAllNftCanisters(): Promise<Array<[string, string]>>;
    getAllStatusCount(): Promise<Result_2>;
    getAllTags(): Promise<Array<TagModel>>;
    getBucketCanisterIdsOfGivenHandles(arg0: Array<string>): Promise<Array<string>>;
    getBucketCanisters(): Promise<Array<[string, string]>>;
    getCanisterVersion(): Promise<string>;
    getCgUsers(): Promise<Result_8>;
    getFrontendCanisterId(): Promise<Result_2>;
    getHistoricalPublishedArticlesData(): Promise<Array<[string, bigint]>>;
    getKinicList(): Promise<Result_8>;
    getLastWeekRejectedPostKeyProperties(): Promise<Array<PostKeyProperties>>;
    getLatestPosts(arg0: number, arg1: number): Promise<GetPostsByFollowers>;
    getLatestTimerCall(): Promise<[string, string]>;
    getList(arg0: Array<string>): Promise<Array<PostKeyProperties>>;
    getMaxMemorySize(): Promise<bigint>;
    getMemorySize(): Promise<bigint>;
    getMoreArticlesFromUsers(arg0: string, arg1: Array<string>): Promise<Array<Array<PostKeyProperties>>>;
    getMoreLatestPosts(arg0: number, arg1: number): Promise<Array<PostKeyProperties>>;
    getMyAllPosts(arg0: number, arg1: number): Promise<Array<PostKeyProperties>>;
    getMyDailyPostsStatus(): Promise<boolean>;
    getMyDraftPosts(arg0: number, arg1: number): Promise<Array<PostKeyProperties>>;
    getMyFollowingTagsPostKeyProperties(arg0: number, arg1: number): Promise<GetPostsByFollowers>;
    getMyPlannedPosts(arg0: number, arg1: number): Promise<Array<PostKeyProperties>>;
    getMyPublishedPosts(arg0: number, arg1: number): Promise<Array<PostKeyProperties>>;
    getMySubmittedToReviewPosts(arg0: number, arg1: number): Promise<Array<PostKeyProperties>>;
    getMyTags(): Promise<Array<PostTagModel__1>>;
    getNextPostId(): Promise<Result_2>;
    getNextPostIdsDebug(arg0: bigint): Promise<Result_2>;
    getPlatformOperators(): Promise<List>;
    getPopular(arg0: number, arg1: number): Promise<GetPostsByFollowers>;
    getPopularThisMonth(arg0: number, arg1: number): Promise<GetPostsByFollowers>;
    getPopularThisWeek(arg0: number, arg1: number): Promise<GetPostsByFollowers>;
    getPopularToday(arg0: number, arg1: number): Promise<GetPostsByFollowers>;
    getPostKeyProperties(arg0: string): Promise<Result_5>;
    getPostUrls(): Promise<Result_2>;
    getPostViewsPerHourLast24Hours(): Promise<[bigint, Array<[bigint, bigint]>]>;
    getPostsByCategory(arg0: string, arg1: string, arg2: number, arg3: number): Promise<GetPostsByFollowers>;
    getPostsByFollowers(arg0: Array<string>, arg1: number, arg2: number): Promise<GetPostsByFollowers>;
    getPostsByPostIds(arg0: Array<string>): Promise<Array<PostKeyProperties>>;
    getPostsByPostIdsMigration(arg0: Array<string>): Promise<Array<PostKeyProperties>>;
    getPostsPerHourLast24Hours(): Promise<[bigint, Array<[bigint, bigint]>]>;
    getPublicationCanisters(): Promise<Array<[string, string]>>;
    getPublicationPosts(arg0: number, arg1: number, arg2: string): Promise<Array<PostKeyProperties>>;
    getTagFollowers(arg0: string): Promise<Result_8>;
    getTagsByUser(arg0: string): Promise<Array<PostTag>>;
    getTotalAmountOfTipsReceived(): Promise<bigint>;
    getTotalArticleViews(): Promise<bigint>;
    getTotalClaps(): Promise<bigint>;
    getTotalPostCount(): Promise<bigint>;
    getTrustedCanisters(): Promise<Result_8>;
    getUserDailyAllowedPostNumber(): Promise<bigint>;
    getUserPostCounts(arg0: string): Promise<UserPostCounts>;
    getUserPostIds(arg0: string): Promise<Result_8>;
    getUserPosts(arg0: string): Promise<Array<PostKeyProperties>>;
    getUsersPostCountsByHandles(arg0: Array<string>): Promise<Array<UserPostCounts>>;
    getViewsByRange(arg0: RecallOptions): Promise<bigint>;
    getWasmChunks(): Promise<Result_7>;
    handleModclubMigration(arg0: string): Promise<Result_2>;
    icrc10_supported_standards(): Promise<Array<SupportedStandard>>;
    icrc28_trusted_origins(): Promise<Icrc28TrustedOriginsResponse>;
    idQuick(): Promise<Principal>;
    incrementApplauds(arg0: string, arg1: bigint): Promise<void>;
    indexPopular(): Promise<void>;
    initializeCanister(arg0: string, arg1: string, arg2: string): Promise<Result_2>;
    initializePostCoreCanister(): Promise<Result_2>;
    isEditorPublic(arg0: string, arg1: Principal): Promise<boolean>;
    isThereEnoughMemory(): Promise<boolean>;
    isWriterPublic(arg0: string, arg1: Principal): Promise<boolean>;
    makePostPublication(arg0: string, arg1: string, arg2: string, arg3: boolean, arg4: bigint): Promise<void>;
    migrateAllPublicationEditorsAndWriters(): Promise<Result_6>;
    migrateModclubInterface(): Promise<Result_2>;
    migratePremiumArticleFromOldArch(): Promise<Result_5>;
    modClubCallback(arg0: ContentResult): Promise<void>;
    refreshUserPostIds(arg0: string): Promise<Result_3>;
    registerAdmin(arg0: string): Promise<Result_1>;
    registerCanister(arg0: string): Promise<Result_1>;
    registerCgUser(arg0: string): Promise<Result_1>;
    registerPlatformOperator(arg0: string): Promise<Result_1>;
    registerPublisher(): Promise<void>;
    reindex(): Promise<Result_2>;
    removePostFromPopularityArrays(arg0: string): Promise<void>;
    removePostIdToUserDebug(arg0: string, arg1: string): Promise<Result_1>;
    resetWasmChunks(): Promise<void>;
    save(arg0: PostSaveModel): Promise<Result_4>;
    sendNewArticleNotification(arg0: PostBucketType): Promise<void>;
    setFrontendCanisterId(arg0: string): Promise<Result_2>;
    setMaxMemorySize(arg0: bigint): Promise<Result_3>;
    setUpModClub(arg0: string): Promise<void>;
    setUserDailyAllowedPostNumber(arg0: bigint): Promise<Result_3>;
    simulateModClub(arg0: string, arg1: PostModerationStatusV2): Promise<void>;
    sortPopularPosts(arg0: PopularityType): Promise<void>;
    storeAllSEO(): Promise<Result_1>;
    testInstructionSize(): Promise<string>;
    unfollowTag(arg0: string): Promise<Result_1>;
    unregisterAdmin(arg0: string): Promise<Result_1>;
    unregisterCanister(arg0: string): Promise<Result_1>;
    unregisterCgUser(arg0: string): Promise<Result_1>;
    unregisterPlatformOperator(arg0: string): Promise<Result_1>;
    updateHandle(arg0: string, arg1: string): Promise<Result_2>;
    updatePostDraft(arg0: string, arg1: boolean, arg2: bigint, arg3: string): Promise<PostKeyProperties>;
    updatePublicationEditorsAndWriters(arg0: string, arg1: Array<string>, arg2: Array<string>): Promise<Result_1>;
    updateSettingsForAllBucketCanisters(): Promise<Result_2>;
    upgradeAllBuckets(arg0: string, arg1: Uint8Array): Promise<Result_1>;
    upgradeBucket(arg0: string, arg1: Uint8Array): Promise<Result_1>;
    validate(arg0: any): Promise<Validate>;
    verifyMigration(): Promise<Result>;
    viewPost(arg0: string): Promise<void>;
}
import type { ContentResult as _ContentResult, ContentStatus as _ContentStatus, List as _List, PopularityType as _PopularityType, Post as _Post, PostBucketType as _PostBucketType, PostKeyProperties as _PostKeyProperties, PostModerationStatusV2 as _PostModerationStatusV2, PostSaveModel as _PostSaveModel, PostTagModel as _PostTagModel, RecallOptions as _RecallOptions, Result as _Result, Result_1 as _Result_1, Result_10 as _Result_10, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Result_8 as _Result_8, Result_9 as _Result_9, TagModel as _TagModel, Validate as _Validate, ViolatedRules as _ViolatedRules } from "./declarations/PostCore.did";
export class PostCore implements PostCoreInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async acceptCycles(): Promise<void> {
        const result = await this.actor.acceptCycles();
        return result;
    }
    async addCanisterToCyclesDispenser(arg0: string, arg1: bigint, arg2: bigint): Promise<Result_1> {
        const result = await this.actor.addCanisterToCyclesDispenser(arg0, arg1, arg2);
        return from_candid_Result_1_n1(result);
    }
    async addNewRules(arg0: Array<string>): Promise<void> {
        const result = await this.actor.addNewRules(arg0);
        return result;
    }
    async addPostCategory(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        const result = await this.actor.addPostCategory(arg0, arg1, arg2);
        return result;
    }
    async addPostIdToUserDebug(arg0: string, arg1: string): Promise<Result_1> {
        const result = await this.actor.addPostIdToUserDebug(arg0, arg1);
        return from_candid_Result_1_n1(result);
    }
    async addWasmChunk(arg0: Uint8Array): Promise<Result_1> {
        const result = await this.actor.addWasmChunk(arg0);
        return from_candid_Result_1_n1(result);
    }
    async availableCycles(): Promise<bigint> {
        const result = await this.actor.availableCycles();
        return result;
    }
    async checkViewsLast24Hours(): Promise<void> {
        const result = await this.actor.checkViewsLast24Hours();
        return result;
    }
    async clapPost(arg0: string): Promise<void> {
        const result = await this.actor.clapPost(arg0);
        return result;
    }
    async copyPublicationCanisters(arg0: string): Promise<Result_10> {
        const result = await this.actor.copyPublicationCanisters(arg0);
        return from_candid_Result_10_n3(result);
    }
    async copyTrustedCanisters(arg0: string): Promise<Result_8> {
        const result = await this.actor.copyTrustedCanisters(arg0);
        return from_candid_Result_8_n5(result);
    }
    async createNewBucketCanister(): Promise<Result_2> {
        const result = await this.actor.createNewBucketCanister();
        return from_candid_Result_2_n7(result);
    }
    async createTag(arg0: string): Promise<Result_9> {
        const result = await this.actor.createTag(arg0);
        return from_candid_Result_9_n9(result);
    }
    async currentId(): Promise<bigint> {
        const result = await this.actor.currentId();
        return result;
    }
    async debugApplaudsHashMap(): Promise<Array<[string, bigint]>> {
        const result = await this.actor.debugApplaudsHashMap();
        return result;
    }
    async debugGetApplaudsHashMap(): Promise<Array<[string, bigint]>> {
        const result = await this.actor.debugGetApplaudsHashMap();
        return result;
    }
    async debugMembersOnlyStatusOfExistingDraftArticles(): Promise<Result_8> {
        const result = await this.actor.debugMembersOnlyStatusOfExistingDraftArticles();
        return from_candid_Result_8_n5(result);
    }
    async debugSaveMultiplePosts(arg0: Array<PostSaveModel>): Promise<Array<Result_4>> {
        const result = await this.actor.debugSaveMultiplePosts(to_candid_vec_n11(arg0));
        return from_candid_vec_n14(result);
    }
    async delete_(arg0: string): Promise<Result_3> {
        const result = await this.actor.delete(arg0);
        return from_candid_Result_3_n20(result);
    }
    async deletePostFromUserDebug(arg0: string, arg1: string): Promise<Result_8> {
        const result = await this.actor.deletePostFromUserDebug(arg0, arg1);
        return from_candid_Result_8_n5(result);
    }
    async deleteUserPosts(arg0: string): Promise<Result_3> {
        const result = await this.actor.deleteUserPosts(arg0);
        return from_candid_Result_3_n20(result);
    }
    async dumpIds(): Promise<Result_1> {
        const result = await this.actor.dumpIds();
        return from_candid_Result_1_n1(result);
    }
    async dumpPosts(): Promise<Result_1> {
        const result = await this.actor.dumpPosts();
        return from_candid_Result_1_n1(result);
    }
    async dumpUserIds(): Promise<Result_1> {
        const result = await this.actor.dumpUserIds();
        return from_candid_Result_1_n1(result);
    }
    async followTag(arg0: string): Promise<Result_1> {
        const result = await this.actor.followTag(arg0);
        return from_candid_Result_1_n1(result);
    }
    async followTags(arg0: Array<string>): Promise<Result_1> {
        const result = await this.actor.followTags(arg0);
        return from_candid_Result_1_n1(result);
    }
    async generateLatestPosts(): Promise<void> {
        const result = await this.actor.generateLatestPosts();
        return result;
    }
    async generatePublishedDates(): Promise<void> {
        const result = await this.actor.generatePublishedDates();
        return result;
    }
    async getActiveBucketCanisterId(): Promise<Result_2> {
        const result = await this.actor.getActiveBucketCanisterId();
        return from_candid_Result_2_n7(result);
    }
    async getAdmins(): Promise<Result_8> {
        const result = await this.actor.getAdmins();
        return from_candid_Result_8_n5(result);
    }
    async getAllBuckets(): Promise<Result_8> {
        const result = await this.actor.getAllBuckets();
        return from_candid_Result_8_n5(result);
    }
    async getAllNftCanisters(): Promise<Array<[string, string]>> {
        const result = await this.actor.getAllNftCanisters();
        return result;
    }
    async getAllStatusCount(): Promise<Result_2> {
        const result = await this.actor.getAllStatusCount();
        return from_candid_Result_2_n7(result);
    }
    async getAllTags(): Promise<Array<TagModel>> {
        const result = await this.actor.getAllTags();
        return result;
    }
    async getBucketCanisterIdsOfGivenHandles(arg0: Array<string>): Promise<Array<string>> {
        const result = await this.actor.getBucketCanisterIdsOfGivenHandles(arg0);
        return result;
    }
    async getBucketCanisters(): Promise<Array<[string, string]>> {
        const result = await this.actor.getBucketCanisters();
        return result;
    }
    async getCanisterVersion(): Promise<string> {
        const result = await this.actor.getCanisterVersion();
        return result;
    }
    async getCgUsers(): Promise<Result_8> {
        const result = await this.actor.getCgUsers();
        return from_candid_Result_8_n5(result);
    }
    async getFrontendCanisterId(): Promise<Result_2> {
        const result = await this.actor.getFrontendCanisterId();
        return from_candid_Result_2_n7(result);
    }
    async getHistoricalPublishedArticlesData(): Promise<Array<[string, bigint]>> {
        const result = await this.actor.getHistoricalPublishedArticlesData();
        return result;
    }
    async getKinicList(): Promise<Result_8> {
        const result = await this.actor.getKinicList();
        return from_candid_Result_8_n5(result);
    }
    async getLastWeekRejectedPostKeyProperties(): Promise<Array<PostKeyProperties>> {
        const result = await this.actor.getLastWeekRejectedPostKeyProperties();
        return result;
    }
    async getLatestPosts(arg0: number, arg1: number): Promise<GetPostsByFollowers> {
        const result = await this.actor.getLatestPosts(arg0, arg1);
        return result;
    }
    async getLatestTimerCall(): Promise<[string, string]> {
        const result = await this.actor.getLatestTimerCall();
        return [
            result[0],
            result[1]
        ];
    }
    async getList(arg0: Array<string>): Promise<Array<PostKeyProperties>> {
        const result = await this.actor.getList(arg0);
        return result;
    }
    async getMaxMemorySize(): Promise<bigint> {
        const result = await this.actor.getMaxMemorySize();
        return result;
    }
    async getMemorySize(): Promise<bigint> {
        const result = await this.actor.getMemorySize();
        return result;
    }
    async getMoreArticlesFromUsers(arg0: string, arg1: Array<string>): Promise<Array<Array<PostKeyProperties>>> {
        const result = await this.actor.getMoreArticlesFromUsers(arg0, arg1);
        return result;
    }
    async getMoreLatestPosts(arg0: number, arg1: number): Promise<Array<PostKeyProperties>> {
        const result = await this.actor.getMoreLatestPosts(arg0, arg1);
        return result;
    }
    async getMyAllPosts(arg0: number, arg1: number): Promise<Array<PostKeyProperties>> {
        const result = await this.actor.getMyAllPosts(arg0, arg1);
        return result;
    }
    async getMyDailyPostsStatus(): Promise<boolean> {
        const result = await this.actor.getMyDailyPostsStatus();
        return result;
    }
    async getMyDraftPosts(arg0: number, arg1: number): Promise<Array<PostKeyProperties>> {
        const result = await this.actor.getMyDraftPosts(arg0, arg1);
        return result;
    }
    async getMyFollowingTagsPostKeyProperties(arg0: number, arg1: number): Promise<GetPostsByFollowers> {
        const result = await this.actor.getMyFollowingTagsPostKeyProperties(arg0, arg1);
        return result;
    }
    async getMyPlannedPosts(arg0: number, arg1: number): Promise<Array<PostKeyProperties>> {
        const result = await this.actor.getMyPlannedPosts(arg0, arg1);
        return result;
    }
    async getMyPublishedPosts(arg0: number, arg1: number): Promise<Array<PostKeyProperties>> {
        const result = await this.actor.getMyPublishedPosts(arg0, arg1);
        return result;
    }
    async getMySubmittedToReviewPosts(arg0: number, arg1: number): Promise<Array<PostKeyProperties>> {
        const result = await this.actor.getMySubmittedToReviewPosts(arg0, arg1);
        return result;
    }
    async getMyTags(): Promise<Array<PostTagModel__1>> {
        const result = await this.actor.getMyTags();
        return result;
    }
    async getNextPostId(): Promise<Result_2> {
        const result = await this.actor.getNextPostId();
        return from_candid_Result_2_n7(result);
    }
    async getNextPostIdsDebug(arg0: bigint): Promise<Result_2> {
        const result = await this.actor.getNextPostIdsDebug(arg0);
        return from_candid_Result_2_n7(result);
    }
    async getPlatformOperators(): Promise<List> {
        const result = await this.actor.getPlatformOperators();
        return from_candid_List_n22(result);
    }
    async getPopular(arg0: number, arg1: number): Promise<GetPostsByFollowers> {
        const result = await this.actor.getPopular(arg0, arg1);
        return result;
    }
    async getPopularThisMonth(arg0: number, arg1: number): Promise<GetPostsByFollowers> {
        const result = await this.actor.getPopularThisMonth(arg0, arg1);
        return result;
    }
    async getPopularThisWeek(arg0: number, arg1: number): Promise<GetPostsByFollowers> {
        const result = await this.actor.getPopularThisWeek(arg0, arg1);
        return result;
    }
    async getPopularToday(arg0: number, arg1: number): Promise<GetPostsByFollowers> {
        const result = await this.actor.getPopularToday(arg0, arg1);
        return result;
    }
    async getPostKeyProperties(arg0: string): Promise<Result_5> {
        const result = await this.actor.getPostKeyProperties(arg0);
        return from_candid_Result_5_n25(result);
    }
    async getPostUrls(): Promise<Result_2> {
        const result = await this.actor.getPostUrls();
        return from_candid_Result_2_n7(result);
    }
    async getPostViewsPerHourLast24Hours(): Promise<[bigint, Array<[bigint, bigint]>]> {
        const result = await this.actor.getPostViewsPerHourLast24Hours();
        return [
            result[0],
            result[1]
        ];
    }
    async getPostsByCategory(arg0: string, arg1: string, arg2: number, arg3: number): Promise<GetPostsByFollowers> {
        const result = await this.actor.getPostsByCategory(arg0, arg1, arg2, arg3);
        return result;
    }
    async getPostsByFollowers(arg0: Array<string>, arg1: number, arg2: number): Promise<GetPostsByFollowers> {
        const result = await this.actor.getPostsByFollowers(arg0, arg1, arg2);
        return result;
    }
    async getPostsByPostIds(arg0: Array<string>): Promise<Array<PostKeyProperties>> {
        const result = await this.actor.getPostsByPostIds(arg0);
        return result;
    }
    async getPostsByPostIdsMigration(arg0: Array<string>): Promise<Array<PostKeyProperties>> {
        const result = await this.actor.getPostsByPostIdsMigration(arg0);
        return result;
    }
    async getPostsPerHourLast24Hours(): Promise<[bigint, Array<[bigint, bigint]>]> {
        const result = await this.actor.getPostsPerHourLast24Hours();
        return [
            result[0],
            result[1]
        ];
    }
    async getPublicationCanisters(): Promise<Array<[string, string]>> {
        const result = await this.actor.getPublicationCanisters();
        return result;
    }
    async getPublicationPosts(arg0: number, arg1: number, arg2: string): Promise<Array<PostKeyProperties>> {
        const result = await this.actor.getPublicationPosts(arg0, arg1, arg2);
        return result;
    }
    async getTagFollowers(arg0: string): Promise<Result_8> {
        const result = await this.actor.getTagFollowers(arg0);
        return from_candid_Result_8_n5(result);
    }
    async getTagsByUser(arg0: string): Promise<Array<PostTag>> {
        const result = await this.actor.getTagsByUser(arg0);
        return result;
    }
    async getTotalAmountOfTipsReceived(): Promise<bigint> {
        const result = await this.actor.getTotalAmountOfTipsReceived();
        return result;
    }
    async getTotalArticleViews(): Promise<bigint> {
        const result = await this.actor.getTotalArticleViews();
        return result;
    }
    async getTotalClaps(): Promise<bigint> {
        const result = await this.actor.getTotalClaps();
        return result;
    }
    async getTotalPostCount(): Promise<bigint> {
        const result = await this.actor.getTotalPostCount();
        return result;
    }
    async getTrustedCanisters(): Promise<Result_8> {
        const result = await this.actor.getTrustedCanisters();
        return from_candid_Result_8_n5(result);
    }
    async getUserDailyAllowedPostNumber(): Promise<bigint> {
        const result = await this.actor.getUserDailyAllowedPostNumber();
        return result;
    }
    async getUserPostCounts(arg0: string): Promise<UserPostCounts> {
        const result = await this.actor.getUserPostCounts(arg0);
        return result;
    }
    async getUserPostIds(arg0: string): Promise<Result_8> {
        const result = await this.actor.getUserPostIds(arg0);
        return from_candid_Result_8_n5(result);
    }
    async getUserPosts(arg0: string): Promise<Array<PostKeyProperties>> {
        const result = await this.actor.getUserPosts(arg0);
        return result;
    }
    async getUsersPostCountsByHandles(arg0: Array<string>): Promise<Array<UserPostCounts>> {
        const result = await this.actor.getUsersPostCountsByHandles(arg0);
        return result;
    }
    async getViewsByRange(arg0: RecallOptions): Promise<bigint> {
        const result = await this.actor.getViewsByRange(to_candid_RecallOptions_n27(arg0));
        return result;
    }
    async getWasmChunks(): Promise<Result_7> {
        const result = await this.actor.getWasmChunks();
        return from_candid_Result_7_n29(result);
    }
    async handleModclubMigration(arg0: string): Promise<Result_2> {
        const result = await this.actor.handleModclubMigration(arg0);
        return from_candid_Result_2_n7(result);
    }
    async icrc10_supported_standards(): Promise<Array<SupportedStandard>> {
        const result = await this.actor.icrc10_supported_standards();
        return result;
    }
    async icrc28_trusted_origins(): Promise<Icrc28TrustedOriginsResponse> {
        const result = await this.actor.icrc28_trusted_origins();
        return result;
    }
    async idQuick(): Promise<Principal> {
        const result = await this.actor.idQuick();
        return result;
    }
    async incrementApplauds(arg0: string, arg1: bigint): Promise<void> {
        const result = await this.actor.incrementApplauds(arg0, arg1);
        return result;
    }
    async indexPopular(): Promise<void> {
        const result = await this.actor.indexPopular();
        return result;
    }
    async initializeCanister(arg0: string, arg1: string, arg2: string): Promise<Result_2> {
        const result = await this.actor.initializeCanister(arg0, arg1, arg2);
        return from_candid_Result_2_n7(result);
    }
    async initializePostCoreCanister(): Promise<Result_2> {
        const result = await this.actor.initializePostCoreCanister();
        return from_candid_Result_2_n7(result);
    }
    async isEditorPublic(arg0: string, arg1: Principal): Promise<boolean> {
        const result = await this.actor.isEditorPublic(arg0, arg1);
        return result;
    }
    async isThereEnoughMemory(): Promise<boolean> {
        const result = await this.actor.isThereEnoughMemory();
        return result;
    }
    async isWriterPublic(arg0: string, arg1: Principal): Promise<boolean> {
        const result = await this.actor.isWriterPublic(arg0, arg1);
        return result;
    }
    async makePostPublication(arg0: string, arg1: string, arg2: string, arg3: boolean, arg4: bigint): Promise<void> {
        const result = await this.actor.makePostPublication(arg0, arg1, arg2, arg3, arg4);
        return result;
    }
    async migrateAllPublicationEditorsAndWriters(): Promise<Result_6> {
        const result = await this.actor.migrateAllPublicationEditorsAndWriters();
        return from_candid_Result_6_n31(result);
    }
    async migrateModclubInterface(): Promise<Result_2> {
        const result = await this.actor.migrateModclubInterface();
        return from_candid_Result_2_n7(result);
    }
    async migratePremiumArticleFromOldArch(): Promise<Result_5> {
        const result = await this.actor.migratePremiumArticleFromOldArch();
        return from_candid_Result_5_n25(result);
    }
    async modClubCallback(arg0: ContentResult): Promise<void> {
        const result = await this.actor.modClubCallback(to_candid_ContentResult_n33(arg0));
        return result;
    }
    async refreshUserPostIds(arg0: string): Promise<Result_3> {
        const result = await this.actor.refreshUserPostIds(arg0);
        return from_candid_Result_3_n20(result);
    }
    async registerAdmin(arg0: string): Promise<Result_1> {
        const result = await this.actor.registerAdmin(arg0);
        return from_candid_Result_1_n1(result);
    }
    async registerCanister(arg0: string): Promise<Result_1> {
        const result = await this.actor.registerCanister(arg0);
        return from_candid_Result_1_n1(result);
    }
    async registerCgUser(arg0: string): Promise<Result_1> {
        const result = await this.actor.registerCgUser(arg0);
        return from_candid_Result_1_n1(result);
    }
    async registerPlatformOperator(arg0: string): Promise<Result_1> {
        const result = await this.actor.registerPlatformOperator(arg0);
        return from_candid_Result_1_n1(result);
    }
    async registerPublisher(): Promise<void> {
        const result = await this.actor.registerPublisher();
        return result;
    }
    async reindex(): Promise<Result_2> {
        const result = await this.actor.reindex();
        return from_candid_Result_2_n7(result);
    }
    async removePostFromPopularityArrays(arg0: string): Promise<void> {
        const result = await this.actor.removePostFromPopularityArrays(arg0);
        return result;
    }
    async removePostIdToUserDebug(arg0: string, arg1: string): Promise<Result_1> {
        const result = await this.actor.removePostIdToUserDebug(arg0, arg1);
        return from_candid_Result_1_n1(result);
    }
    async resetWasmChunks(): Promise<void> {
        const result = await this.actor.resetWasmChunks();
        return result;
    }
    async save(arg0: PostSaveModel): Promise<Result_4> {
        const result = await this.actor.save(to_candid_PostSaveModel_n12(arg0));
        return from_candid_Result_4_n15(result);
    }
    async sendNewArticleNotification(arg0: PostBucketType): Promise<void> {
        const result = await this.actor.sendNewArticleNotification(to_candid_PostBucketType_n37(arg0));
        return result;
    }
    async setFrontendCanisterId(arg0: string): Promise<Result_2> {
        const result = await this.actor.setFrontendCanisterId(arg0);
        return from_candid_Result_2_n7(result);
    }
    async setMaxMemorySize(arg0: bigint): Promise<Result_3> {
        const result = await this.actor.setMaxMemorySize(arg0);
        return from_candid_Result_3_n20(result);
    }
    async setUpModClub(arg0: string): Promise<void> {
        const result = await this.actor.setUpModClub(arg0);
        return result;
    }
    async setUserDailyAllowedPostNumber(arg0: bigint): Promise<Result_3> {
        const result = await this.actor.setUserDailyAllowedPostNumber(arg0);
        return from_candid_Result_3_n20(result);
    }
    async simulateModClub(arg0: string, arg1: PostModerationStatusV2): Promise<void> {
        const result = await this.actor.simulateModClub(arg0, to_candid_PostModerationStatusV2_n39(arg1));
        return result;
    }
    async sortPopularPosts(arg0: PopularityType): Promise<void> {
        const result = await this.actor.sortPopularPosts(to_candid_PopularityType_n40(arg0));
        return result;
    }
    async storeAllSEO(): Promise<Result_1> {
        const result = await this.actor.storeAllSEO();
        return from_candid_Result_1_n1(result);
    }
    async testInstructionSize(): Promise<string> {
        const result = await this.actor.testInstructionSize();
        return result;
    }
    async unfollowTag(arg0: string): Promise<Result_1> {
        const result = await this.actor.unfollowTag(arg0);
        return from_candid_Result_1_n1(result);
    }
    async unregisterAdmin(arg0: string): Promise<Result_1> {
        const result = await this.actor.unregisterAdmin(arg0);
        return from_candid_Result_1_n1(result);
    }
    async unregisterCanister(arg0: string): Promise<Result_1> {
        const result = await this.actor.unregisterCanister(arg0);
        return from_candid_Result_1_n1(result);
    }
    async unregisterCgUser(arg0: string): Promise<Result_1> {
        const result = await this.actor.unregisterCgUser(arg0);
        return from_candid_Result_1_n1(result);
    }
    async unregisterPlatformOperator(arg0: string): Promise<Result_1> {
        const result = await this.actor.unregisterPlatformOperator(arg0);
        return from_candid_Result_1_n1(result);
    }
    async updateHandle(arg0: string, arg1: string): Promise<Result_2> {
        const result = await this.actor.updateHandle(arg0, arg1);
        return from_candid_Result_2_n7(result);
    }
    async updatePostDraft(arg0: string, arg1: boolean, arg2: bigint, arg3: string): Promise<PostKeyProperties> {
        const result = await this.actor.updatePostDraft(arg0, arg1, arg2, arg3);
        return result;
    }
    async updatePublicationEditorsAndWriters(arg0: string, arg1: Array<string>, arg2: Array<string>): Promise<Result_1> {
        const result = await this.actor.updatePublicationEditorsAndWriters(arg0, arg1, arg2);
        return from_candid_Result_1_n1(result);
    }
    async updateSettingsForAllBucketCanisters(): Promise<Result_2> {
        const result = await this.actor.updateSettingsForAllBucketCanisters();
        return from_candid_Result_2_n7(result);
    }
    async upgradeAllBuckets(arg0: string, arg1: Uint8Array): Promise<Result_1> {
        const result = await this.actor.upgradeAllBuckets(arg0, arg1);
        return from_candid_Result_1_n1(result);
    }
    async upgradeBucket(arg0: string, arg1: Uint8Array): Promise<Result_1> {
        const result = await this.actor.upgradeBucket(arg0, arg1);
        return from_candid_Result_1_n1(result);
    }
    async validate(arg0: any): Promise<Validate> {
        const result = await this.actor.validate(arg0);
        return from_candid_Validate_n42(result);
    }
    async verifyMigration(): Promise<Result> {
        const result = await this.actor.verifyMigration();
        return from_candid_Result_n44(result);
    }
    async viewPost(arg0: string): Promise<void> {
        const result = await this.actor.viewPost(arg0);
        return result;
    }
}
function from_candid_List_n22(value: _List): List {
    return from_candid_opt_n23(value);
}
function from_candid_Post_n17(value: _Post): Post {
    return from_candid_record_n18(value);
}
function from_candid_Result_10_n3(value: _Result_10): Result_10 {
    return from_candid_variant_n4(value);
}
function from_candid_Result_1_n1(value: _Result_1): Result_1 {
    return from_candid_variant_n2(value);
}
function from_candid_Result_2_n7(value: _Result_2): Result_2 {
    return from_candid_variant_n8(value);
}
function from_candid_Result_3_n20(value: _Result_3): Result_3 {
    return from_candid_variant_n21(value);
}
function from_candid_Result_4_n15(value: _Result_4): Result_4 {
    return from_candid_variant_n16(value);
}
function from_candid_Result_5_n25(value: _Result_5): Result_5 {
    return from_candid_variant_n26(value);
}
function from_candid_Result_6_n31(value: _Result_6): Result_6 {
    return from_candid_variant_n32(value);
}
function from_candid_Result_7_n29(value: _Result_7): Result_7 {
    return from_candid_variant_n30(value);
}
function from_candid_Result_8_n5(value: _Result_8): Result_8 {
    return from_candid_variant_n6(value);
}
function from_candid_Result_9_n9(value: _Result_9): Result_9 {
    return from_candid_variant_n10(value);
}
function from_candid_Result_n44(value: _Result): Result {
    return from_candid_variant_n45(value);
}
function from_candid_Validate_n42(value: _Validate): Validate {
    return from_candid_variant_n43(value);
}
function from_candid_opt_n19(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(value: [] | [[string, _List]]): [string, List] | null {
    return value.length === 0 ? null : from_candid_tuple_n24(value[0]);
}
function from_candid_record_n18(value: {
    url: string;
    bucketCanisterId: string;
    title: string;
    created: string;
    modified: string;
    content: string;
    views: string;
    wordCount: string;
    isPremium: boolean;
    publishedDate: string;
    claps: string;
    tags: Array<_PostTagModel>;
    nftCanisterId: [] | [string];
    isDraft: boolean;
    creatorPrincipal: string;
    category: string;
    handle: string;
    creatorHandle: string;
    headerImage: string;
    isMembersOnly: boolean;
    subtitle: string;
    isPublication: boolean;
    postId: string;
}): {
    url: string;
    bucketCanisterId: string;
    title: string;
    created: string;
    modified: string;
    content: string;
    views: string;
    wordCount: string;
    isPremium: boolean;
    publishedDate: string;
    claps: string;
    tags: Array<PostTagModel>;
    nftCanisterId?: string;
    isDraft: boolean;
    creatorPrincipal: string;
    category: string;
    handle: string;
    creatorHandle: string;
    headerImage: string;
    isMembersOnly: boolean;
    subtitle: string;
    isPublication: boolean;
    postId: string;
} {
    return {
        url: value.url,
        bucketCanisterId: value.bucketCanisterId,
        title: value.title,
        created: value.created,
        modified: value.modified,
        content: value.content,
        views: value.views,
        wordCount: value.wordCount,
        isPremium: value.isPremium,
        publishedDate: value.publishedDate,
        claps: value.claps,
        tags: value.tags,
        nftCanisterId: record_opt_to_undefined(from_candid_opt_n19(value.nftCanisterId)),
        isDraft: value.isDraft,
        creatorPrincipal: value.creatorPrincipal,
        category: value.category,
        handle: value.handle,
        creatorHandle: value.creatorHandle,
        headerImage: value.headerImage,
        isMembersOnly: value.isMembersOnly,
        subtitle: value.subtitle,
        isPublication: value.isPublication,
        postId: value.postId
    };
}
function from_candid_tuple_n24(value: [string, _List]): [string, List] {
    return [
        value[0],
        from_candid_List_n22(value[1])
    ];
}
function from_candid_variant_n10(value: {
    ok: _TagModel;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: TagModel;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n16(value: {
    ok: _Post;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Post;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Post_n17(value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n26(value: {
    ok: _PostKeyProperties;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PostKeyProperties;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n30(value: {
    ok: Uint8Array;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Uint8Array;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n32(value: {
    ok: [Array<[string, Array<string>]>, Array<[string, Array<string>]>];
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: [Array<[string, Array<string>]>, Array<[string, Array<string>]>];
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(value: {
    ok: Array<[string, string]>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<[string, string]>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n43(value: {
    Ok: string;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: string;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n45(value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(value: {
    ok: Array<string>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<string>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n14(value: Array<_Result_4>): Array<Result_4> {
    return value.map((x)=>from_candid_Result_4_n15(x));
}
function to_candid_ContentResult_n33(value: ContentResult): _ContentResult {
    return to_candid_record_n34(value);
}
function to_candid_ContentStatus_n35(value: ContentStatus): _ContentStatus {
    return to_candid_variant_n36(value);
}
function to_candid_PopularityType_n40(value: PopularityType): _PopularityType {
    return to_candid_variant_n41(value);
}
function to_candid_PostBucketType_n37(value: PostBucketType): _PostBucketType {
    return to_candid_record_n38(value);
}
function to_candid_PostModerationStatusV2_n39(value: PostModerationStatusV2): _PostModerationStatusV2 {
    return to_candid_variant_n36(value);
}
function to_candid_PostSaveModel_n12(value: PostSaveModel): _PostSaveModel {
    return to_candid_record_n13(value);
}
function to_candid_RecallOptions_n27(value: RecallOptions): _RecallOptions {
    return to_candid_variant_n28(value);
}
function to_candid_record_n13(value: {
    title: string;
    content: string;
    premium?: {
        thumbnail: string;
        icpPrice: bigint;
        maxSupply: bigint;
    };
    isDraft: boolean;
    tagIds: Array<string>;
    category: string;
    handle: string;
    creatorHandle: string;
    headerImage: string;
    isMembersOnly: boolean;
    scheduledPublishedDate?: bigint;
    subtitle: string;
    isPublication: boolean;
    postId: string;
}): {
    title: string;
    content: string;
    premium: [] | [{
            thumbnail: string;
            icpPrice: bigint;
            maxSupply: bigint;
        }];
    isDraft: boolean;
    tagIds: Array<string>;
    category: string;
    handle: string;
    creatorHandle: string;
    headerImage: string;
    isMembersOnly: boolean;
    scheduledPublishedDate: [] | [bigint];
    subtitle: string;
    isPublication: boolean;
    postId: string;
} {
    return {
        title: value.title,
        content: value.content,
        premium: value.premium ? candid_some(value.premium) : candid_none(),
        isDraft: value.isDraft,
        tagIds: value.tagIds,
        category: value.category,
        handle: value.handle,
        creatorHandle: value.creatorHandle,
        headerImage: value.headerImage,
        isMembersOnly: value.isMembersOnly,
        scheduledPublishedDate: value.scheduledPublishedDate ? candid_some(value.scheduledPublishedDate) : candid_none(),
        subtitle: value.subtitle,
        isPublication: value.isPublication,
        postId: value.postId
    };
}
function to_candid_record_n34(value: {
    status: ContentStatus;
    approvedCount: bigint;
    sourceId: string;
    violatedRules: Array<ViolatedRules>;
    rejectedCount: bigint;
}): {
    status: _ContentStatus;
    approvedCount: bigint;
    sourceId: string;
    violatedRules: Array<_ViolatedRules>;
    rejectedCount: bigint;
} {
    return {
        status: to_candid_ContentStatus_n35(value.status),
        approvedCount: value.approvedCount,
        sourceId: value.sourceId,
        violatedRules: value.violatedRules,
        rejectedCount: value.rejectedCount
    };
}
function to_candid_record_n38(value: {
    url: string;
    bucketCanisterId: string;
    title: string;
    created: string;
    modified: string;
    content: string;
    wordCount: string;
    isPremium: boolean;
    publishedDate: string;
    nftCanisterId?: string;
    isDraft: boolean;
    creatorPrincipal: string;
    category: string;
    handle: string;
    postOwnerPrincipal: string;
    creatorHandle: string;
    headerImage: string;
    isMembersOnly: boolean;
    subtitle: string;
    isPublication: boolean;
    postId: string;
}): {
    url: string;
    bucketCanisterId: string;
    title: string;
    created: string;
    modified: string;
    content: string;
    wordCount: string;
    isPremium: boolean;
    publishedDate: string;
    nftCanisterId: [] | [string];
    isDraft: boolean;
    creatorPrincipal: string;
    category: string;
    handle: string;
    postOwnerPrincipal: string;
    creatorHandle: string;
    headerImage: string;
    isMembersOnly: boolean;
    subtitle: string;
    isPublication: boolean;
    postId: string;
} {
    return {
        url: value.url,
        bucketCanisterId: value.bucketCanisterId,
        title: value.title,
        created: value.created,
        modified: value.modified,
        content: value.content,
        wordCount: value.wordCount,
        isPremium: value.isPremium,
        publishedDate: value.publishedDate,
        nftCanisterId: value.nftCanisterId ? candid_some(value.nftCanisterId) : candid_none(),
        isDraft: value.isDraft,
        creatorPrincipal: value.creatorPrincipal,
        category: value.category,
        handle: value.handle,
        postOwnerPrincipal: value.postOwnerPrincipal,
        creatorHandle: value.creatorHandle,
        headerImage: value.headerImage,
        isMembersOnly: value.isMembersOnly,
        subtitle: value.subtitle,
        isPublication: value.isPublication,
        postId: value.postId
    };
}
function to_candid_variant_n28(value: RecallOptions): {
    sixtydays: null;
} | {
    today: null;
} | {
    thisWeek: null;
} | {
    thisYear: null;
} | {
    allTime: null;
} | {
    ninetydays: null;
} | {
    thisMonth: null;
} {
    return value == RecallOptions.sixtydays ? {
        sixtydays: null
    } : value == RecallOptions.today ? {
        today: null
    } : value == RecallOptions.thisWeek ? {
        thisWeek: null
    } : value == RecallOptions.thisYear ? {
        thisYear: null
    } : value == RecallOptions.allTime ? {
        allTime: null
    } : value == RecallOptions.ninetydays ? {
        ninetydays: null
    } : value == RecallOptions.thisMonth ? {
        thisMonth: null
    } : value;
}
function to_candid_variant_n36(value: PostModerationStatusV2): {
    new: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == PostModerationStatusV2.new ? {
        new_: null
    } : value == PostModerationStatusV2.approved ? {
        approved: null
    } : value == PostModerationStatusV2.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n41(value: PopularityType): {
    month: null;
} | {
    today: null;
} | {
    ever: null;
} | {
    week: null;
} {
    return value == PopularityType.month ? {
        month: null
    } : value == PopularityType.today ? {
        today: null
    } : value == PopularityType.ever ? {
        ever: null
    } : value == PopularityType.week ? {
        week: null
    } : value;
}
function to_candid_vec_n11(value: Array<PostSaveModel>): Array<_PostSaveModel> {
    return value.map((x)=>to_candid_PostSaveModel_n12(x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): PostCore {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new PostCore(actor);
}
