/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/Icrc1Archive.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface Account {
    owner: Principal;
    subaccount?: Uint8Array;
}
export type Block = Value;
export type BlockIndex = bigint;
export type Value = {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Map_;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Nat64";
    Nat64: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Array";
    Array: Array<Value>;
};
export type Map_ = Array<[string, Value]>;
export interface Transaction {
    burn?: {
        from: Account;
        memo?: Uint8Array;
        created_at_time?: bigint;
        amount: bigint;
    };
    kind: string;
    mint?: {
        to: Account;
        memo?: Uint8Array;
        created_at_time?: bigint;
        amount: bigint;
    };
    timestamp: bigint;
    transfer?: {
        to: Account;
        from: Account;
        memo?: Uint8Array;
        created_at_time?: bigint;
        amount: bigint;
    };
}
export interface Icrc1ArchiveInterface {
    append_blocks(arg0: Array<Uint8Array>): Promise<void>;
    get_blocks(arg0: {
        start: bigint;
        length: bigint;
    }): Promise<{
        blocks: Array<Block>;
    }>;
    get_transaction(arg0: bigint): Promise<Transaction | null>;
    get_transactions(arg0: {
        start: bigint;
        length: bigint;
    }): Promise<{
        transactions: Array<Transaction>;
    }>;
    remaining_capacity(): Promise<bigint>;
}
import type { Account as _Account, Block as _Block, Map as _Map, Transaction as _Transaction, Value as _Value } from "./declarations/Icrc1Archive.did";
export class Icrc1Archive implements Icrc1ArchiveInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async append_blocks(arg0: Array<Uint8Array>): Promise<void> {
        const result = await this.actor.append_blocks(arg0);
        return result;
    }
    async get_blocks(arg0: {
        start: bigint;
        length: bigint;
    }): Promise<{
        blocks: Array<Block>;
    }> {
        const result = await this.actor.get_blocks(arg0);
        return from_candid_record_n1(result);
    }
    async get_transaction(arg0: bigint): Promise<Transaction | null> {
        const result = await this.actor.get_transaction(arg0);
        return from_candid_opt_n10(result);
    }
    async get_transactions(arg0: {
        start: bigint;
        length: bigint;
    }): Promise<{
        transactions: Array<Transaction>;
    }> {
        const result = await this.actor.get_transactions(arg0);
        return from_candid_record_n23(result);
    }
    async remaining_capacity(): Promise<bigint> {
        const result = await this.actor.remaining_capacity();
        return result;
    }
}
function from_candid_Account_n15(value: _Account): Account {
    return from_candid_record_n16(value);
}
function from_candid_Block_n3(value: _Block): Block {
    return from_candid_variant_n4(value);
}
function from_candid_Map_n5(value: _Map): Map_ {
    return from_candid_vec_n6(value);
}
function from_candid_Transaction_n11(value: _Transaction): Transaction {
    return from_candid_record_n12(value);
}
function from_candid_Value_n8(value: _Value): Value {
    return from_candid_variant_n4(value);
}
function from_candid_opt_n10(value: [] | [_Transaction]): Transaction | null {
    return value.length === 0 ? null : from_candid_Transaction_n11(value[0]);
}
function from_candid_opt_n13(value: [] | [{
        from: _Account;
        memo: [] | [Uint8Array];
        created_at_time: [] | [bigint];
        amount: bigint;
    }]): {
    from: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
} | null {
    return value.length === 0 ? null : from_candid_record_n14(value[0]);
}
function from_candid_opt_n17(value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(value: [] | [{
        to: _Account;
        memo: [] | [Uint8Array];
        created_at_time: [] | [bigint];
        amount: bigint;
    }]): {
    to: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
} | null {
    return value.length === 0 ? null : from_candid_record_n20(value[0]);
}
function from_candid_opt_n21(value: [] | [{
        to: _Account;
        from: _Account;
        memo: [] | [Uint8Array];
        created_at_time: [] | [bigint];
        amount: bigint;
    }]): {
    to: Account;
    from: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
} | null {
    return value.length === 0 ? null : from_candid_record_n22(value[0]);
}
function from_candid_record_n1(value: {
    blocks: Array<_Block>;
}): {
    blocks: Array<Block>;
} {
    return {
        blocks: from_candid_vec_n2(value.blocks)
    };
}
function from_candid_record_n12(value: {
    burn: [] | [{
            from: _Account;
            memo: [] | [Uint8Array];
            created_at_time: [] | [bigint];
            amount: bigint;
        }];
    kind: string;
    mint: [] | [{
            to: _Account;
            memo: [] | [Uint8Array];
            created_at_time: [] | [bigint];
            amount: bigint;
        }];
    timestamp: bigint;
    transfer: [] | [{
            to: _Account;
            from: _Account;
            memo: [] | [Uint8Array];
            created_at_time: [] | [bigint];
            amount: bigint;
        }];
}): {
    burn?: {
        from: Account;
        memo?: Uint8Array;
        created_at_time?: bigint;
        amount: bigint;
    };
    kind: string;
    mint?: {
        to: Account;
        memo?: Uint8Array;
        created_at_time?: bigint;
        amount: bigint;
    };
    timestamp: bigint;
    transfer?: {
        to: Account;
        from: Account;
        memo?: Uint8Array;
        created_at_time?: bigint;
        amount: bigint;
    };
} {
    return {
        burn: record_opt_to_undefined(from_candid_opt_n13(value.burn)),
        kind: value.kind,
        mint: record_opt_to_undefined(from_candid_opt_n19(value.mint)),
        timestamp: value.timestamp,
        transfer: record_opt_to_undefined(from_candid_opt_n21(value.transfer))
    };
}
function from_candid_record_n14(value: {
    from: _Account;
    memo: [] | [Uint8Array];
    created_at_time: [] | [bigint];
    amount: bigint;
}): {
    from: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
} {
    return {
        from: from_candid_Account_n15(value.from),
        memo: record_opt_to_undefined(from_candid_opt_n17(value.memo)),
        created_at_time: record_opt_to_undefined(from_candid_opt_n18(value.created_at_time)),
        amount: value.amount
    };
}
function from_candid_record_n16(value: {
    owner: Principal;
    subaccount: [] | [Uint8Array];
}): {
    owner: Principal;
    subaccount?: Uint8Array;
} {
    return {
        owner: value.owner,
        subaccount: record_opt_to_undefined(from_candid_opt_n17(value.subaccount))
    };
}
function from_candid_record_n20(value: {
    to: _Account;
    memo: [] | [Uint8Array];
    created_at_time: [] | [bigint];
    amount: bigint;
}): {
    to: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
} {
    return {
        to: from_candid_Account_n15(value.to),
        memo: record_opt_to_undefined(from_candid_opt_n17(value.memo)),
        created_at_time: record_opt_to_undefined(from_candid_opt_n18(value.created_at_time)),
        amount: value.amount
    };
}
function from_candid_record_n22(value: {
    to: _Account;
    from: _Account;
    memo: [] | [Uint8Array];
    created_at_time: [] | [bigint];
    amount: bigint;
}): {
    to: Account;
    from: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
} {
    return {
        to: from_candid_Account_n15(value.to),
        from: from_candid_Account_n15(value.from),
        memo: record_opt_to_undefined(from_candid_opt_n17(value.memo)),
        created_at_time: record_opt_to_undefined(from_candid_opt_n18(value.created_at_time)),
        amount: value.amount
    };
}
function from_candid_record_n23(value: {
    transactions: Array<_Transaction>;
}): {
    transactions: Array<Transaction>;
} {
    return {
        transactions: from_candid_vec_n24(value.transactions)
    };
}
function from_candid_tuple_n7(value: [string, _Value]): [string, Value] {
    return [
        value[0],
        from_candid_Value_n8(value[1])
    ];
}
function from_candid_variant_n4(value: {
    Int: bigint;
} | {
    Map: _Map;
} | {
    Nat: bigint;
} | {
    Nat64: bigint;
} | {
    Blob: Uint8Array;
} | {
    Text: string;
} | {
    Array: Array<_Value>;
}): {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Map_;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Nat64";
    Nat64: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Array";
    Array: Array<Value>;
} {
    return "Int" in value ? {
        __kind__: "Int",
        Int: value.Int
    } : "Map" in value ? {
        __kind__: "Map",
        Map: from_candid_Map_n5(value.Map)
    } : "Nat" in value ? {
        __kind__: "Nat",
        Nat: value.Nat
    } : "Nat64" in value ? {
        __kind__: "Nat64",
        Nat64: value.Nat64
    } : "Blob" in value ? {
        __kind__: "Blob",
        Blob: value.Blob
    } : "Text" in value ? {
        __kind__: "Text",
        Text: value.Text
    } : "Array" in value ? {
        __kind__: "Array",
        Array: from_candid_vec_n9(value.Array)
    } : value;
}
function from_candid_vec_n2(value: Array<_Block>): Array<Block> {
    return value.map((x)=>from_candid_Block_n3(x));
}
function from_candid_vec_n24(value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n11(x));
}
function from_candid_vec_n6(value: Array<[string, _Value]>): Array<[string, Value]> {
    return value.map((x)=>from_candid_tuple_n7(x));
}
function from_candid_vec_n9(value: Array<_Value>): Array<Value> {
    return value.map((x)=>from_candid_Value_n8(x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Icrc1Archive {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Icrc1Archive(actor);
}
