/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/Notifications.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export type NotificationContent__1 = {
    __kind__: "FaucetClaimAvailable";
    FaucetClaimAvailable: null;
} | {
    __kind__: "TipReceived";
    TipReceived: {
        bucketCanisterId: string;
        amountOfTokens: string;
        tipSenderPrincipal: string;
        publicationPrincipalId?: string;
        postTitle: string;
        numberOfApplauds: string;
        tippedTokenSymbol: string;
        postId: string;
    };
} | {
    __kind__: "NewArticleByFollowedWriter";
    NewArticleByFollowedWriter: {
        bucketCanisterId: string;
        postWriterPrincipal: string;
        postTitle: string;
        postId: string;
    };
} | {
    __kind__: "AuthorLosesSubscriber";
    AuthorLosesSubscriber: {
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscriberPrincipalId: string;
    };
} | {
    __kind__: "YouSubscribedToAuthor";
    YouSubscribedToAuthor: {
        amountOfTokens: string;
        subscriptionEndTime: string;
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscribedWriterPrincipalId: string;
        subscriptionStartTime: string;
        isPublication: boolean;
    };
} | {
    __kind__: "NewCommentOnMyArticle";
    NewCommentOnMyArticle: {
        bucketCanisterId: string;
        commentId: string;
        isReply: boolean;
        commentContent: string;
        postTitle: string;
        commenterPrincipal: string;
        postId: string;
    };
} | {
    __kind__: "VerifyProfile";
    VerifyProfile: null;
} | {
    __kind__: "YouUnsubscribedFromAuthor";
    YouUnsubscribedFromAuthor: {
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscribedWriterPrincipalId: string;
        isPublication: boolean;
    };
} | {
    __kind__: "NewFollower";
    NewFollower: {
        followerPrincipalId: string;
    };
} | {
    __kind__: "ReaderExpiredSubscription";
    ReaderExpiredSubscription: {
        amountOfTokens: string;
        subscriptionEndTime: string;
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscribedWriterPrincipalId: string;
        subscriptionStartTime: string;
        isPublication: boolean;
    };
} | {
    __kind__: "ReplyToMyComment";
    ReplyToMyComment: {
        bucketCanisterId: string;
        postWriterPrincipal: string;
        myCommentId: string;
        myCommentContent: string;
        replyCommentContent: string;
        postTitle: string;
        replyCommenterPrincipal: string;
        replyCommentId: string;
        postId: string;
    };
} | {
    __kind__: "PremiumArticleSold";
    PremiumArticleSold: {
        bucketCanisterId: string;
        amountOfTokens: string;
        publicationPrincipalId?: string;
        purchasedTokenSymbol: string;
        purchaserPrincipal: string;
        postTitle: string;
        postId: string;
    };
} | {
    __kind__: "NewArticleByFollowedTag";
    NewArticleByFollowedTag: {
        bucketCanisterId: string;
        tagName: string;
        postWriterPrincipal: string;
        postTitle: string;
        postId: string;
    };
} | {
    __kind__: "AuthorGainsNewSubscriber";
    AuthorGainsNewSubscriber: {
        amountOfTokens: string;
        subscriptionEndTime: string;
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscriptionStartTime: string;
        subscriberPrincipalId: string;
    };
};
export type Result_2 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type Result = {
    __kind__: "ok";
    ok: UserNotificationSettings;
} | {
    __kind__: "err";
    err: string;
};
export interface Notification {
    id: string;
    content: NotificationContent;
    read: boolean;
    timestamp: string;
    notificationReceiverPrincipalId: string;
}
export interface Icrc28TrustedOriginsResponse {
    trusted_origins: Array<string>;
}
export interface GetUserNotificationsResponse {
    notifications: Array<Notification>;
    totalCount: string;
}
export interface SupportedStandard {
    url: string;
    name: string;
}
export type Result_1 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface UserNotificationSettings {
    premiumArticleSold: boolean;
    verifyProfile: boolean;
    tipReceived: boolean;
    authorGainsNewSubscriber: boolean;
    authorLosesSubscriber: boolean;
    youSubscribedToAuthor: boolean;
    newCommentOnMyArticle: boolean;
    replyToMyComment: boolean;
    youUnsubscribedFromAuthor: boolean;
    newFollower: boolean;
    readerExpiredSubscription: boolean;
    newArticleByFollowedWriter: boolean;
    newArticleByFollowedTag: boolean;
    faucetClaimAvailable: boolean;
}
export type NotificationContent = {
    __kind__: "FaucetClaimAvailable";
    FaucetClaimAvailable: null;
} | {
    __kind__: "TipReceived";
    TipReceived: {
        bucketCanisterId: string;
        amountOfTokens: string;
        tipSenderPrincipal: string;
        publicationPrincipalId?: string;
        postTitle: string;
        numberOfApplauds: string;
        tippedTokenSymbol: string;
        postId: string;
    };
} | {
    __kind__: "NewArticleByFollowedWriter";
    NewArticleByFollowedWriter: {
        bucketCanisterId: string;
        postWriterPrincipal: string;
        postTitle: string;
        postId: string;
    };
} | {
    __kind__: "AuthorLosesSubscriber";
    AuthorLosesSubscriber: {
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscriberPrincipalId: string;
    };
} | {
    __kind__: "YouSubscribedToAuthor";
    YouSubscribedToAuthor: {
        amountOfTokens: string;
        subscriptionEndTime: string;
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscribedWriterPrincipalId: string;
        subscriptionStartTime: string;
        isPublication: boolean;
    };
} | {
    __kind__: "NewCommentOnMyArticle";
    NewCommentOnMyArticle: {
        bucketCanisterId: string;
        commentId: string;
        isReply: boolean;
        commentContent: string;
        postTitle: string;
        commenterPrincipal: string;
        postId: string;
    };
} | {
    __kind__: "VerifyProfile";
    VerifyProfile: null;
} | {
    __kind__: "YouUnsubscribedFromAuthor";
    YouUnsubscribedFromAuthor: {
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscribedWriterPrincipalId: string;
        isPublication: boolean;
    };
} | {
    __kind__: "NewFollower";
    NewFollower: {
        followerPrincipalId: string;
    };
} | {
    __kind__: "ReaderExpiredSubscription";
    ReaderExpiredSubscription: {
        amountOfTokens: string;
        subscriptionEndTime: string;
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscribedWriterPrincipalId: string;
        subscriptionStartTime: string;
        isPublication: boolean;
    };
} | {
    __kind__: "ReplyToMyComment";
    ReplyToMyComment: {
        bucketCanisterId: string;
        postWriterPrincipal: string;
        myCommentId: string;
        myCommentContent: string;
        replyCommentContent: string;
        postTitle: string;
        replyCommenterPrincipal: string;
        replyCommentId: string;
        postId: string;
    };
} | {
    __kind__: "PremiumArticleSold";
    PremiumArticleSold: {
        bucketCanisterId: string;
        amountOfTokens: string;
        publicationPrincipalId?: string;
        purchasedTokenSymbol: string;
        purchaserPrincipal: string;
        postTitle: string;
        postId: string;
    };
} | {
    __kind__: "NewArticleByFollowedTag";
    NewArticleByFollowedTag: {
        bucketCanisterId: string;
        tagName: string;
        postWriterPrincipal: string;
        postTitle: string;
        postId: string;
    };
} | {
    __kind__: "AuthorGainsNewSubscriber";
    AuthorGainsNewSubscriber: {
        amountOfTokens: string;
        subscriptionEndTime: string;
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscriptionStartTime: string;
        subscriberPrincipalId: string;
    };
};
export enum SubscriptionTimeInterval {
    LifeTime = "LifeTime",
    Weekly = "Weekly",
    Monthly = "Monthly",
    Annually = "Annually"
}
export interface NotificationsInterface {
    acceptCycles(): Promise<void>;
    availableCycles(): Promise<bigint>;
    broadcastNotification(arg0: NotificationContent__1): Promise<Result_2>;
    createNotification(arg0: string, arg1: NotificationContent__1): Promise<void>;
    createNotifications(arg0: Array<[string, NotificationContent__1]>): Promise<void>;
    getCanisterVersion(): Promise<string>;
    getMaxMemorySize(): Promise<bigint>;
    getMemorySize(): Promise<bigint>;
    getUserNotificationSettings(): Promise<UserNotificationSettings>;
    getUserNotifications(arg0: string, arg1: string): Promise<GetUserNotificationsResponse>;
    icrc10_supported_standards(): Promise<Array<SupportedStandard>>;
    icrc28_trusted_origins(): Promise<Icrc28TrustedOriginsResponse>;
    isThereEnoughMemory(): Promise<boolean>;
    markNotificationsAsRead(arg0: Array<string>): Promise<void>;
    setMaxMemorySize(arg0: bigint): Promise<Result_1>;
    updateNotificationSettings(arg0: UserNotificationSettings): Promise<Result>;
}
import type { GetUserNotificationsResponse as _GetUserNotificationsResponse, Notification as _Notification, NotificationContent as _NotificationContent, NotificationContent__1 as _NotificationContent__1, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, SubscriptionTimeInterval as _SubscriptionTimeInterval, UserNotificationSettings as _UserNotificationSettings } from "./declarations/Notifications.did";
export class Notifications implements NotificationsInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async acceptCycles(): Promise<void> {
        const result = await this.actor.acceptCycles();
        return result;
    }
    async availableCycles(): Promise<bigint> {
        const result = await this.actor.availableCycles();
        return result;
    }
    async broadcastNotification(arg0: NotificationContent__1): Promise<Result_2> {
        const result = await this.actor.broadcastNotification(to_candid_NotificationContent__1_n1(arg0));
        return from_candid_Result_2_n11(result);
    }
    async createNotification(arg0: string, arg1: NotificationContent__1): Promise<void> {
        const result = await this.actor.createNotification(arg0, to_candid_NotificationContent__1_n1(arg1));
        return result;
    }
    async createNotifications(arg0: Array<[string, NotificationContent__1]>): Promise<void> {
        const result = await this.actor.createNotifications(to_candid_vec_n13(arg0));
        return result;
    }
    async getCanisterVersion(): Promise<string> {
        const result = await this.actor.getCanisterVersion();
        return result;
    }
    async getMaxMemorySize(): Promise<bigint> {
        const result = await this.actor.getMaxMemorySize();
        return result;
    }
    async getMemorySize(): Promise<bigint> {
        const result = await this.actor.getMemorySize();
        return result;
    }
    async getUserNotificationSettings(): Promise<UserNotificationSettings> {
        const result = await this.actor.getUserNotificationSettings();
        return result;
    }
    async getUserNotifications(arg0: string, arg1: string): Promise<GetUserNotificationsResponse> {
        const result = await this.actor.getUserNotifications(arg0, arg1);
        return from_candid_GetUserNotificationsResponse_n15(result);
    }
    async icrc10_supported_standards(): Promise<Array<SupportedStandard>> {
        const result = await this.actor.icrc10_supported_standards();
        return result;
    }
    async icrc28_trusted_origins(): Promise<Icrc28TrustedOriginsResponse> {
        const result = await this.actor.icrc28_trusted_origins();
        return result;
    }
    async isThereEnoughMemory(): Promise<boolean> {
        const result = await this.actor.isThereEnoughMemory();
        return result;
    }
    async markNotificationsAsRead(arg0: Array<string>): Promise<void> {
        const result = await this.actor.markNotificationsAsRead(arg0);
        return result;
    }
    async setMaxMemorySize(arg0: bigint): Promise<Result_1> {
        const result = await this.actor.setMaxMemorySize(arg0);
        return from_candid_Result_1_n31(result);
    }
    async updateNotificationSettings(arg0: UserNotificationSettings): Promise<Result> {
        const result = await this.actor.updateNotificationSettings(arg0);
        return from_candid_Result_n33(result);
    }
}
function from_candid_GetUserNotificationsResponse_n15(value: _GetUserNotificationsResponse): GetUserNotificationsResponse {
    return from_candid_record_n16(value);
}
function from_candid_NotificationContent_n20(value: _NotificationContent): NotificationContent {
    return from_candid_variant_n21(value);
}
function from_candid_Notification_n18(value: _Notification): Notification {
    return from_candid_record_n19(value);
}
function from_candid_Result_1_n31(value: _Result_1): Result_1 {
    return from_candid_variant_n32(value);
}
function from_candid_Result_2_n11(value: _Result_2): Result_2 {
    return from_candid_variant_n12(value);
}
function from_candid_Result_n33(value: _Result): Result {
    return from_candid_variant_n34(value);
}
function from_candid_SubscriptionTimeInterval_n25(value: _SubscriptionTimeInterval): SubscriptionTimeInterval {
    return from_candid_variant_n26(value);
}
function from_candid_opt_n23(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(value: {
    notifications: Array<_Notification>;
    totalCount: string;
}): {
    notifications: Array<Notification>;
    totalCount: string;
} {
    return {
        notifications: from_candid_vec_n17(value.notifications),
        totalCount: value.totalCount
    };
}
function from_candid_record_n19(value: {
    id: string;
    content: _NotificationContent;
    read: boolean;
    timestamp: string;
    notificationReceiverPrincipalId: string;
}): {
    id: string;
    content: NotificationContent;
    read: boolean;
    timestamp: string;
    notificationReceiverPrincipalId: string;
} {
    return {
        id: value.id,
        content: from_candid_NotificationContent_n20(value.content),
        read: value.read,
        timestamp: value.timestamp,
        notificationReceiverPrincipalId: value.notificationReceiverPrincipalId
    };
}
function from_candid_record_n22(value: {
    bucketCanisterId: string;
    amountOfTokens: string;
    tipSenderPrincipal: string;
    publicationPrincipalId: [] | [string];
    postTitle: string;
    numberOfApplauds: string;
    tippedTokenSymbol: string;
    postId: string;
}): {
    bucketCanisterId: string;
    amountOfTokens: string;
    tipSenderPrincipal: string;
    publicationPrincipalId?: string;
    postTitle: string;
    numberOfApplauds: string;
    tippedTokenSymbol: string;
    postId: string;
} {
    return {
        bucketCanisterId: value.bucketCanisterId,
        amountOfTokens: value.amountOfTokens,
        tipSenderPrincipal: value.tipSenderPrincipal,
        publicationPrincipalId: record_opt_to_undefined(from_candid_opt_n23(value.publicationPrincipalId)),
        postTitle: value.postTitle,
        numberOfApplauds: value.numberOfApplauds,
        tippedTokenSymbol: value.tippedTokenSymbol,
        postId: value.postId
    };
}
function from_candid_record_n24(value: {
    subscriptionTimeInterval: _SubscriptionTimeInterval;
    subscriberPrincipalId: string;
}): {
    subscriptionTimeInterval: SubscriptionTimeInterval;
    subscriberPrincipalId: string;
} {
    return {
        subscriptionTimeInterval: from_candid_SubscriptionTimeInterval_n25(value.subscriptionTimeInterval),
        subscriberPrincipalId: value.subscriberPrincipalId
    };
}
function from_candid_record_n27(value: {
    amountOfTokens: string;
    subscriptionEndTime: string;
    subscriptionTimeInterval: _SubscriptionTimeInterval;
    subscribedWriterPrincipalId: string;
    subscriptionStartTime: string;
    isPublication: boolean;
}): {
    amountOfTokens: string;
    subscriptionEndTime: string;
    subscriptionTimeInterval: SubscriptionTimeInterval;
    subscribedWriterPrincipalId: string;
    subscriptionStartTime: string;
    isPublication: boolean;
} {
    return {
        amountOfTokens: value.amountOfTokens,
        subscriptionEndTime: value.subscriptionEndTime,
        subscriptionTimeInterval: from_candid_SubscriptionTimeInterval_n25(value.subscriptionTimeInterval),
        subscribedWriterPrincipalId: value.subscribedWriterPrincipalId,
        subscriptionStartTime: value.subscriptionStartTime,
        isPublication: value.isPublication
    };
}
function from_candid_record_n28(value: {
    subscriptionTimeInterval: _SubscriptionTimeInterval;
    subscribedWriterPrincipalId: string;
    isPublication: boolean;
}): {
    subscriptionTimeInterval: SubscriptionTimeInterval;
    subscribedWriterPrincipalId: string;
    isPublication: boolean;
} {
    return {
        subscriptionTimeInterval: from_candid_SubscriptionTimeInterval_n25(value.subscriptionTimeInterval),
        subscribedWriterPrincipalId: value.subscribedWriterPrincipalId,
        isPublication: value.isPublication
    };
}
function from_candid_record_n29(value: {
    bucketCanisterId: string;
    amountOfTokens: string;
    publicationPrincipalId: [] | [string];
    purchasedTokenSymbol: string;
    purchaserPrincipal: string;
    postTitle: string;
    postId: string;
}): {
    bucketCanisterId: string;
    amountOfTokens: string;
    publicationPrincipalId?: string;
    purchasedTokenSymbol: string;
    purchaserPrincipal: string;
    postTitle: string;
    postId: string;
} {
    return {
        bucketCanisterId: value.bucketCanisterId,
        amountOfTokens: value.amountOfTokens,
        publicationPrincipalId: record_opt_to_undefined(from_candid_opt_n23(value.publicationPrincipalId)),
        purchasedTokenSymbol: value.purchasedTokenSymbol,
        purchaserPrincipal: value.purchaserPrincipal,
        postTitle: value.postTitle,
        postId: value.postId
    };
}
function from_candid_record_n30(value: {
    amountOfTokens: string;
    subscriptionEndTime: string;
    subscriptionTimeInterval: _SubscriptionTimeInterval;
    subscriptionStartTime: string;
    subscriberPrincipalId: string;
}): {
    amountOfTokens: string;
    subscriptionEndTime: string;
    subscriptionTimeInterval: SubscriptionTimeInterval;
    subscriptionStartTime: string;
    subscriberPrincipalId: string;
} {
    return {
        amountOfTokens: value.amountOfTokens,
        subscriptionEndTime: value.subscriptionEndTime,
        subscriptionTimeInterval: from_candid_SubscriptionTimeInterval_n25(value.subscriptionTimeInterval),
        subscriptionStartTime: value.subscriptionStartTime,
        subscriberPrincipalId: value.subscriberPrincipalId
    };
}
function from_candid_variant_n12(value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(value: {
    FaucetClaimAvailable: null;
} | {
    TipReceived: {
        bucketCanisterId: string;
        amountOfTokens: string;
        tipSenderPrincipal: string;
        publicationPrincipalId: [] | [string];
        postTitle: string;
        numberOfApplauds: string;
        tippedTokenSymbol: string;
        postId: string;
    };
} | {
    NewArticleByFollowedWriter: {
        bucketCanisterId: string;
        postWriterPrincipal: string;
        postTitle: string;
        postId: string;
    };
} | {
    AuthorLosesSubscriber: {
        subscriptionTimeInterval: _SubscriptionTimeInterval;
        subscriberPrincipalId: string;
    };
} | {
    YouSubscribedToAuthor: {
        amountOfTokens: string;
        subscriptionEndTime: string;
        subscriptionTimeInterval: _SubscriptionTimeInterval;
        subscribedWriterPrincipalId: string;
        subscriptionStartTime: string;
        isPublication: boolean;
    };
} | {
    NewCommentOnMyArticle: {
        bucketCanisterId: string;
        commentId: string;
        isReply: boolean;
        commentContent: string;
        postTitle: string;
        commenterPrincipal: string;
        postId: string;
    };
} | {
    VerifyProfile: null;
} | {
    YouUnsubscribedFromAuthor: {
        subscriptionTimeInterval: _SubscriptionTimeInterval;
        subscribedWriterPrincipalId: string;
        isPublication: boolean;
    };
} | {
    NewFollower: {
        followerPrincipalId: string;
    };
} | {
    ReaderExpiredSubscription: {
        amountOfTokens: string;
        subscriptionEndTime: string;
        subscriptionTimeInterval: _SubscriptionTimeInterval;
        subscribedWriterPrincipalId: string;
        subscriptionStartTime: string;
        isPublication: boolean;
    };
} | {
    ReplyToMyComment: {
        bucketCanisterId: string;
        postWriterPrincipal: string;
        myCommentId: string;
        myCommentContent: string;
        replyCommentContent: string;
        postTitle: string;
        replyCommenterPrincipal: string;
        replyCommentId: string;
        postId: string;
    };
} | {
    PremiumArticleSold: {
        bucketCanisterId: string;
        amountOfTokens: string;
        publicationPrincipalId: [] | [string];
        purchasedTokenSymbol: string;
        purchaserPrincipal: string;
        postTitle: string;
        postId: string;
    };
} | {
    NewArticleByFollowedTag: {
        bucketCanisterId: string;
        tagName: string;
        postWriterPrincipal: string;
        postTitle: string;
        postId: string;
    };
} | {
    AuthorGainsNewSubscriber: {
        amountOfTokens: string;
        subscriptionEndTime: string;
        subscriptionTimeInterval: _SubscriptionTimeInterval;
        subscriptionStartTime: string;
        subscriberPrincipalId: string;
    };
}): {
    __kind__: "FaucetClaimAvailable";
    FaucetClaimAvailable: null;
} | {
    __kind__: "TipReceived";
    TipReceived: {
        bucketCanisterId: string;
        amountOfTokens: string;
        tipSenderPrincipal: string;
        publicationPrincipalId?: string;
        postTitle: string;
        numberOfApplauds: string;
        tippedTokenSymbol: string;
        postId: string;
    };
} | {
    __kind__: "NewArticleByFollowedWriter";
    NewArticleByFollowedWriter: {
        bucketCanisterId: string;
        postWriterPrincipal: string;
        postTitle: string;
        postId: string;
    };
} | {
    __kind__: "AuthorLosesSubscriber";
    AuthorLosesSubscriber: {
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscriberPrincipalId: string;
    };
} | {
    __kind__: "YouSubscribedToAuthor";
    YouSubscribedToAuthor: {
        amountOfTokens: string;
        subscriptionEndTime: string;
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscribedWriterPrincipalId: string;
        subscriptionStartTime: string;
        isPublication: boolean;
    };
} | {
    __kind__: "NewCommentOnMyArticle";
    NewCommentOnMyArticle: {
        bucketCanisterId: string;
        commentId: string;
        isReply: boolean;
        commentContent: string;
        postTitle: string;
        commenterPrincipal: string;
        postId: string;
    };
} | {
    __kind__: "VerifyProfile";
    VerifyProfile: null;
} | {
    __kind__: "YouUnsubscribedFromAuthor";
    YouUnsubscribedFromAuthor: {
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscribedWriterPrincipalId: string;
        isPublication: boolean;
    };
} | {
    __kind__: "NewFollower";
    NewFollower: {
        followerPrincipalId: string;
    };
} | {
    __kind__: "ReaderExpiredSubscription";
    ReaderExpiredSubscription: {
        amountOfTokens: string;
        subscriptionEndTime: string;
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscribedWriterPrincipalId: string;
        subscriptionStartTime: string;
        isPublication: boolean;
    };
} | {
    __kind__: "ReplyToMyComment";
    ReplyToMyComment: {
        bucketCanisterId: string;
        postWriterPrincipal: string;
        myCommentId: string;
        myCommentContent: string;
        replyCommentContent: string;
        postTitle: string;
        replyCommenterPrincipal: string;
        replyCommentId: string;
        postId: string;
    };
} | {
    __kind__: "PremiumArticleSold";
    PremiumArticleSold: {
        bucketCanisterId: string;
        amountOfTokens: string;
        publicationPrincipalId?: string;
        purchasedTokenSymbol: string;
        purchaserPrincipal: string;
        postTitle: string;
        postId: string;
    };
} | {
    __kind__: "NewArticleByFollowedTag";
    NewArticleByFollowedTag: {
        bucketCanisterId: string;
        tagName: string;
        postWriterPrincipal: string;
        postTitle: string;
        postId: string;
    };
} | {
    __kind__: "AuthorGainsNewSubscriber";
    AuthorGainsNewSubscriber: {
        amountOfTokens: string;
        subscriptionEndTime: string;
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscriptionStartTime: string;
        subscriberPrincipalId: string;
    };
} {
    return "FaucetClaimAvailable" in value ? {
        __kind__: "FaucetClaimAvailable",
        FaucetClaimAvailable: value.FaucetClaimAvailable
    } : "TipReceived" in value ? {
        __kind__: "TipReceived",
        TipReceived: from_candid_record_n22(value.TipReceived)
    } : "NewArticleByFollowedWriter" in value ? {
        __kind__: "NewArticleByFollowedWriter",
        NewArticleByFollowedWriter: value.NewArticleByFollowedWriter
    } : "AuthorLosesSubscriber" in value ? {
        __kind__: "AuthorLosesSubscriber",
        AuthorLosesSubscriber: from_candid_record_n24(value.AuthorLosesSubscriber)
    } : "YouSubscribedToAuthor" in value ? {
        __kind__: "YouSubscribedToAuthor",
        YouSubscribedToAuthor: from_candid_record_n27(value.YouSubscribedToAuthor)
    } : "NewCommentOnMyArticle" in value ? {
        __kind__: "NewCommentOnMyArticle",
        NewCommentOnMyArticle: value.NewCommentOnMyArticle
    } : "VerifyProfile" in value ? {
        __kind__: "VerifyProfile",
        VerifyProfile: value.VerifyProfile
    } : "YouUnsubscribedFromAuthor" in value ? {
        __kind__: "YouUnsubscribedFromAuthor",
        YouUnsubscribedFromAuthor: from_candid_record_n28(value.YouUnsubscribedFromAuthor)
    } : "NewFollower" in value ? {
        __kind__: "NewFollower",
        NewFollower: value.NewFollower
    } : "ReaderExpiredSubscription" in value ? {
        __kind__: "ReaderExpiredSubscription",
        ReaderExpiredSubscription: from_candid_record_n27(value.ReaderExpiredSubscription)
    } : "ReplyToMyComment" in value ? {
        __kind__: "ReplyToMyComment",
        ReplyToMyComment: value.ReplyToMyComment
    } : "PremiumArticleSold" in value ? {
        __kind__: "PremiumArticleSold",
        PremiumArticleSold: from_candid_record_n29(value.PremiumArticleSold)
    } : "NewArticleByFollowedTag" in value ? {
        __kind__: "NewArticleByFollowedTag",
        NewArticleByFollowedTag: value.NewArticleByFollowedTag
    } : "AuthorGainsNewSubscriber" in value ? {
        __kind__: "AuthorGainsNewSubscriber",
        AuthorGainsNewSubscriber: from_candid_record_n30(value.AuthorGainsNewSubscriber)
    } : value;
}
function from_candid_variant_n26(value: {
    LifeTime: null;
} | {
    Weekly: null;
} | {
    Monthly: null;
} | {
    Annually: null;
}): SubscriptionTimeInterval {
    return "LifeTime" in value ? SubscriptionTimeInterval.LifeTime : "Weekly" in value ? SubscriptionTimeInterval.Weekly : "Monthly" in value ? SubscriptionTimeInterval.Monthly : "Annually" in value ? SubscriptionTimeInterval.Annually : value;
}
function from_candid_variant_n32(value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n34(value: {
    ok: _UserNotificationSettings;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserNotificationSettings;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n17(value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n18(x));
}
function to_candid_NotificationContent__1_n1(value: NotificationContent__1): _NotificationContent__1 {
    return to_candid_variant_n2(value);
}
function to_candid_SubscriptionTimeInterval_n4(value: SubscriptionTimeInterval): _SubscriptionTimeInterval {
    return to_candid_variant_n5(value);
}
function to_candid_record_n10(value: {
    bucketCanisterId: string;
    amountOfTokens: string;
    tipSenderPrincipal: string;
    publicationPrincipalId?: string;
    postTitle: string;
    numberOfApplauds: string;
    tippedTokenSymbol: string;
    postId: string;
}): {
    bucketCanisterId: string;
    amountOfTokens: string;
    tipSenderPrincipal: string;
    publicationPrincipalId: [] | [string];
    postTitle: string;
    numberOfApplauds: string;
    tippedTokenSymbol: string;
    postId: string;
} {
    return {
        bucketCanisterId: value.bucketCanisterId,
        amountOfTokens: value.amountOfTokens,
        tipSenderPrincipal: value.tipSenderPrincipal,
        publicationPrincipalId: value.publicationPrincipalId ? candid_some(value.publicationPrincipalId) : candid_none(),
        postTitle: value.postTitle,
        numberOfApplauds: value.numberOfApplauds,
        tippedTokenSymbol: value.tippedTokenSymbol,
        postId: value.postId
    };
}
function to_candid_record_n3(value: {
    amountOfTokens: string;
    subscriptionEndTime: string;
    subscriptionTimeInterval: SubscriptionTimeInterval;
    subscriptionStartTime: string;
    subscriberPrincipalId: string;
}): {
    amountOfTokens: string;
    subscriptionEndTime: string;
    subscriptionTimeInterval: _SubscriptionTimeInterval;
    subscriptionStartTime: string;
    subscriberPrincipalId: string;
} {
    return {
        amountOfTokens: value.amountOfTokens,
        subscriptionEndTime: value.subscriptionEndTime,
        subscriptionTimeInterval: to_candid_SubscriptionTimeInterval_n4(value.subscriptionTimeInterval),
        subscriptionStartTime: value.subscriptionStartTime,
        subscriberPrincipalId: value.subscriberPrincipalId
    };
}
function to_candid_record_n6(value: {
    bucketCanisterId: string;
    amountOfTokens: string;
    publicationPrincipalId?: string;
    purchasedTokenSymbol: string;
    purchaserPrincipal: string;
    postTitle: string;
    postId: string;
}): {
    bucketCanisterId: string;
    amountOfTokens: string;
    publicationPrincipalId: [] | [string];
    purchasedTokenSymbol: string;
    purchaserPrincipal: string;
    postTitle: string;
    postId: string;
} {
    return {
        bucketCanisterId: value.bucketCanisterId,
        amountOfTokens: value.amountOfTokens,
        publicationPrincipalId: value.publicationPrincipalId ? candid_some(value.publicationPrincipalId) : candid_none(),
        purchasedTokenSymbol: value.purchasedTokenSymbol,
        purchaserPrincipal: value.purchaserPrincipal,
        postTitle: value.postTitle,
        postId: value.postId
    };
}
function to_candid_record_n7(value: {
    amountOfTokens: string;
    subscriptionEndTime: string;
    subscriptionTimeInterval: SubscriptionTimeInterval;
    subscribedWriterPrincipalId: string;
    subscriptionStartTime: string;
    isPublication: boolean;
}): {
    amountOfTokens: string;
    subscriptionEndTime: string;
    subscriptionTimeInterval: _SubscriptionTimeInterval;
    subscribedWriterPrincipalId: string;
    subscriptionStartTime: string;
    isPublication: boolean;
} {
    return {
        amountOfTokens: value.amountOfTokens,
        subscriptionEndTime: value.subscriptionEndTime,
        subscriptionTimeInterval: to_candid_SubscriptionTimeInterval_n4(value.subscriptionTimeInterval),
        subscribedWriterPrincipalId: value.subscribedWriterPrincipalId,
        subscriptionStartTime: value.subscriptionStartTime,
        isPublication: value.isPublication
    };
}
function to_candid_record_n8(value: {
    subscriptionTimeInterval: SubscriptionTimeInterval;
    subscribedWriterPrincipalId: string;
    isPublication: boolean;
}): {
    subscriptionTimeInterval: _SubscriptionTimeInterval;
    subscribedWriterPrincipalId: string;
    isPublication: boolean;
} {
    return {
        subscriptionTimeInterval: to_candid_SubscriptionTimeInterval_n4(value.subscriptionTimeInterval),
        subscribedWriterPrincipalId: value.subscribedWriterPrincipalId,
        isPublication: value.isPublication
    };
}
function to_candid_record_n9(value: {
    subscriptionTimeInterval: SubscriptionTimeInterval;
    subscriberPrincipalId: string;
}): {
    subscriptionTimeInterval: _SubscriptionTimeInterval;
    subscriberPrincipalId: string;
} {
    return {
        subscriptionTimeInterval: to_candid_SubscriptionTimeInterval_n4(value.subscriptionTimeInterval),
        subscriberPrincipalId: value.subscriberPrincipalId
    };
}
function to_candid_tuple_n14(value: [string, NotificationContent__1]): [string, _NotificationContent__1] {
    return [
        value[0],
        to_candid_NotificationContent__1_n1(value[1])
    ];
}
function to_candid_variant_n2(value: {
    __kind__: "FaucetClaimAvailable";
    FaucetClaimAvailable: null;
} | {
    __kind__: "TipReceived";
    TipReceived: {
        bucketCanisterId: string;
        amountOfTokens: string;
        tipSenderPrincipal: string;
        publicationPrincipalId?: string;
        postTitle: string;
        numberOfApplauds: string;
        tippedTokenSymbol: string;
        postId: string;
    };
} | {
    __kind__: "NewArticleByFollowedWriter";
    NewArticleByFollowedWriter: {
        bucketCanisterId: string;
        postWriterPrincipal: string;
        postTitle: string;
        postId: string;
    };
} | {
    __kind__: "AuthorLosesSubscriber";
    AuthorLosesSubscriber: {
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscriberPrincipalId: string;
    };
} | {
    __kind__: "YouSubscribedToAuthor";
    YouSubscribedToAuthor: {
        amountOfTokens: string;
        subscriptionEndTime: string;
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscribedWriterPrincipalId: string;
        subscriptionStartTime: string;
        isPublication: boolean;
    };
} | {
    __kind__: "NewCommentOnMyArticle";
    NewCommentOnMyArticle: {
        bucketCanisterId: string;
        commentId: string;
        isReply: boolean;
        commentContent: string;
        postTitle: string;
        commenterPrincipal: string;
        postId: string;
    };
} | {
    __kind__: "VerifyProfile";
    VerifyProfile: null;
} | {
    __kind__: "YouUnsubscribedFromAuthor";
    YouUnsubscribedFromAuthor: {
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscribedWriterPrincipalId: string;
        isPublication: boolean;
    };
} | {
    __kind__: "NewFollower";
    NewFollower: {
        followerPrincipalId: string;
    };
} | {
    __kind__: "ReaderExpiredSubscription";
    ReaderExpiredSubscription: {
        amountOfTokens: string;
        subscriptionEndTime: string;
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscribedWriterPrincipalId: string;
        subscriptionStartTime: string;
        isPublication: boolean;
    };
} | {
    __kind__: "ReplyToMyComment";
    ReplyToMyComment: {
        bucketCanisterId: string;
        postWriterPrincipal: string;
        myCommentId: string;
        myCommentContent: string;
        replyCommentContent: string;
        postTitle: string;
        replyCommenterPrincipal: string;
        replyCommentId: string;
        postId: string;
    };
} | {
    __kind__: "PremiumArticleSold";
    PremiumArticleSold: {
        bucketCanisterId: string;
        amountOfTokens: string;
        publicationPrincipalId?: string;
        purchasedTokenSymbol: string;
        purchaserPrincipal: string;
        postTitle: string;
        postId: string;
    };
} | {
    __kind__: "NewArticleByFollowedTag";
    NewArticleByFollowedTag: {
        bucketCanisterId: string;
        tagName: string;
        postWriterPrincipal: string;
        postTitle: string;
        postId: string;
    };
} | {
    __kind__: "AuthorGainsNewSubscriber";
    AuthorGainsNewSubscriber: {
        amountOfTokens: string;
        subscriptionEndTime: string;
        subscriptionTimeInterval: SubscriptionTimeInterval;
        subscriptionStartTime: string;
        subscriberPrincipalId: string;
    };
}): {
    FaucetClaimAvailable: null;
} | {
    TipReceived: {
        bucketCanisterId: string;
        amountOfTokens: string;
        tipSenderPrincipal: string;
        publicationPrincipalId: [] | [string];
        postTitle: string;
        numberOfApplauds: string;
        tippedTokenSymbol: string;
        postId: string;
    };
} | {
    NewArticleByFollowedWriter: {
        bucketCanisterId: string;
        postWriterPrincipal: string;
        postTitle: string;
        postId: string;
    };
} | {
    AuthorLosesSubscriber: {
        subscriptionTimeInterval: _SubscriptionTimeInterval;
        subscriberPrincipalId: string;
    };
} | {
    YouSubscribedToAuthor: {
        amountOfTokens: string;
        subscriptionEndTime: string;
        subscriptionTimeInterval: _SubscriptionTimeInterval;
        subscribedWriterPrincipalId: string;
        subscriptionStartTime: string;
        isPublication: boolean;
    };
} | {
    NewCommentOnMyArticle: {
        bucketCanisterId: string;
        commentId: string;
        isReply: boolean;
        commentContent: string;
        postTitle: string;
        commenterPrincipal: string;
        postId: string;
    };
} | {
    VerifyProfile: null;
} | {
    YouUnsubscribedFromAuthor: {
        subscriptionTimeInterval: _SubscriptionTimeInterval;
        subscribedWriterPrincipalId: string;
        isPublication: boolean;
    };
} | {
    NewFollower: {
        followerPrincipalId: string;
    };
} | {
    ReaderExpiredSubscription: {
        amountOfTokens: string;
        subscriptionEndTime: string;
        subscriptionTimeInterval: _SubscriptionTimeInterval;
        subscribedWriterPrincipalId: string;
        subscriptionStartTime: string;
        isPublication: boolean;
    };
} | {
    ReplyToMyComment: {
        bucketCanisterId: string;
        postWriterPrincipal: string;
        myCommentId: string;
        myCommentContent: string;
        replyCommentContent: string;
        postTitle: string;
        replyCommenterPrincipal: string;
        replyCommentId: string;
        postId: string;
    };
} | {
    PremiumArticleSold: {
        bucketCanisterId: string;
        amountOfTokens: string;
        publicationPrincipalId: [] | [string];
        purchasedTokenSymbol: string;
        purchaserPrincipal: string;
        postTitle: string;
        postId: string;
    };
} | {
    NewArticleByFollowedTag: {
        bucketCanisterId: string;
        tagName: string;
        postWriterPrincipal: string;
        postTitle: string;
        postId: string;
    };
} | {
    AuthorGainsNewSubscriber: {
        amountOfTokens: string;
        subscriptionEndTime: string;
        subscriptionTimeInterval: _SubscriptionTimeInterval;
        subscriptionStartTime: string;
        subscriberPrincipalId: string;
    };
} {
    return value.__kind__ === "FaucetClaimAvailable" ? {
        FaucetClaimAvailable: value.FaucetClaimAvailable
    } : value.__kind__ === "TipReceived" ? {
        TipReceived: to_candid_record_n10(value.TipReceived)
    } : value.__kind__ === "NewArticleByFollowedWriter" ? {
        NewArticleByFollowedWriter: value.NewArticleByFollowedWriter
    } : value.__kind__ === "AuthorLosesSubscriber" ? {
        AuthorLosesSubscriber: to_candid_record_n9(value.AuthorLosesSubscriber)
    } : value.__kind__ === "YouSubscribedToAuthor" ? {
        YouSubscribedToAuthor: to_candid_record_n7(value.YouSubscribedToAuthor)
    } : value.__kind__ === "NewCommentOnMyArticle" ? {
        NewCommentOnMyArticle: value.NewCommentOnMyArticle
    } : value.__kind__ === "VerifyProfile" ? {
        VerifyProfile: value.VerifyProfile
    } : value.__kind__ === "YouUnsubscribedFromAuthor" ? {
        YouUnsubscribedFromAuthor: to_candid_record_n8(value.YouUnsubscribedFromAuthor)
    } : value.__kind__ === "NewFollower" ? {
        NewFollower: value.NewFollower
    } : value.__kind__ === "ReaderExpiredSubscription" ? {
        ReaderExpiredSubscription: to_candid_record_n7(value.ReaderExpiredSubscription)
    } : value.__kind__ === "ReplyToMyComment" ? {
        ReplyToMyComment: value.ReplyToMyComment
    } : value.__kind__ === "PremiumArticleSold" ? {
        PremiumArticleSold: to_candid_record_n6(value.PremiumArticleSold)
    } : value.__kind__ === "NewArticleByFollowedTag" ? {
        NewArticleByFollowedTag: value.NewArticleByFollowedTag
    } : value.__kind__ === "AuthorGainsNewSubscriber" ? {
        AuthorGainsNewSubscriber: to_candid_record_n3(value.AuthorGainsNewSubscriber)
    } : value;
}
function to_candid_variant_n5(value: SubscriptionTimeInterval): {
    LifeTime: null;
} | {
    Weekly: null;
} | {
    Monthly: null;
} | {
    Annually: null;
} {
    return value == SubscriptionTimeInterval.LifeTime ? {
        LifeTime: null
    } : value == SubscriptionTimeInterval.Weekly ? {
        Weekly: null
    } : value == SubscriptionTimeInterval.Monthly ? {
        Monthly: null
    } : value == SubscriptionTimeInterval.Annually ? {
        Annually: null
    } : value;
}
function to_candid_vec_n13(value: Array<[string, NotificationContent__1]>): Array<[string, _NotificationContent__1]> {
    return value.map((x)=>to_candid_tuple_n14(x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Notifications {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Notifications(actor);
}
