/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/Sonic.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export type Error_ = {
    __kind__: "CommonError";
    CommonError: null;
} | {
    __kind__: "InternalError";
    InternalError: string;
} | {
    __kind__: "UnsupportedToken";
    UnsupportedToken: string;
} | {
    __kind__: "InsufficientFunds";
    InsufficientFunds: null;
};
export type Result = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: Error_;
};
export interface SwapArgs {
    amountIn: string;
    zeroForOne: boolean;
    amountOutMinimum: string;
}
export interface SonicInterface {
    quote(arg0: SwapArgs): Promise<Result>;
}
import type { Error as _Error, Result as _Result } from "./declarations/Sonic.did";
export class Sonic implements SonicInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async quote(arg0: SwapArgs): Promise<Result> {
        const result = await this.actor.quote(arg0);
        return from_candid_Result_n1(result);
    }
}
function from_candid_Error_n3(value: _Error): Error_ {
    return from_candid_variant_n4(value);
}
function from_candid_Result_n1(value: _Result): Result {
    return from_candid_variant_n2(value);
}
function from_candid_variant_n2(value: {
    ok: bigint;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(value.err)
    } : value;
}
function from_candid_variant_n4(value: {
    CommonError: null;
} | {
    InternalError: string;
} | {
    UnsupportedToken: string;
} | {
    InsufficientFunds: null;
}): {
    __kind__: "CommonError";
    CommonError: null;
} | {
    __kind__: "InternalError";
    InternalError: string;
} | {
    __kind__: "UnsupportedToken";
    UnsupportedToken: string;
} | {
    __kind__: "InsufficientFunds";
    InsufficientFunds: null;
} {
    return "CommonError" in value ? {
        __kind__: "CommonError",
        CommonError: value.CommonError
    } : "InternalError" in value ? {
        __kind__: "InternalError",
        InternalError: value.InternalError
    } : "UnsupportedToken" in value ? {
        __kind__: "UnsupportedToken",
        UnsupportedToken: value.UnsupportedToken
    } : "InsufficientFunds" in value ? {
        __kind__: "InsufficientFunds",
        InsufficientFunds: value.InsufficientFunds
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Sonic {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Sonic(actor);
}
