/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/Storage.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export type Result_2 = {
    __kind__: "ok";
    ok: Uint8Array;
} | {
    __kind__: "err";
    err: string;
};
export type CanisterCyclesAggregatedData = BigUint64Array;
export interface Icrc28TrustedOriginsResponse {
    trusted_origins: Array<string>;
}
export interface DailyMetricsData {
    updateCalls: bigint;
    canisterHeapMemorySize: NumericEntity;
    canisterCycles: NumericEntity;
    canisterMemorySize: NumericEntity;
    timeMillis: bigint;
}
export interface Content {
    contentId: string;
    contentSize: bigint;
    mimeType: string;
    offset: bigint;
    totalChunks: bigint;
    chunkData: Uint8Array;
}
export interface GetMetricsParameters {
    dateToMillis: bigint;
    granularity: MetricsGranularity;
    dateFromMillis: bigint;
}
export type CanisterMemoryAggregatedData = BigUint64Array;
export interface SupportedStandard {
    url: string;
    name: string;
}
export type Validate = {
    __kind__: "Ok";
    Ok: string;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type Result_4 = {
    __kind__: "ok";
    ok: [Array<Principal>, Array<string>];
} | {
    __kind__: "err";
    err: string;
};
export interface CanisterMetrics {
    data: CanisterMetricsData;
}
export type CanisterHeapMemoryAggregatedData = BigUint64Array;
export type Result = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: Array<string>;
} | {
    __kind__: "err";
    err: string;
};
export interface StorageInterface {
    acceptCycles(): Promise<void>;
    addStorageBucket(arg0: string): Promise<Result_1>;
    addWasmChunk(arg0: Uint8Array): Promise<Result_1>;
    availableCycles(): Promise<bigint>;
    collectCanisterMetrics(): Promise<void>;
    getAdmins(): Promise<Result_3>;
    getAllDataCanisterIds(): Promise<Result_4>;
    getCanisterMetrics(arg0: GetMetricsParameters): Promise<CanisterMetrics | null>;
    getCanisterVersion(): Promise<string>;
    getCgUsers(): Promise<Result_3>;
    getNewContentId(): Promise<Result>;
    getPlatformOperators(): Promise<List>;
    getWasmChunks(): Promise<Result_2>;
    icrc10_supported_standards(): Promise<Array<SupportedStandard>>;
    icrc28_trusted_origins(): Promise<Icrc28TrustedOriginsResponse>;
    idQuick(): Promise<Principal>;
    registerAdmin(arg0: string): Promise<Result_1>;
    registerCgUser(arg0: string): Promise<Result_1>;
    registerPlatformOperator(arg0: string): Promise<Result_1>;
    resetWasmChunks(): Promise<void>;
    retiredDataCanisterIdForWriting(arg0: string): Promise<Result_1>;
    unregisterAdmin(arg0: string): Promise<Result_1>;
    unregisterCgUser(arg0: string): Promise<Result_1>;
    unregisterPlatformOperator(arg0: string): Promise<Result_1>;
    upgradeAllBuckets(arg0: string, arg1: Uint8Array): Promise<Result_1>;
    upgradeBucket(arg0: string, arg1: Uint8Array): Promise<Result_1>;
    uploadBlob(arg0: Content): Promise<Result>;
    validate(arg0: any): Promise<Validate>;
}
export interface NumericEntity {
    avg: bigint;
    max: bigint;
    min: bigint;
    first: bigint;
    last: bigint;
}
export type List = [string, List] | null;
export interface HourlyMetricsData {
    updateCalls: UpdateCallsAggregatedData;
    canisterHeapMemorySize: CanisterHeapMemoryAggregatedData;
    canisterCycles: CanisterCyclesAggregatedData;
    canisterMemorySize: CanisterMemoryAggregatedData;
    timeMillis: bigint;
}
export type CanisterMetricsData = {
    __kind__: "hourly";
    hourly: Array<HourlyMetricsData>;
} | {
    __kind__: "daily";
    daily: Array<DailyMetricsData>;
};
export type UpdateCallsAggregatedData = BigUint64Array;
export enum MetricsGranularity {
    hourly = "hourly",
    daily = "daily"
}
export interface StorageInterface extends StorageInterface {
}
import type { CanisterMetrics as _CanisterMetrics, CanisterMetricsData as _CanisterMetricsData, DailyMetricsData as _DailyMetricsData, GetMetricsParameters as _GetMetricsParameters, HourlyMetricsData as _HourlyMetricsData, List as _List, MetricsGranularity as _MetricsGranularity, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Validate as _Validate } from "./declarations/Storage.did";
export class Storage implements StorageInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async acceptCycles(): Promise<void> {
        const result = await this.actor.acceptCycles();
        return result;
    }
    async addStorageBucket(arg0: string): Promise<Result_1> {
        const result = await this.actor.addStorageBucket(arg0);
        return from_candid_Result_1_n1(result);
    }
    async addWasmChunk(arg0: Uint8Array): Promise<Result_1> {
        const result = await this.actor.addWasmChunk(arg0);
        return from_candid_Result_1_n1(result);
    }
    async availableCycles(): Promise<bigint> {
        const result = await this.actor.availableCycles();
        return result;
    }
    async collectCanisterMetrics(): Promise<void> {
        const result = await this.actor.collectCanisterMetrics();
        return result;
    }
    async getAdmins(): Promise<Result_3> {
        const result = await this.actor.getAdmins();
        return from_candid_Result_3_n3(result);
    }
    async getAllDataCanisterIds(): Promise<Result_4> {
        const result = await this.actor.getAllDataCanisterIds();
        return from_candid_Result_4_n5(result);
    }
    async getCanisterMetrics(arg0: GetMetricsParameters): Promise<CanisterMetrics | null> {
        const result = await this.actor.getCanisterMetrics(to_candid_GetMetricsParameters_n7(arg0));
        return from_candid_opt_n11(result);
    }
    async getCanisterVersion(): Promise<string> {
        const result = await this.actor.getCanisterVersion();
        return result;
    }
    async getCgUsers(): Promise<Result_3> {
        const result = await this.actor.getCgUsers();
        return from_candid_Result_3_n3(result);
    }
    async getNewContentId(): Promise<Result> {
        const result = await this.actor.getNewContentId();
        return from_candid_Result_n16(result);
    }
    async getPlatformOperators(): Promise<List> {
        const result = await this.actor.getPlatformOperators();
        return from_candid_List_n18(result);
    }
    async getWasmChunks(): Promise<Result_2> {
        const result = await this.actor.getWasmChunks();
        return from_candid_Result_2_n21(result);
    }
    async icrc10_supported_standards(): Promise<Array<SupportedStandard>> {
        const result = await this.actor.icrc10_supported_standards();
        return result;
    }
    async icrc28_trusted_origins(): Promise<Icrc28TrustedOriginsResponse> {
        const result = await this.actor.icrc28_trusted_origins();
        return result;
    }
    async idQuick(): Promise<Principal> {
        const result = await this.actor.idQuick();
        return result;
    }
    async registerAdmin(arg0: string): Promise<Result_1> {
        const result = await this.actor.registerAdmin(arg0);
        return from_candid_Result_1_n1(result);
    }
    async registerCgUser(arg0: string): Promise<Result_1> {
        const result = await this.actor.registerCgUser(arg0);
        return from_candid_Result_1_n1(result);
    }
    async registerPlatformOperator(arg0: string): Promise<Result_1> {
        const result = await this.actor.registerPlatformOperator(arg0);
        return from_candid_Result_1_n1(result);
    }
    async resetWasmChunks(): Promise<void> {
        const result = await this.actor.resetWasmChunks();
        return result;
    }
    async retiredDataCanisterIdForWriting(arg0: string): Promise<Result_1> {
        const result = await this.actor.retiredDataCanisterIdForWriting(arg0);
        return from_candid_Result_1_n1(result);
    }
    async unregisterAdmin(arg0: string): Promise<Result_1> {
        const result = await this.actor.unregisterAdmin(arg0);
        return from_candid_Result_1_n1(result);
    }
    async unregisterCgUser(arg0: string): Promise<Result_1> {
        const result = await this.actor.unregisterCgUser(arg0);
        return from_candid_Result_1_n1(result);
    }
    async unregisterPlatformOperator(arg0: string): Promise<Result_1> {
        const result = await this.actor.unregisterPlatformOperator(arg0);
        return from_candid_Result_1_n1(result);
    }
    async upgradeAllBuckets(arg0: string, arg1: Uint8Array): Promise<Result_1> {
        const result = await this.actor.upgradeAllBuckets(arg0, arg1);
        return from_candid_Result_1_n1(result);
    }
    async upgradeBucket(arg0: string, arg1: Uint8Array): Promise<Result_1> {
        const result = await this.actor.upgradeBucket(arg0, arg1);
        return from_candid_Result_1_n1(result);
    }
    async uploadBlob(arg0: Content): Promise<Result> {
        const result = await this.actor.uploadBlob(arg0);
        return from_candid_Result_n16(result);
    }
    async validate(arg0: any): Promise<Validate> {
        const result = await this.actor.validate(arg0);
        return from_candid_Validate_n23(result);
    }
}
function from_candid_CanisterMetricsData_n14(value: _CanisterMetricsData): CanisterMetricsData {
    return from_candid_variant_n15(value);
}
function from_candid_CanisterMetrics_n12(value: _CanisterMetrics): CanisterMetrics {
    return from_candid_record_n13(value);
}
function from_candid_List_n18(value: _List): List {
    return from_candid_opt_n19(value);
}
function from_candid_Result_1_n1(value: _Result_1): Result_1 {
    return from_candid_variant_n2(value);
}
function from_candid_Result_2_n21(value: _Result_2): Result_2 {
    return from_candid_variant_n22(value);
}
function from_candid_Result_3_n3(value: _Result_3): Result_3 {
    return from_candid_variant_n4(value);
}
function from_candid_Result_4_n5(value: _Result_4): Result_4 {
    return from_candid_variant_n6(value);
}
function from_candid_Result_n16(value: _Result): Result {
    return from_candid_variant_n17(value);
}
function from_candid_Validate_n23(value: _Validate): Validate {
    return from_candid_variant_n24(value);
}
function from_candid_opt_n11(value: [] | [_CanisterMetrics]): CanisterMetrics | null {
    return value.length === 0 ? null : from_candid_CanisterMetrics_n12(value[0]);
}
function from_candid_opt_n19(value: [] | [[string, _List]]): [string, List] | null {
    return value.length === 0 ? null : from_candid_tuple_n20(value[0]);
}
function from_candid_record_n13(value: {
    data: _CanisterMetricsData;
}): {
    data: CanisterMetricsData;
} {
    return {
        data: from_candid_CanisterMetricsData_n14(value.data)
    };
}
function from_candid_tuple_n20(value: [string, _List]): [string, List] {
    return [
        value[0],
        from_candid_List_n18(value[1])
    ];
}
function from_candid_variant_n15(value: {
    hourly: Array<_HourlyMetricsData>;
} | {
    daily: Array<_DailyMetricsData>;
}): {
    __kind__: "hourly";
    hourly: Array<HourlyMetricsData>;
} | {
    __kind__: "daily";
    daily: Array<DailyMetricsData>;
} {
    return "hourly" in value ? {
        __kind__: "hourly",
        hourly: value.hourly
    } : "daily" in value ? {
        __kind__: "daily",
        daily: value.daily
    } : value;
}
function from_candid_variant_n17(value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(value: {
    ok: Uint8Array;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Uint8Array;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(value: {
    Ok: string;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: string;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n4(value: {
    ok: Array<string>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<string>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(value: {
    ok: [Array<Principal>, Array<string>];
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: [Array<Principal>, Array<string>];
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function to_candid_GetMetricsParameters_n7(value: GetMetricsParameters): _GetMetricsParameters {
    return to_candid_record_n8(value);
}
function to_candid_MetricsGranularity_n9(value: MetricsGranularity): _MetricsGranularity {
    return to_candid_variant_n10(value);
}
function to_candid_record_n8(value: {
    dateToMillis: bigint;
    granularity: MetricsGranularity;
    dateFromMillis: bigint;
}): {
    dateToMillis: bigint;
    granularity: _MetricsGranularity;
    dateFromMillis: bigint;
} {
    return {
        dateToMillis: value.dateToMillis,
        granularity: to_candid_MetricsGranularity_n9(value.granularity),
        dateFromMillis: value.dateFromMillis
    };
}
function to_candid_variant_n10(value: MetricsGranularity): {
    hourly: null;
} | {
    daily: null;
} {
    return value == MetricsGranularity.hourly ? {
        hourly: null
    } : value == MetricsGranularity.daily ? {
        daily: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Storage {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Storage(actor);
}
