/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/Icrc1.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface Account {
    owner: Principal;
    subaccount?: Uint8Array;
}
export interface GetTransactionsResponse {
    first_index: bigint;
    log_length: bigint;
    transactions: Array<Transaction>;
    archived_transactions: Array<ArchivedRange_1>;
}
export interface GetBlocksResponse {
    certificate?: Uint8Array;
    first_index: bigint;
    blocks: Array<Value>;
    chain_length: bigint;
    archived_blocks: Array<ArchivedRange>;
}
export interface Mint {
    to: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
}
export interface ArchiveOptions {
    num_blocks_to_archive: bigint;
    max_transactions_per_response?: bigint;
    trigger_threshold: bigint;
    max_message_size_bytes?: bigint;
    cycles_for_archive_creation?: bigint;
    node_max_memory_size_bytes?: bigint;
    controller_id: Principal;
}
export type Result_2 = {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: TransferFromError;
};
export interface GetBlocksRequest {
    start: bigint;
    length: bigint;
}
export interface ApproveArgs {
    fee?: bigint;
    memo?: Uint8Array;
    from_subaccount?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
    expected_allowance?: bigint;
    expires_at?: bigint;
    spender: Account;
}
export interface ArchivedRange_1 {
    callback: [Principal, string];
    start: bigint;
    length: bigint;
}
export interface FeatureFlags {
    icrc2: boolean;
}
export interface Burn {
    from: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
    spender?: Account;
}
export interface DataCertificate {
    certificate?: Uint8Array;
    hash_tree: Uint8Array;
}
export type Result_1 = {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: ApproveError;
};
export type LedgerArgument = {
    __kind__: "Upgrade";
    Upgrade: UpgradeArgs | null;
} | {
    __kind__: "Init";
    Init: InitArgs;
};
export interface Transaction {
    burn?: Burn;
    kind: string;
    mint?: Mint;
    approve?: Approve;
    timestamp: bigint;
    transfer?: Transfer;
}
export interface Transfer {
    to: Account;
    fee?: bigint;
    from: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
    spender?: Account;
}
export type ChangeFeeCollector = {
    __kind__: "SetTo";
    SetTo: Account;
} | {
    __kind__: "Unset";
    Unset: null;
};
export interface StandardRecord {
    url: string;
    name: string;
}
export interface Allowance {
    allowance: bigint;
    expires_at?: bigint;
}
export interface TransferFromArgs {
    to: Account;
    fee?: bigint;
    spender_subaccount?: Uint8Array;
    from: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
}
export type Vec = Array<{
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Array<[string, Value]>;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Nat64";
    Nat64: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Array";
    Array: Vec;
}>;
export type Value = {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Array<[string, Value]>;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Nat64";
    Nat64: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Array";
    Array: Vec;
};
export interface BlockRange {
    blocks: Array<Value>;
}
export type TransferFromError = {
    __kind__: "GenericError";
    GenericError: {
        message: string;
        error_code: bigint;
    };
} | {
    __kind__: "TemporarilyUnavailable";
    TemporarilyUnavailable: null;
} | {
    __kind__: "InsufficientAllowance";
    InsufficientAllowance: {
        allowance: bigint;
    };
} | {
    __kind__: "BadBurn";
    BadBurn: {
        min_burn_amount: bigint;
    };
} | {
    __kind__: "Duplicate";
    Duplicate: {
        duplicate_of: bigint;
    };
} | {
    __kind__: "BadFee";
    BadFee: {
        expected_fee: bigint;
    };
} | {
    __kind__: "CreatedInFuture";
    CreatedInFuture: {
        ledger_time: bigint;
    };
} | {
    __kind__: "TooOld";
    TooOld: null;
} | {
    __kind__: "InsufficientFunds";
    InsufficientFunds: {
        balance: bigint;
    };
};
export interface TransactionRange {
    transactions: Array<Transaction>;
}
export interface AllowanceArgs {
    account: Account;
    spender: Account;
}
export interface Approve {
    fee?: bigint;
    from: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
    expected_allowance?: bigint;
    expires_at?: bigint;
    spender: Account;
}
export type MetadataValue = {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Text";
    Text: string;
};
export interface TransferArg {
    to: Account;
    fee?: bigint;
    memo?: Uint8Array;
    from_subaccount?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
}
export type ApproveError = {
    __kind__: "GenericError";
    GenericError: {
        message: string;
        error_code: bigint;
    };
} | {
    __kind__: "TemporarilyUnavailable";
    TemporarilyUnavailable: null;
} | {
    __kind__: "Duplicate";
    Duplicate: {
        duplicate_of: bigint;
    };
} | {
    __kind__: "BadFee";
    BadFee: {
        expected_fee: bigint;
    };
} | {
    __kind__: "AllowanceChanged";
    AllowanceChanged: {
        current_allowance: bigint;
    };
} | {
    __kind__: "CreatedInFuture";
    CreatedInFuture: {
        ledger_time: bigint;
    };
} | {
    __kind__: "TooOld";
    TooOld: null;
} | {
    __kind__: "Expired";
    Expired: {
        ledger_time: bigint;
    };
} | {
    __kind__: "InsufficientFunds";
    InsufficientFunds: {
        balance: bigint;
    };
};
export interface ArchivedRange {
    callback: [Principal, string];
    start: bigint;
    length: bigint;
}
export type Result = {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: TransferError;
};
export interface InitArgs {
    decimals?: number;
    token_symbol: string;
    transfer_fee: bigint;
    metadata: Array<[string, MetadataValue]>;
    minting_account: Account;
    initial_balances: Array<[Account, bigint]>;
    maximum_number_of_accounts?: bigint;
    accounts_overflow_trim_quantity?: bigint;
    fee_collector_account?: Account;
    archive_options: ArchiveOptions;
    max_memo_length?: number;
    token_name: string;
    feature_flags?: FeatureFlags;
}
export type TransferError = {
    __kind__: "GenericError";
    GenericError: {
        message: string;
        error_code: bigint;
    };
} | {
    __kind__: "TemporarilyUnavailable";
    TemporarilyUnavailable: null;
} | {
    __kind__: "BadBurn";
    BadBurn: {
        min_burn_amount: bigint;
    };
} | {
    __kind__: "Duplicate";
    Duplicate: {
        duplicate_of: bigint;
    };
} | {
    __kind__: "BadFee";
    BadFee: {
        expected_fee: bigint;
    };
} | {
    __kind__: "CreatedInFuture";
    CreatedInFuture: {
        ledger_time: bigint;
    };
} | {
    __kind__: "TooOld";
    TooOld: null;
} | {
    __kind__: "InsufficientFunds";
    InsufficientFunds: {
        balance: bigint;
    };
};
export interface UpgradeArgs {
    token_symbol?: string;
    transfer_fee?: bigint;
    metadata?: Array<[string, MetadataValue]>;
    maximum_number_of_accounts?: bigint;
    accounts_overflow_trim_quantity?: bigint;
    change_fee_collector?: ChangeFeeCollector;
    max_memo_length?: number;
    token_name?: string;
    feature_flags?: FeatureFlags;
}
export interface Icrc1Interface {
    get_blocks(arg0: GetBlocksRequest): Promise<GetBlocksResponse>;
    get_data_certificate(): Promise<DataCertificate>;
    get_transactions(arg0: GetBlocksRequest): Promise<GetTransactionsResponse>;
    icrc1_balance_of(arg0: Account): Promise<bigint>;
    icrc1_decimals(): Promise<number>;
    icrc1_fee(): Promise<bigint>;
    icrc1_metadata(): Promise<Array<[string, MetadataValue]>>;
    icrc1_minting_account(): Promise<Account | null>;
    icrc1_name(): Promise<string>;
    icrc1_supported_standards(): Promise<Array<StandardRecord>>;
    icrc1_symbol(): Promise<string>;
    icrc1_total_supply(): Promise<bigint>;
    icrc1_transfer(arg0: TransferArg): Promise<Result>;
    icrc2_allowance(arg0: AllowanceArgs): Promise<Allowance>;
    icrc2_approve(arg0: ApproveArgs): Promise<Result_1>;
    icrc2_transfer_from(arg0: TransferFromArgs): Promise<Result_2>;
}
import type { Account as _Account, Allowance as _Allowance, AllowanceArgs as _AllowanceArgs, Approve as _Approve, ApproveArgs as _ApproveArgs, ApproveError as _ApproveError, ArchivedRange as _ArchivedRange, ArchivedRange_1 as _ArchivedRange_1, Burn as _Burn, DataCertificate as _DataCertificate, GetBlocksResponse as _GetBlocksResponse, GetTransactionsResponse as _GetTransactionsResponse, MetadataValue as _MetadataValue, Mint as _Mint, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Transaction as _Transaction, Transfer as _Transfer, TransferArg as _TransferArg, TransferError as _TransferError, TransferFromArgs as _TransferFromArgs, TransferFromError as _TransferFromError, Value as _Value, Vec as _Vec } from "./declarations/Icrc1.did";
export class Icrc1 implements Icrc1Interface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async get_blocks(arg0: GetBlocksRequest): Promise<GetBlocksResponse> {
        const result = await this.actor.get_blocks(arg0);
        return from_candid_GetBlocksResponse_n1(result);
    }
    async get_data_certificate(): Promise<DataCertificate> {
        const result = await this.actor.get_data_certificate();
        return from_candid_DataCertificate_n11(result);
    }
    async get_transactions(arg0: GetBlocksRequest): Promise<GetTransactionsResponse> {
        const result = await this.actor.get_transactions(arg0);
        return from_candid_GetTransactionsResponse_n13(result);
    }
    async icrc1_balance_of(arg0: Account): Promise<bigint> {
        const result = await this.actor.icrc1_balance_of(to_candid_Account_n35(arg0));
        return result;
    }
    async icrc1_decimals(): Promise<number> {
        const result = await this.actor.icrc1_decimals();
        return result;
    }
    async icrc1_fee(): Promise<bigint> {
        const result = await this.actor.icrc1_fee();
        return result;
    }
    async icrc1_metadata(): Promise<Array<[string, MetadataValue]>> {
        const result = await this.actor.icrc1_metadata();
        return from_candid_vec_n37(result);
    }
    async icrc1_minting_account(): Promise<Account | null> {
        const result = await this.actor.icrc1_minting_account();
        return from_candid_opt_n24(result);
    }
    async icrc1_name(): Promise<string> {
        const result = await this.actor.icrc1_name();
        return result;
    }
    async icrc1_supported_standards(): Promise<Array<StandardRecord>> {
        const result = await this.actor.icrc1_supported_standards();
        return result;
    }
    async icrc1_symbol(): Promise<string> {
        const result = await this.actor.icrc1_symbol();
        return result;
    }
    async icrc1_total_supply(): Promise<bigint> {
        const result = await this.actor.icrc1_total_supply();
        return result;
    }
    async icrc1_transfer(arg0: TransferArg): Promise<Result> {
        const result = await this.actor.icrc1_transfer(to_candid_TransferArg_n41(arg0));
        return from_candid_Result_n43(result);
    }
    async icrc2_allowance(arg0: AllowanceArgs): Promise<Allowance> {
        const result = await this.actor.icrc2_allowance(to_candid_AllowanceArgs_n47(arg0));
        return from_candid_Allowance_n49(result);
    }
    async icrc2_approve(arg0: ApproveArgs): Promise<Result_1> {
        const result = await this.actor.icrc2_approve(to_candid_ApproveArgs_n51(arg0));
        return from_candid_Result_1_n53(result);
    }
    async icrc2_transfer_from(arg0: TransferFromArgs): Promise<Result_2> {
        const result = await this.actor.icrc2_transfer_from(to_candid_TransferFromArgs_n57(arg0));
        return from_candid_Result_2_n59(result);
    }
}
function from_candid_Account_n21(value: _Account): Account {
    return from_candid_record_n22(value);
}
function from_candid_Allowance_n49(value: _Allowance): Allowance {
    return from_candid_record_n50(value);
}
function from_candid_ApproveError_n55(value: _ApproveError): ApproveError {
    return from_candid_variant_n56(value);
}
function from_candid_Approve_n29(value: _Approve): Approve {
    return from_candid_record_n30(value);
}
function from_candid_Burn_n19(value: _Burn): Burn {
    return from_candid_record_n20(value);
}
function from_candid_DataCertificate_n11(value: _DataCertificate): DataCertificate {
    return from_candid_record_n12(value);
}
function from_candid_GetBlocksResponse_n1(value: _GetBlocksResponse): GetBlocksResponse {
    return from_candid_record_n2(value);
}
function from_candid_GetTransactionsResponse_n13(value: _GetTransactionsResponse): GetTransactionsResponse {
    return from_candid_record_n14(value);
}
function from_candid_MetadataValue_n39(value: _MetadataValue): MetadataValue {
    return from_candid_variant_n40(value);
}
function from_candid_Mint_n26(value: _Mint): Mint {
    return from_candid_record_n27(value);
}
function from_candid_Result_1_n53(value: _Result_1): Result_1 {
    return from_candid_variant_n54(value);
}
function from_candid_Result_2_n59(value: _Result_2): Result_2 {
    return from_candid_variant_n60(value);
}
function from_candid_Result_n43(value: _Result): Result {
    return from_candid_variant_n44(value);
}
function from_candid_Transaction_n16(value: _Transaction): Transaction {
    return from_candid_record_n17(value);
}
function from_candid_TransferError_n45(value: _TransferError): TransferError {
    return from_candid_variant_n46(value);
}
function from_candid_TransferFromError_n61(value: _TransferFromError): TransferFromError {
    return from_candid_variant_n62(value);
}
function from_candid_Transfer_n33(value: _Transfer): Transfer {
    return from_candid_record_n34(value);
}
function from_candid_Value_n5(value: _Value): Value {
    return from_candid_variant_n6(value);
}
function from_candid_Vec_n9(value: _Vec): Vec {
    return from_candid_vec_n10(value);
}
function from_candid_opt_n18(value: [] | [_Burn]): Burn | null {
    return value.length === 0 ? null : from_candid_Burn_n19(value[0]);
}
function from_candid_opt_n23(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(value: [] | [_Account]): Account | null {
    return value.length === 0 ? null : from_candid_Account_n21(value[0]);
}
function from_candid_opt_n25(value: [] | [_Mint]): Mint | null {
    return value.length === 0 ? null : from_candid_Mint_n26(value[0]);
}
function from_candid_opt_n28(value: [] | [_Approve]): Approve | null {
    return value.length === 0 ? null : from_candid_Approve_n29(value[0]);
}
function from_candid_opt_n3(value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(value: [] | [_Transfer]): Transfer | null {
    return value.length === 0 ? null : from_candid_Transfer_n33(value[0]);
}
function from_candid_record_n12(value: {
    certificate: [] | [Uint8Array];
    hash_tree: Uint8Array;
}): {
    certificate?: Uint8Array;
    hash_tree: Uint8Array;
} {
    return {
        certificate: record_opt_to_undefined(from_candid_opt_n3(value.certificate)),
        hash_tree: value.hash_tree
    };
}
function from_candid_record_n14(value: {
    first_index: bigint;
    log_length: bigint;
    transactions: Array<_Transaction>;
    archived_transactions: Array<_ArchivedRange_1>;
}): {
    first_index: bigint;
    log_length: bigint;
    transactions: Array<Transaction>;
    archived_transactions: Array<ArchivedRange_1>;
} {
    return {
        first_index: value.first_index,
        log_length: value.log_length,
        transactions: from_candid_vec_n15(value.transactions),
        archived_transactions: value.archived_transactions
    };
}
function from_candid_record_n17(value: {
    burn: [] | [_Burn];
    kind: string;
    mint: [] | [_Mint];
    approve: [] | [_Approve];
    timestamp: bigint;
    transfer: [] | [_Transfer];
}): {
    burn?: Burn;
    kind: string;
    mint?: Mint;
    approve?: Approve;
    timestamp: bigint;
    transfer?: Transfer;
} {
    return {
        burn: record_opt_to_undefined(from_candid_opt_n18(value.burn)),
        kind: value.kind,
        mint: record_opt_to_undefined(from_candid_opt_n25(value.mint)),
        approve: record_opt_to_undefined(from_candid_opt_n28(value.approve)),
        timestamp: value.timestamp,
        transfer: record_opt_to_undefined(from_candid_opt_n32(value.transfer))
    };
}
function from_candid_record_n2(value: {
    certificate: [] | [Uint8Array];
    first_index: bigint;
    blocks: Array<_Value>;
    chain_length: bigint;
    archived_blocks: Array<_ArchivedRange>;
}): {
    certificate?: Uint8Array;
    first_index: bigint;
    blocks: Array<Value>;
    chain_length: bigint;
    archived_blocks: Array<ArchivedRange>;
} {
    return {
        certificate: record_opt_to_undefined(from_candid_opt_n3(value.certificate)),
        first_index: value.first_index,
        blocks: from_candid_vec_n4(value.blocks),
        chain_length: value.chain_length,
        archived_blocks: value.archived_blocks
    };
}
function from_candid_record_n20(value: {
    from: _Account;
    memo: [] | [Uint8Array];
    created_at_time: [] | [bigint];
    amount: bigint;
    spender: [] | [_Account];
}): {
    from: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
    spender?: Account;
} {
    return {
        from: from_candid_Account_n21(value.from),
        memo: record_opt_to_undefined(from_candid_opt_n3(value.memo)),
        created_at_time: record_opt_to_undefined(from_candid_opt_n23(value.created_at_time)),
        amount: value.amount,
        spender: record_opt_to_undefined(from_candid_opt_n24(value.spender))
    };
}
function from_candid_record_n22(value: {
    owner: Principal;
    subaccount: [] | [Uint8Array];
}): {
    owner: Principal;
    subaccount?: Uint8Array;
} {
    return {
        owner: value.owner,
        subaccount: record_opt_to_undefined(from_candid_opt_n3(value.subaccount))
    };
}
function from_candid_record_n27(value: {
    to: _Account;
    memo: [] | [Uint8Array];
    created_at_time: [] | [bigint];
    amount: bigint;
}): {
    to: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
} {
    return {
        to: from_candid_Account_n21(value.to),
        memo: record_opt_to_undefined(from_candid_opt_n3(value.memo)),
        created_at_time: record_opt_to_undefined(from_candid_opt_n23(value.created_at_time)),
        amount: value.amount
    };
}
function from_candid_record_n30(value: {
    fee: [] | [bigint];
    from: _Account;
    memo: [] | [Uint8Array];
    created_at_time: [] | [bigint];
    amount: bigint;
    expected_allowance: [] | [bigint];
    expires_at: [] | [bigint];
    spender: _Account;
}): {
    fee?: bigint;
    from: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
    expected_allowance?: bigint;
    expires_at?: bigint;
    spender: Account;
} {
    return {
        fee: record_opt_to_undefined(from_candid_opt_n31(value.fee)),
        from: from_candid_Account_n21(value.from),
        memo: record_opt_to_undefined(from_candid_opt_n3(value.memo)),
        created_at_time: record_opt_to_undefined(from_candid_opt_n23(value.created_at_time)),
        amount: value.amount,
        expected_allowance: record_opt_to_undefined(from_candid_opt_n31(value.expected_allowance)),
        expires_at: record_opt_to_undefined(from_candid_opt_n23(value.expires_at)),
        spender: from_candid_Account_n21(value.spender)
    };
}
function from_candid_record_n34(value: {
    to: _Account;
    fee: [] | [bigint];
    from: _Account;
    memo: [] | [Uint8Array];
    created_at_time: [] | [bigint];
    amount: bigint;
    spender: [] | [_Account];
}): {
    to: Account;
    fee?: bigint;
    from: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
    spender?: Account;
} {
    return {
        to: from_candid_Account_n21(value.to),
        fee: record_opt_to_undefined(from_candid_opt_n31(value.fee)),
        from: from_candid_Account_n21(value.from),
        memo: record_opt_to_undefined(from_candid_opt_n3(value.memo)),
        created_at_time: record_opt_to_undefined(from_candid_opt_n23(value.created_at_time)),
        amount: value.amount,
        spender: record_opt_to_undefined(from_candid_opt_n24(value.spender))
    };
}
function from_candid_record_n50(value: {
    allowance: bigint;
    expires_at: [] | [bigint];
}): {
    allowance: bigint;
    expires_at?: bigint;
} {
    return {
        allowance: value.allowance,
        expires_at: record_opt_to_undefined(from_candid_opt_n23(value.expires_at))
    };
}
function from_candid_tuple_n38(value: [string, _MetadataValue]): [string, MetadataValue] {
    return [
        value[0],
        from_candid_MetadataValue_n39(value[1])
    ];
}
function from_candid_tuple_n8(value: [string, _Value]): [string, Value] {
    return [
        value[0],
        from_candid_Value_n5(value[1])
    ];
}
function from_candid_variant_n40(value: {
    Int: bigint;
} | {
    Nat: bigint;
} | {
    Blob: Uint8Array;
} | {
    Text: string;
}): {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Text";
    Text: string;
} {
    return "Int" in value ? {
        __kind__: "Int",
        Int: value.Int
    } : "Nat" in value ? {
        __kind__: "Nat",
        Nat: value.Nat
    } : "Blob" in value ? {
        __kind__: "Blob",
        Blob: value.Blob
    } : "Text" in value ? {
        __kind__: "Text",
        Text: value.Text
    } : value;
}
function from_candid_variant_n44(value: {
    Ok: bigint;
} | {
    Err: _TransferError;
}): {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: TransferError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_TransferError_n45(value.Err)
    } : value;
}
function from_candid_variant_n46(value: {
    GenericError: {
        message: string;
        error_code: bigint;
    };
} | {
    TemporarilyUnavailable: null;
} | {
    BadBurn: {
        min_burn_amount: bigint;
    };
} | {
    Duplicate: {
        duplicate_of: bigint;
    };
} | {
    BadFee: {
        expected_fee: bigint;
    };
} | {
    CreatedInFuture: {
        ledger_time: bigint;
    };
} | {
    TooOld: null;
} | {
    InsufficientFunds: {
        balance: bigint;
    };
}): {
    __kind__: "GenericError";
    GenericError: {
        message: string;
        error_code: bigint;
    };
} | {
    __kind__: "TemporarilyUnavailable";
    TemporarilyUnavailable: null;
} | {
    __kind__: "BadBurn";
    BadBurn: {
        min_burn_amount: bigint;
    };
} | {
    __kind__: "Duplicate";
    Duplicate: {
        duplicate_of: bigint;
    };
} | {
    __kind__: "BadFee";
    BadFee: {
        expected_fee: bigint;
    };
} | {
    __kind__: "CreatedInFuture";
    CreatedInFuture: {
        ledger_time: bigint;
    };
} | {
    __kind__: "TooOld";
    TooOld: null;
} | {
    __kind__: "InsufficientFunds";
    InsufficientFunds: {
        balance: bigint;
    };
} {
    return "GenericError" in value ? {
        __kind__: "GenericError",
        GenericError: value.GenericError
    } : "TemporarilyUnavailable" in value ? {
        __kind__: "TemporarilyUnavailable",
        TemporarilyUnavailable: value.TemporarilyUnavailable
    } : "BadBurn" in value ? {
        __kind__: "BadBurn",
        BadBurn: value.BadBurn
    } : "Duplicate" in value ? {
        __kind__: "Duplicate",
        Duplicate: value.Duplicate
    } : "BadFee" in value ? {
        __kind__: "BadFee",
        BadFee: value.BadFee
    } : "CreatedInFuture" in value ? {
        __kind__: "CreatedInFuture",
        CreatedInFuture: value.CreatedInFuture
    } : "TooOld" in value ? {
        __kind__: "TooOld",
        TooOld: value.TooOld
    } : "InsufficientFunds" in value ? {
        __kind__: "InsufficientFunds",
        InsufficientFunds: value.InsufficientFunds
    } : value;
}
function from_candid_variant_n54(value: {
    Ok: bigint;
} | {
    Err: _ApproveError;
}): {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: ApproveError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_ApproveError_n55(value.Err)
    } : value;
}
function from_candid_variant_n56(value: {
    GenericError: {
        message: string;
        error_code: bigint;
    };
} | {
    TemporarilyUnavailable: null;
} | {
    Duplicate: {
        duplicate_of: bigint;
    };
} | {
    BadFee: {
        expected_fee: bigint;
    };
} | {
    AllowanceChanged: {
        current_allowance: bigint;
    };
} | {
    CreatedInFuture: {
        ledger_time: bigint;
    };
} | {
    TooOld: null;
} | {
    Expired: {
        ledger_time: bigint;
    };
} | {
    InsufficientFunds: {
        balance: bigint;
    };
}): {
    __kind__: "GenericError";
    GenericError: {
        message: string;
        error_code: bigint;
    };
} | {
    __kind__: "TemporarilyUnavailable";
    TemporarilyUnavailable: null;
} | {
    __kind__: "Duplicate";
    Duplicate: {
        duplicate_of: bigint;
    };
} | {
    __kind__: "BadFee";
    BadFee: {
        expected_fee: bigint;
    };
} | {
    __kind__: "AllowanceChanged";
    AllowanceChanged: {
        current_allowance: bigint;
    };
} | {
    __kind__: "CreatedInFuture";
    CreatedInFuture: {
        ledger_time: bigint;
    };
} | {
    __kind__: "TooOld";
    TooOld: null;
} | {
    __kind__: "Expired";
    Expired: {
        ledger_time: bigint;
    };
} | {
    __kind__: "InsufficientFunds";
    InsufficientFunds: {
        balance: bigint;
    };
} {
    return "GenericError" in value ? {
        __kind__: "GenericError",
        GenericError: value.GenericError
    } : "TemporarilyUnavailable" in value ? {
        __kind__: "TemporarilyUnavailable",
        TemporarilyUnavailable: value.TemporarilyUnavailable
    } : "Duplicate" in value ? {
        __kind__: "Duplicate",
        Duplicate: value.Duplicate
    } : "BadFee" in value ? {
        __kind__: "BadFee",
        BadFee: value.BadFee
    } : "AllowanceChanged" in value ? {
        __kind__: "AllowanceChanged",
        AllowanceChanged: value.AllowanceChanged
    } : "CreatedInFuture" in value ? {
        __kind__: "CreatedInFuture",
        CreatedInFuture: value.CreatedInFuture
    } : "TooOld" in value ? {
        __kind__: "TooOld",
        TooOld: value.TooOld
    } : "Expired" in value ? {
        __kind__: "Expired",
        Expired: value.Expired
    } : "InsufficientFunds" in value ? {
        __kind__: "InsufficientFunds",
        InsufficientFunds: value.InsufficientFunds
    } : value;
}
function from_candid_variant_n6(value: {
    Int: bigint;
} | {
    Map: Array<[string, _Value]>;
} | {
    Nat: bigint;
} | {
    Nat64: bigint;
} | {
    Blob: Uint8Array;
} | {
    Text: string;
} | {
    Array: _Vec;
}): {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Array<[string, Value]>;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Nat64";
    Nat64: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Array";
    Array: Vec;
} {
    return "Int" in value ? {
        __kind__: "Int",
        Int: value.Int
    } : "Map" in value ? {
        __kind__: "Map",
        Map: from_candid_vec_n7(value.Map)
    } : "Nat" in value ? {
        __kind__: "Nat",
        Nat: value.Nat
    } : "Nat64" in value ? {
        __kind__: "Nat64",
        Nat64: value.Nat64
    } : "Blob" in value ? {
        __kind__: "Blob",
        Blob: value.Blob
    } : "Text" in value ? {
        __kind__: "Text",
        Text: value.Text
    } : "Array" in value ? {
        __kind__: "Array",
        Array: from_candid_Vec_n9(value.Array)
    } : value;
}
function from_candid_variant_n60(value: {
    Ok: bigint;
} | {
    Err: _TransferFromError;
}): {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: TransferFromError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_TransferFromError_n61(value.Err)
    } : value;
}
function from_candid_variant_n62(value: {
    GenericError: {
        message: string;
        error_code: bigint;
    };
} | {
    TemporarilyUnavailable: null;
} | {
    InsufficientAllowance: {
        allowance: bigint;
    };
} | {
    BadBurn: {
        min_burn_amount: bigint;
    };
} | {
    Duplicate: {
        duplicate_of: bigint;
    };
} | {
    BadFee: {
        expected_fee: bigint;
    };
} | {
    CreatedInFuture: {
        ledger_time: bigint;
    };
} | {
    TooOld: null;
} | {
    InsufficientFunds: {
        balance: bigint;
    };
}): {
    __kind__: "GenericError";
    GenericError: {
        message: string;
        error_code: bigint;
    };
} | {
    __kind__: "TemporarilyUnavailable";
    TemporarilyUnavailable: null;
} | {
    __kind__: "InsufficientAllowance";
    InsufficientAllowance: {
        allowance: bigint;
    };
} | {
    __kind__: "BadBurn";
    BadBurn: {
        min_burn_amount: bigint;
    };
} | {
    __kind__: "Duplicate";
    Duplicate: {
        duplicate_of: bigint;
    };
} | {
    __kind__: "BadFee";
    BadFee: {
        expected_fee: bigint;
    };
} | {
    __kind__: "CreatedInFuture";
    CreatedInFuture: {
        ledger_time: bigint;
    };
} | {
    __kind__: "TooOld";
    TooOld: null;
} | {
    __kind__: "InsufficientFunds";
    InsufficientFunds: {
        balance: bigint;
    };
} {
    return "GenericError" in value ? {
        __kind__: "GenericError",
        GenericError: value.GenericError
    } : "TemporarilyUnavailable" in value ? {
        __kind__: "TemporarilyUnavailable",
        TemporarilyUnavailable: value.TemporarilyUnavailable
    } : "InsufficientAllowance" in value ? {
        __kind__: "InsufficientAllowance",
        InsufficientAllowance: value.InsufficientAllowance
    } : "BadBurn" in value ? {
        __kind__: "BadBurn",
        BadBurn: value.BadBurn
    } : "Duplicate" in value ? {
        __kind__: "Duplicate",
        Duplicate: value.Duplicate
    } : "BadFee" in value ? {
        __kind__: "BadFee",
        BadFee: value.BadFee
    } : "CreatedInFuture" in value ? {
        __kind__: "CreatedInFuture",
        CreatedInFuture: value.CreatedInFuture
    } : "TooOld" in value ? {
        __kind__: "TooOld",
        TooOld: value.TooOld
    } : "InsufficientFunds" in value ? {
        __kind__: "InsufficientFunds",
        InsufficientFunds: value.InsufficientFunds
    } : value;
}
function from_candid_vec_n10(value: Array<{
    Int: bigint;
} | {
    Map: Array<[string, _Value]>;
} | {
    Nat: bigint;
} | {
    Nat64: bigint;
} | {
    Blob: Uint8Array;
} | {
    Text: string;
} | {
    Array: _Vec;
}>): Array<{
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Array<[string, Value]>;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Nat64";
    Nat64: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Array";
    Array: Vec;
}> {
    return value.map((x)=>from_candid_variant_n6(x));
}
function from_candid_vec_n15(value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n16(x));
}
function from_candid_vec_n37(value: Array<[string, _MetadataValue]>): Array<[string, MetadataValue]> {
    return value.map((x)=>from_candid_tuple_n38(x));
}
function from_candid_vec_n4(value: Array<_Value>): Array<Value> {
    return value.map((x)=>from_candid_Value_n5(x));
}
function from_candid_vec_n7(value: Array<[string, _Value]>): Array<[string, Value]> {
    return value.map((x)=>from_candid_tuple_n8(x));
}
function to_candid_Account_n35(value: Account): _Account {
    return to_candid_record_n36(value);
}
function to_candid_AllowanceArgs_n47(value: AllowanceArgs): _AllowanceArgs {
    return to_candid_record_n48(value);
}
function to_candid_ApproveArgs_n51(value: ApproveArgs): _ApproveArgs {
    return to_candid_record_n52(value);
}
function to_candid_TransferArg_n41(value: TransferArg): _TransferArg {
    return to_candid_record_n42(value);
}
function to_candid_TransferFromArgs_n57(value: TransferFromArgs): _TransferFromArgs {
    return to_candid_record_n58(value);
}
function to_candid_record_n36(value: {
    owner: Principal;
    subaccount?: Uint8Array;
}): {
    owner: Principal;
    subaccount: [] | [Uint8Array];
} {
    return {
        owner: value.owner,
        subaccount: value.subaccount ? candid_some(value.subaccount) : candid_none()
    };
}
function to_candid_record_n42(value: {
    to: Account;
    fee?: bigint;
    memo?: Uint8Array;
    from_subaccount?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
}): {
    to: _Account;
    fee: [] | [bigint];
    memo: [] | [Uint8Array];
    from_subaccount: [] | [Uint8Array];
    created_at_time: [] | [bigint];
    amount: bigint;
} {
    return {
        to: to_candid_Account_n35(value.to),
        fee: value.fee ? candid_some(value.fee) : candid_none(),
        memo: value.memo ? candid_some(value.memo) : candid_none(),
        from_subaccount: value.from_subaccount ? candid_some(value.from_subaccount) : candid_none(),
        created_at_time: value.created_at_time ? candid_some(value.created_at_time) : candid_none(),
        amount: value.amount
    };
}
function to_candid_record_n48(value: {
    account: Account;
    spender: Account;
}): {
    account: _Account;
    spender: _Account;
} {
    return {
        account: to_candid_Account_n35(value.account),
        spender: to_candid_Account_n35(value.spender)
    };
}
function to_candid_record_n52(value: {
    fee?: bigint;
    memo?: Uint8Array;
    from_subaccount?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
    expected_allowance?: bigint;
    expires_at?: bigint;
    spender: Account;
}): {
    fee: [] | [bigint];
    memo: [] | [Uint8Array];
    from_subaccount: [] | [Uint8Array];
    created_at_time: [] | [bigint];
    amount: bigint;
    expected_allowance: [] | [bigint];
    expires_at: [] | [bigint];
    spender: _Account;
} {
    return {
        fee: value.fee ? candid_some(value.fee) : candid_none(),
        memo: value.memo ? candid_some(value.memo) : candid_none(),
        from_subaccount: value.from_subaccount ? candid_some(value.from_subaccount) : candid_none(),
        created_at_time: value.created_at_time ? candid_some(value.created_at_time) : candid_none(),
        amount: value.amount,
        expected_allowance: value.expected_allowance ? candid_some(value.expected_allowance) : candid_none(),
        expires_at: value.expires_at ? candid_some(value.expires_at) : candid_none(),
        spender: to_candid_Account_n35(value.spender)
    };
}
function to_candid_record_n58(value: {
    to: Account;
    fee?: bigint;
    spender_subaccount?: Uint8Array;
    from: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
}): {
    to: _Account;
    fee: [] | [bigint];
    spender_subaccount: [] | [Uint8Array];
    from: _Account;
    memo: [] | [Uint8Array];
    created_at_time: [] | [bigint];
    amount: bigint;
} {
    return {
        to: to_candid_Account_n35(value.to),
        fee: value.fee ? candid_some(value.fee) : candid_none(),
        spender_subaccount: value.spender_subaccount ? candid_some(value.spender_subaccount) : candid_none(),
        from: to_candid_Account_n35(value.from),
        memo: value.memo ? candid_some(value.memo) : candid_none(),
        created_at_time: value.created_at_time ? candid_some(value.created_at_time) : candid_none(),
        amount: value.amount
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Icrc1 {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Icrc1(actor);
}
