/* eslint-disable */
// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { Principal } from '@icp-sdk/core/principal';
import { IDL } from '@icp-sdk/core/candid';

export interface Icrc28TrustedOriginsResponse {
  'trusted_origins' : Array<string>,
}
export interface PaymentRequest {
  'subscriptionEventId' : string,
  'subaccount' : Uint8Array,
  'subscriptionTimeInterval' : SubscriptionTimeInterval,
  'writerPrincipalId' : string,
  'expirationDate' : bigint,
  'paymentFee' : string,
  'readerPrincipalId' : string,
}
export interface ReaderSubscriptionDetails {
  'readerSubscriptions' : Array<SubscriptionEvent>,
  'readerNotStoppedSubscriptionsWriters' : Array<WriterSubscriptionDetails>,
  'readerPrincipalId' : string,
}
export type Result = { 'ok' : WriterSubscriptionDetails } |
  { 'err' : string };
export type Result_1 = { 'ok' : ReaderSubscriptionDetails } |
  { 'err' : string };
export type Result_2 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_3 = { 'ok' : PaymentRequest } |
  { 'err' : string };
export type Result_4 = { 'ok' : null } |
  { 'err' : string };
export interface SubscriptionEvent {
  'startTime' : bigint,
  'subscriptionEventId' : string,
  'endTime' : bigint,
  'subscriptionTimeInterval' : SubscriptionTimeInterval,
  'writerPrincipalId' : string,
  'paymentFee' : string,
  'isWriterSubscriptionActive' : boolean,
  'readerPrincipalId' : string,
}
export type SubscriptionTimeInterval = { 'LifeTime' : null } |
  { 'Weekly' : null } |
  { 'Monthly' : null } |
  { 'Annually' : null };
export interface SupportedStandard { 'url' : string, 'name' : string }
export interface UpdateSubscriptionDetailsModel {
  'weeklyFee' : [] | [bigint],
  'lifeTimeFee' : [] | [bigint],
  'annuallyFee' : [] | [bigint],
  'monthlyFee' : [] | [bigint],
  'publicationInformation' : [] | [[Principal, string]],
}
export interface WriterSubscriptionDetails {
  'writerSubscriptions' : Array<SubscriptionEvent>,
  'weeklyFee' : [] | [string],
  'paymentReceiverPrincipalId' : string,
  'writerPrincipalId' : string,
  'lifeTimeFee' : [] | [string],
  'isSubscriptionActive' : boolean,
  'annuallyFee' : [] | [string],
  'monthlyFee' : [] | [string],
}
export interface _SERVICE {
  'acceptCycles' : ActorMethod<[], undefined>,
  'availableCycles' : ActorMethod<[], bigint>,
  'checkMyExpiredSubscriptionsNotifications' : ActorMethod<[], undefined>,
  'completeSubscriptionEvent' : ActorMethod<[string], Result_1>,
  'createPaymentRequestAsReader' : ActorMethod<
    [string, SubscriptionTimeInterval, bigint],
    Result_3
  >,
  'disperseTokensForSuccessfulSubscription' : ActorMethod<[string], Result_4>,
  'expiredNotificationsHeartbeatExternal' : ActorMethod<[], undefined>,
  'getCanisterVersion' : ActorMethod<[], string>,
  'getLatestTimerCall' : ActorMethod<[], [string, string]>,
  'getMaxMemorySize' : ActorMethod<[], bigint>,
  'getMemorySize' : ActorMethod<[], bigint>,
  'getPaymentRequestBySubscriptionEventId' : ActorMethod<[string], Result_3>,
  'getReaderSubscriptionDetails' : ActorMethod<[], Result_1>,
  'getWriterSubscriptionDetails' : ActorMethod<[[] | [string]], Result>,
  'getWriterSubscriptionDetailsByPrincipalId' : ActorMethod<[string], Result>,
  'icrc10_supported_standards' : ActorMethod<[], Array<SupportedStandard>>,
  'icrc28_trusted_origins' : ActorMethod<[], Icrc28TrustedOriginsResponse>,
  'isReaderSubscriber' : ActorMethod<[string, string], boolean>,
  'isThereEnoughMemory' : ActorMethod<[], boolean>,
  'isWriterActivatedSubscription' : ActorMethod<[string], boolean>,
  'pendingStuckTokensHeartbeatExternal' : ActorMethod<[], undefined>,
  'pendingTokensHeartbeatExternal' : ActorMethod<[], undefined>,
  'sendNewSubscriptionNotifications' : ActorMethod<
    [SubscriptionEvent],
    undefined
  >,
  'sendStopSubscriptionNotification' : ActorMethod<[string, string], undefined>,
  'setMaxMemorySize' : ActorMethod<[bigint], Result_2>,
  'stopSubscription' : ActorMethod<[string], Result_1>,
  'updateSubscriptionDetails' : ActorMethod<
    [UpdateSubscriptionDetailsModel],
    Result
  >,
}
export const idlFactory: IDL.InterfaceFactory = ({ IDL }) => {
  const SubscriptionTimeInterval = IDL.Variant({
    'LifeTime' : IDL.Null,
    'Weekly' : IDL.Null,
    'Monthly' : IDL.Null,
    'Annually' : IDL.Null,
  });
  const SubscriptionEvent = IDL.Record({
    'startTime' : IDL.Int,
    'subscriptionEventId' : IDL.Text,
    'endTime' : IDL.Int,
    'subscriptionTimeInterval' : SubscriptionTimeInterval,
    'writerPrincipalId' : IDL.Text,
    'paymentFee' : IDL.Text,
    'isWriterSubscriptionActive' : IDL.Bool,
    'readerPrincipalId' : IDL.Text,
  });
  const WriterSubscriptionDetails = IDL.Record({
    'writerSubscriptions' : IDL.Vec(SubscriptionEvent),
    'weeklyFee' : IDL.Opt(IDL.Text),
    'paymentReceiverPrincipalId' : IDL.Text,
    'writerPrincipalId' : IDL.Text,
    'lifeTimeFee' : IDL.Opt(IDL.Text),
    'isSubscriptionActive' : IDL.Bool,
    'annuallyFee' : IDL.Opt(IDL.Text),
    'monthlyFee' : IDL.Opt(IDL.Text),
  });
  const ReaderSubscriptionDetails = IDL.Record({
    'readerSubscriptions' : IDL.Vec(SubscriptionEvent),
    'readerNotStoppedSubscriptionsWriters' : IDL.Vec(WriterSubscriptionDetails),
    'readerPrincipalId' : IDL.Text,
  });
  const Result_1 = IDL.Variant({
    'ok' : ReaderSubscriptionDetails,
    'err' : IDL.Text,
  });
  const PaymentRequest = IDL.Record({
    'subscriptionEventId' : IDL.Text,
    'subaccount' : IDL.Vec(IDL.Nat8),
    'subscriptionTimeInterval' : SubscriptionTimeInterval,
    'writerPrincipalId' : IDL.Text,
    'expirationDate' : IDL.Int,
    'paymentFee' : IDL.Text,
    'readerPrincipalId' : IDL.Text,
  });
  const Result_3 = IDL.Variant({ 'ok' : PaymentRequest, 'err' : IDL.Text });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Result = IDL.Variant({
    'ok' : WriterSubscriptionDetails,
    'err' : IDL.Text,
  });
  const SupportedStandard = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
  const Icrc28TrustedOriginsResponse = IDL.Record({
    'trusted_origins' : IDL.Vec(IDL.Text),
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const UpdateSubscriptionDetailsModel = IDL.Record({
    'weeklyFee' : IDL.Opt(IDL.Nat),
    'lifeTimeFee' : IDL.Opt(IDL.Nat),
    'annuallyFee' : IDL.Opt(IDL.Nat),
    'monthlyFee' : IDL.Opt(IDL.Nat),
    'publicationInformation' : IDL.Opt(IDL.Tuple(IDL.Principal, IDL.Text)),
  });
  
  return IDL.Service({
    'acceptCycles' : IDL.Func([], [], []),
    'availableCycles' : IDL.Func([], [IDL.Nat], ['query']),
    'checkMyExpiredSubscriptionsNotifications' : IDL.Func([], [], []),
    'completeSubscriptionEvent' : IDL.Func([IDL.Text], [Result_1], []),
    'createPaymentRequestAsReader' : IDL.Func(
        [IDL.Text, SubscriptionTimeInterval, IDL.Nat],
        [Result_3],
        [],
      ),
    'disperseTokensForSuccessfulSubscription' : IDL.Func(
        [IDL.Text],
        [Result_4],
        [],
      ),
    'expiredNotificationsHeartbeatExternal' : IDL.Func([], [], []),
    'getCanisterVersion' : IDL.Func([], [IDL.Text], ['query']),
    'getLatestTimerCall' : IDL.Func([], [IDL.Text, IDL.Text], ['query']),
    'getMaxMemorySize' : IDL.Func([], [IDL.Nat], ['query']),
    'getMemorySize' : IDL.Func([], [IDL.Nat], ['query']),
    'getPaymentRequestBySubscriptionEventId' : IDL.Func(
        [IDL.Text],
        [Result_3],
        ['query'],
      ),
    'getReaderSubscriptionDetails' : IDL.Func([], [Result_1], ['query']),
    'getWriterSubscriptionDetails' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [Result],
        ['composite_query'],
      ),
    'getWriterSubscriptionDetailsByPrincipalId' : IDL.Func(
        [IDL.Text],
        [Result],
        ['query'],
      ),
    'icrc10_supported_standards' : IDL.Func(
        [],
        [IDL.Vec(SupportedStandard)],
        ['query'],
      ),
    'icrc28_trusted_origins' : IDL.Func([], [Icrc28TrustedOriginsResponse], []),
    'isReaderSubscriber' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'isThereEnoughMemory' : IDL.Func([], [IDL.Bool], ['query']),
    'isWriterActivatedSubscription' : IDL.Func(
        [IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'pendingStuckTokensHeartbeatExternal' : IDL.Func([], [], []),
    'pendingTokensHeartbeatExternal' : IDL.Func([], [], []),
    'sendNewSubscriptionNotifications' : IDL.Func([SubscriptionEvent], [], []),
    'sendStopSubscriptionNotification' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setMaxMemorySize' : IDL.Func([IDL.Nat], [Result_2], []),
    'stopSubscription' : IDL.Func([IDL.Text], [Result_1], []),
    'updateSubscriptionDetails' : IDL.Func(
        [UpdateSubscriptionDetailsModel],
        [Result],
        [],
      ),
  });
};

export const init: (args: { IDL: typeof IDL }) => IDL.Type[] = ({ IDL }) => {
  return [];
};
