/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/User.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export type Result_2 = {
    __kind__: "ok";
    ok: ReaderSubscriptionDetails;
} | {
    __kind__: "err";
    err: string;
};
export interface Icrc28TrustedOriginsResponse {
    trusted_origins: Array<string>;
}
export interface DailyMetricsData {
    updateCalls: bigint;
    canisterHeapMemorySize: NumericEntity;
    canisterCycles: NumericEntity;
    canisterMemorySize: NumericEntity;
    timeMillis: bigint;
}
export interface UserListItem {
    bio: string;
    socialChannelsUrls: Array<string>;
    principal: string;
    displayName: string;
    followersCount: string;
    website: string;
    isVerified: boolean;
    handle: string;
    fontType: string;
    avatar: string;
}
export type CanisterMemoryAggregatedData = BigUint64Array;
export type Result_5 = {
    __kind__: "ok";
    ok: [bigint, bigint];
} | {
    __kind__: "err";
    err: string;
};
export type GetHandleByPrincipalReturn = {
    __kind__: "ok";
    ok: string | null;
} | {
    __kind__: "err";
    err: string;
};
export type Validate = {
    __kind__: "Ok";
    Ok: string;
} | {
    __kind__: "Err";
    Err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface CanisterMetrics {
    data: CanisterMetricsData;
}
export type Result_4 = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export type Result_11 = {
    __kind__: "ok";
    ok: Array<[string, bigint]>;
} | {
    __kind__: "err";
    err: string;
};
export type CanisterHeapMemoryAggregatedData = BigUint64Array;
export interface NumericEntity {
    avg: bigint;
    max: bigint;
    min: bigint;
    first: bigint;
    last: bigint;
}
export type List = [string, List] | null;
export interface PublicationObject {
    isEditor: boolean;
    publicationName: string;
}
export type AddPublicationReturn = {
    __kind__: "ok";
    ok: User__1;
} | {
    __kind__: "err";
    err: string;
};
export type Result_7 = {
    __kind__: "ok";
    ok: UserListItem;
} | {
    __kind__: "err";
    err: string;
};
export interface ReaderSubscriptionDetails {
    readerSubscriptions: Array<SubscriptionEvent>;
    readerNotStoppedSubscriptionsWriters: Array<WriterSubscriptionDetails>;
    readerPrincipalId: string;
}
export type CanisterMetricsData = {
    __kind__: "hourly";
    hourly: Array<HourlyMetricsData>;
} | {
    __kind__: "daily";
    daily: Array<DailyMetricsData>;
};
export interface WriterSubscriptionDetails {
    writerSubscriptions: Array<SubscriptionEvent>;
    weeklyFee?: string;
    paymentReceiverPrincipalId: string;
    writerPrincipalId: string;
    lifeTimeFee?: string;
    isSubscriptionActive: boolean;
    annuallyFee?: string;
    monthlyFee?: string;
}
export interface PublicationObject__1 {
    isEditor: boolean;
    publicationName: string;
}
export type VerifyResult = {
    __kind__: "Ok";
    Ok: UniquePersonProof;
} | {
    __kind__: "Err";
    Err: string;
};
export type FollowersPrincipals = [string, List] | null;
export interface UserClaimInfo {
    isUserBlocked: boolean;
    maxClaimableTokens: string;
    subaccount?: Uint8Array;
    lastClaimDate?: string;
    isClaimActive: boolean;
}
export interface Date_ {
    day: bigint;
    month: bigint;
    hour: bigint;
    year: bigint;
}
export interface UniquePersonProof {
    provider: UniquePersonProofProvider;
    timestamp: bigint;
}
export interface User {
    bio: string;
    socialChannels: Array<string>;
    followersArray: Array<string>;
    displayName: string;
    followersCount: number;
    nuaTokens: number;
    accountCreated: string;
    publicationsArray: Array<PublicationObject>;
    claimInfo: UserClaimInfo;
    website: string;
    isVerified: boolean;
    handle: string;
    followersPrincipals: FollowersPrincipals;
    followers: Followers;
    avatar: string;
}
export type Result_6 = {
    __kind__: "ok";
    ok: Array<string>;
} | {
    __kind__: "err";
    err: string;
};
export type CanisterCyclesAggregatedData = BigUint64Array;
export type RegisterUserReturn = {
    __kind__: "ok";
    ok: User__1;
} | {
    __kind__: "err";
    err: string;
};
export type NuaBalanceResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface SupportedStandard {
    url: string;
    name: string;
}
export type Result_9 = {
    __kind__: "ok";
    ok: Array<User>;
} | {
    __kind__: "err";
    err: string;
};
export interface GetMetricsParameters {
    dateToMillis: bigint;
    granularity: MetricsGranularity;
    dateFromMillis: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export type Result_10 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export type Followers = [string, List] | null;
export type Result_8 = {
    __kind__: "ok";
    ok: Array<UserListItem>;
} | {
    __kind__: "err";
    err: string;
};
export type RemovePublicationReturn = {
    __kind__: "ok";
    ok: User__1;
} | {
    __kind__: "err";
    err: string;
};
export interface User__1 {
    bio: string;
    socialChannels: Array<string>;
    followersArray: Array<string>;
    displayName: string;
    followersCount: number;
    nuaTokens: number;
    accountCreated: string;
    publicationsArray: Array<PublicationObject>;
    claimInfo: UserClaimInfo;
    website: string;
    isVerified: boolean;
    handle: string;
    followersPrincipals: FollowersPrincipals;
    followers: Followers;
    avatar: string;
}
export interface SubscriptionEvent {
    startTime: bigint;
    subscriptionEventId: string;
    endTime: bigint;
    subscriptionTimeInterval: SubscriptionTimeInterval;
    writerPrincipalId: string;
    paymentFee: string;
    isWriterSubscriptionActive: boolean;
    readerPrincipalId: string;
}
export interface HourlyMetricsData {
    updateCalls: UpdateCallsAggregatedData;
    canisterHeapMemorySize: CanisterHeapMemoryAggregatedData;
    canisterCycles: CanisterCyclesAggregatedData;
    canisterMemorySize: CanisterMemoryAggregatedData;
    timeMillis: bigint;
}
export type GetPrincipalByHandleReturn = {
    __kind__: "ok";
    ok: string | null;
} | {
    __kind__: "err";
    err: string;
};
export type UpdateCallsAggregatedData = BigUint64Array;
export enum MetricsGranularity {
    hourly = "hourly",
    daily = "daily"
}
export enum SubscriptionTimeInterval {
    LifeTime = "LifeTime",
    Weekly = "Weekly",
    Monthly = "Monthly",
    Annually = "Annually"
}
export enum UniquePersonProofProvider {
    DecideAI = "DecideAI"
}
export interface UserInterface {
    acceptCycles(): Promise<void>;
    addNuaBalance(arg0: string): Promise<void>;
    addPublication(arg0: PublicationObject__1, arg1: string): Promise<AddPublicationReturn>;
    adminAirDrop(arg0: number): Promise<Result_10>;
    availableCycles(): Promise<bigint>;
    blockUserFromClaiming(arg0: string): Promise<Result_1>;
    checkMyClaimNotification(): Promise<void>;
    claimRestrictedTokens(): Promise<Result>;
    clearAllMyFollowers(): Promise<string>;
    collectCanisterMetrics(): Promise<void>;
    deleteConfirmedLinkings(): Promise<Result_1>;
    deleteUser(arg0: string): Promise<Result_3>;
    dumpUsers(): Promise<string>;
    followAuthor(arg0: string): Promise<Result>;
    generateAccountIds(): Promise<void>;
    generateLowercaseHandles(): Promise<[string, Array<string>]>;
    getActiveUsersByRange(arg0: Date_): Promise<bigint>;
    getAdmins(): Promise<Result_6>;
    getAllClaimSubaccountIndexes(): Promise<Result_11>;
    getAllHandles(): Promise<Array<string>>;
    getAllUserPrincipals(): Promise<Result_6>;
    getCanisterMetrics(arg0: GetMetricsParameters): Promise<CanisterMetrics | null>;
    getCanisterVersion(): Promise<string>;
    getCgUsers(): Promise<Result_6>;
    getDailyMaxRegistration(): Promise<bigint>;
    getFollowersByPrincipalId(arg0: Principal): Promise<Array<UserListItem>>;
    getFollowersCount(arg0: string): Promise<string>;
    getFollowersPrincipalIdsByPrincipalId(arg0: string): Promise<Array<string>>;
    getHandleByPrincipal(arg0: string): Promise<GetHandleByPrincipalReturn>;
    getHandlesByAccountIdentifiers(arg0: Array<string>): Promise<Array<string>>;
    getHandlesByPrincipals(arg0: Array<string>): Promise<Array<string>>;
    getLastDayClaimedTokensAmount(): Promise<bigint>;
    getLastDayNumberOfClaimEvents(): Promise<bigint>;
    getLinkedPrincipal(arg0: string): Promise<Result_10>;
    getMaxMemorySize(): Promise<bigint>;
    getMemorySize(): Promise<bigint>;
    getMultipleUsersByPrincipalId(arg0: Array<string>): Promise<Result_9>;
    getMyFollowers(): Promise<Result_8>;
    getNuaBalance(arg0: string): Promise<NuaBalanceResult>;
    getNumberOfAllRegisteredUsers(): Promise<bigint>;
    getPlatformOperators(): Promise<List>;
    getPrincipalByHandle(arg0: string): Promise<GetPrincipalByHandleReturn>;
    getPrincipalsByHandles(arg0: Array<string>): Promise<Array<string>>;
    getRegistrationNumberLastDay(): Promise<bigint>;
    getTotalNumberOfClaimedTokens(): Promise<bigint>;
    getTrustedCanisters(): Promise<Result_6>;
    getUser(): Promise<Result>;
    getUserByHandle(arg0: string): Promise<Result>;
    getUserByPrincipalId(arg0: string): Promise<Result>;
    getUserFollowers(arg0: string): Promise<Array<UserListItem>>;
    getUserInternal(arg0: string): Promise<User | null>;
    getUserListItemByHandle(arg0: string): Promise<Result_7>;
    getUsersBlockedFromClaiming(): Promise<Result_6>;
    getUsersByHandles(arg0: Array<string>): Promise<Array<UserListItem>>;
    getUsersByPrincipals(arg0: Array<string>): Promise<Array<UserListItem>>;
    getVerificationStatus(arg0: string): Promise<Result_4>;
    handleClap(arg0: string, arg1: string): Promise<void>;
    icrc10_supported_standards(): Promise<Array<SupportedStandard>>;
    icrc28_trusted_origins(): Promise<Icrc28TrustedOriginsResponse>;
    isRegistrationOpen(): Promise<boolean>;
    isThereEnoughMemory(): Promise<boolean>;
    linkInternetIdentityConfirm(arg0: string): Promise<Result_1>;
    linkInternetIdentityRequest(arg0: string, arg1: string): Promise<Result_1>;
    migrateFollowersHashmapsFromHandlesToPrincipalIds(): Promise<Result_5>;
    registerAdmin(arg0: string): Promise<Result_1>;
    registerCanister(arg0: string): Promise<Result_1>;
    registerCgUser(arg0: string): Promise<Result_1>;
    registerPlatformOperator(arg0: string): Promise<Result_1>;
    registerUser(arg0: string, arg1: string, arg2: string): Promise<RegisterUserReturn>;
    removePoh(arg0: string): Promise<Result>;
    removePublication(arg0: PublicationObject__1, arg1: string): Promise<RemovePublicationReturn>;
    setDailyMaxRegistration(arg0: bigint): Promise<Result_3>;
    setIsClaimActive(arg0: boolean): Promise<Result_4>;
    setMaxMemorySize(arg0: bigint): Promise<Result_3>;
    setMaxNumberOfClaimableTokens(arg0: bigint): Promise<Result_3>;
    setMaxNumberOfDailyClaimableTokens(arg0: bigint): Promise<Result_3>;
    spendNuaBalance(arg0: string): Promise<void>;
    spendRestrictedTokensForSubscription(arg0: string, arg1: bigint): Promise<Result_2>;
    spendRestrictedTokensForTipping(arg0: string, arg1: string, arg2: bigint): Promise<Result_1>;
    testInstructionSize(): Promise<string>;
    unblockUserFromClaiming(arg0: string): Promise<Result_1>;
    unfollowAuthor(arg0: string): Promise<Result>;
    unregisterAdmin(arg0: string): Promise<Result_1>;
    unregisterCanister(arg0: string): Promise<Result_1>;
    unregisterCgUser(arg0: string): Promise<Result_1>;
    unregisterPlatformOperator(arg0: string): Promise<Result_1>;
    updateAvatar(arg0: string): Promise<Result>;
    updateBio(arg0: string): Promise<Result>;
    updateDisplayName(arg0: string): Promise<Result>;
    updateFontType(arg0: string): Promise<Result>;
    updateHandle(arg0: string, arg1: string, arg2: string, arg3: Array<string> | null): Promise<Result>;
    updateLastLogin(): Promise<void>;
    updateSocialLinks(arg0: string, arg1: Array<string>): Promise<Result>;
    updateUserDetails(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<string>): Promise<Result>;
    validate(arg0: any): Promise<Validate>;
    verifyPoh(arg0: string): Promise<VerifyResult>;
}
import type { AddPublicationReturn as _AddPublicationReturn, CanisterMetrics as _CanisterMetrics, CanisterMetricsData as _CanisterMetricsData, DailyMetricsData as _DailyMetricsData, Followers as _Followers, FollowersPrincipals as _FollowersPrincipals, GetHandleByPrincipalReturn as _GetHandleByPrincipalReturn, GetMetricsParameters as _GetMetricsParameters, GetPrincipalByHandleReturn as _GetPrincipalByHandleReturn, HourlyMetricsData as _HourlyMetricsData, List as _List, MetricsGranularity as _MetricsGranularity, NuaBalanceResult as _NuaBalanceResult, PublicationObject as _PublicationObject, ReaderSubscriptionDetails as _ReaderSubscriptionDetails, RegisterUserReturn as _RegisterUserReturn, RemovePublicationReturn as _RemovePublicationReturn, Result as _Result, Result_1 as _Result_1, Result_10 as _Result_10, Result_11 as _Result_11, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Result_8 as _Result_8, Result_9 as _Result_9, SubscriptionEvent as _SubscriptionEvent, SubscriptionTimeInterval as _SubscriptionTimeInterval, UniquePersonProof as _UniquePersonProof, UniquePersonProofProvider as _UniquePersonProofProvider, User as _User, UserClaimInfo as _UserClaimInfo, UserListItem as _UserListItem, User__1 as _User__1, Validate as _Validate, VerifyResult as _VerifyResult, WriterSubscriptionDetails as _WriterSubscriptionDetails } from "./declarations/User.did";
export class User implements UserInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async acceptCycles(): Promise<void> {
        const result = await this.actor.acceptCycles();
        return result;
    }
    async addNuaBalance(arg0: string): Promise<void> {
        const result = await this.actor.addNuaBalance(arg0);
        return result;
    }
    async addPublication(arg0: PublicationObject__1, arg1: string): Promise<AddPublicationReturn> {
        const result = await this.actor.addPublication(arg0, arg1);
        return from_candid_AddPublicationReturn_n1(result);
    }
    async adminAirDrop(arg0: number): Promise<Result_10> {
        const result = await this.actor.adminAirDrop(arg0);
        return from_candid_Result_10_n14(result);
    }
    async availableCycles(): Promise<bigint> {
        const result = await this.actor.availableCycles();
        return result;
    }
    async blockUserFromClaiming(arg0: string): Promise<Result_1> {
        const result = await this.actor.blockUserFromClaiming(arg0);
        return from_candid_Result_1_n16(result);
    }
    async checkMyClaimNotification(): Promise<void> {
        const result = await this.actor.checkMyClaimNotification();
        return result;
    }
    async claimRestrictedTokens(): Promise<Result> {
        const result = await this.actor.claimRestrictedTokens();
        return from_candid_Result_n18(result);
    }
    async clearAllMyFollowers(): Promise<string> {
        const result = await this.actor.clearAllMyFollowers();
        return result;
    }
    async collectCanisterMetrics(): Promise<void> {
        const result = await this.actor.collectCanisterMetrics();
        return result;
    }
    async deleteConfirmedLinkings(): Promise<Result_1> {
        const result = await this.actor.deleteConfirmedLinkings();
        return from_candid_Result_1_n16(result);
    }
    async deleteUser(arg0: string): Promise<Result_3> {
        const result = await this.actor.deleteUser(arg0);
        return from_candid_Result_3_n21(result);
    }
    async dumpUsers(): Promise<string> {
        const result = await this.actor.dumpUsers();
        return result;
    }
    async followAuthor(arg0: string): Promise<Result> {
        const result = await this.actor.followAuthor(arg0);
        return from_candid_Result_n18(result);
    }
    async generateAccountIds(): Promise<void> {
        const result = await this.actor.generateAccountIds();
        return result;
    }
    async generateLowercaseHandles(): Promise<[string, Array<string>]> {
        const result = await this.actor.generateLowercaseHandles();
        return [
            result[0],
            result[1]
        ];
    }
    async getActiveUsersByRange(arg0: Date_): Promise<bigint> {
        const result = await this.actor.getActiveUsersByRange(arg0);
        return result;
    }
    async getAdmins(): Promise<Result_6> {
        const result = await this.actor.getAdmins();
        return from_candid_Result_6_n23(result);
    }
    async getAllClaimSubaccountIndexes(): Promise<Result_11> {
        const result = await this.actor.getAllClaimSubaccountIndexes();
        return from_candid_Result_11_n25(result);
    }
    async getAllHandles(): Promise<Array<string>> {
        const result = await this.actor.getAllHandles();
        return result;
    }
    async getAllUserPrincipals(): Promise<Result_6> {
        const result = await this.actor.getAllUserPrincipals();
        return from_candid_Result_6_n23(result);
    }
    async getCanisterMetrics(arg0: GetMetricsParameters): Promise<CanisterMetrics | null> {
        const result = await this.actor.getCanisterMetrics(to_candid_GetMetricsParameters_n27(arg0));
        return from_candid_opt_n31(result);
    }
    async getCanisterVersion(): Promise<string> {
        const result = await this.actor.getCanisterVersion();
        return result;
    }
    async getCgUsers(): Promise<Result_6> {
        const result = await this.actor.getCgUsers();
        return from_candid_Result_6_n23(result);
    }
    async getDailyMaxRegistration(): Promise<bigint> {
        const result = await this.actor.getDailyMaxRegistration();
        return result;
    }
    async getFollowersByPrincipalId(arg0: Principal): Promise<Array<UserListItem>> {
        const result = await this.actor.getFollowersByPrincipalId(arg0);
        return result;
    }
    async getFollowersCount(arg0: string): Promise<string> {
        const result = await this.actor.getFollowersCount(arg0);
        return result;
    }
    async getFollowersPrincipalIdsByPrincipalId(arg0: string): Promise<Array<string>> {
        const result = await this.actor.getFollowersPrincipalIdsByPrincipalId(arg0);
        return result;
    }
    async getHandleByPrincipal(arg0: string): Promise<GetHandleByPrincipalReturn> {
        const result = await this.actor.getHandleByPrincipal(arg0);
        return from_candid_GetHandleByPrincipalReturn_n36(result);
    }
    async getHandlesByAccountIdentifiers(arg0: Array<string>): Promise<Array<string>> {
        const result = await this.actor.getHandlesByAccountIdentifiers(arg0);
        return result;
    }
    async getHandlesByPrincipals(arg0: Array<string>): Promise<Array<string>> {
        const result = await this.actor.getHandlesByPrincipals(arg0);
        return result;
    }
    async getLastDayClaimedTokensAmount(): Promise<bigint> {
        const result = await this.actor.getLastDayClaimedTokensAmount();
        return result;
    }
    async getLastDayNumberOfClaimEvents(): Promise<bigint> {
        const result = await this.actor.getLastDayNumberOfClaimEvents();
        return result;
    }
    async getLinkedPrincipal(arg0: string): Promise<Result_10> {
        const result = await this.actor.getLinkedPrincipal(arg0);
        return from_candid_Result_10_n14(result);
    }
    async getMaxMemorySize(): Promise<bigint> {
        const result = await this.actor.getMaxMemorySize();
        return result;
    }
    async getMemorySize(): Promise<bigint> {
        const result = await this.actor.getMemorySize();
        return result;
    }
    async getMultipleUsersByPrincipalId(arg0: Array<string>): Promise<Result_9> {
        const result = await this.actor.getMultipleUsersByPrincipalId(arg0);
        return from_candid_Result_9_n38(result);
    }
    async getMyFollowers(): Promise<Result_8> {
        const result = await this.actor.getMyFollowers();
        return from_candid_Result_8_n41(result);
    }
    async getNuaBalance(arg0: string): Promise<NuaBalanceResult> {
        const result = await this.actor.getNuaBalance(arg0);
        return from_candid_NuaBalanceResult_n43(result);
    }
    async getNumberOfAllRegisteredUsers(): Promise<bigint> {
        const result = await this.actor.getNumberOfAllRegisteredUsers();
        return result;
    }
    async getPlatformOperators(): Promise<List> {
        const result = await this.actor.getPlatformOperators();
        return from_candid_List_n12(result);
    }
    async getPrincipalByHandle(arg0: string): Promise<GetPrincipalByHandleReturn> {
        const result = await this.actor.getPrincipalByHandle(arg0);
        return from_candid_GetPrincipalByHandleReturn_n44(result);
    }
    async getPrincipalsByHandles(arg0: Array<string>): Promise<Array<string>> {
        const result = await this.actor.getPrincipalsByHandles(arg0);
        return result;
    }
    async getRegistrationNumberLastDay(): Promise<bigint> {
        const result = await this.actor.getRegistrationNumberLastDay();
        return result;
    }
    async getTotalNumberOfClaimedTokens(): Promise<bigint> {
        const result = await this.actor.getTotalNumberOfClaimedTokens();
        return result;
    }
    async getTrustedCanisters(): Promise<Result_6> {
        const result = await this.actor.getTrustedCanisters();
        return from_candid_Result_6_n23(result);
    }
    async getUser(): Promise<Result> {
        const result = await this.actor.getUser();
        return from_candid_Result_n18(result);
    }
    async getUserByHandle(arg0: string): Promise<Result> {
        const result = await this.actor.getUserByHandle(arg0);
        return from_candid_Result_n18(result);
    }
    async getUserByPrincipalId(arg0: string): Promise<Result> {
        const result = await this.actor.getUserByPrincipalId(arg0);
        return from_candid_Result_n18(result);
    }
    async getUserFollowers(arg0: string): Promise<Array<UserListItem>> {
        const result = await this.actor.getUserFollowers(arg0);
        return result;
    }
    async getUserInternal(arg0: string): Promise<User | null> {
        const result = await this.actor.getUserInternal(arg0);
        return from_candid_opt_n45(result);
    }
    async getUserListItemByHandle(arg0: string): Promise<Result_7> {
        const result = await this.actor.getUserListItemByHandle(arg0);
        return from_candid_Result_7_n46(result);
    }
    async getUsersBlockedFromClaiming(): Promise<Result_6> {
        const result = await this.actor.getUsersBlockedFromClaiming();
        return from_candid_Result_6_n23(result);
    }
    async getUsersByHandles(arg0: Array<string>): Promise<Array<UserListItem>> {
        const result = await this.actor.getUsersByHandles(arg0);
        return result;
    }
    async getUsersByPrincipals(arg0: Array<string>): Promise<Array<UserListItem>> {
        const result = await this.actor.getUsersByPrincipals(arg0);
        return result;
    }
    async getVerificationStatus(arg0: string): Promise<Result_4> {
        const result = await this.actor.getVerificationStatus(arg0);
        return from_candid_Result_4_n48(result);
    }
    async handleClap(arg0: string, arg1: string): Promise<void> {
        const result = await this.actor.handleClap(arg0, arg1);
        return result;
    }
    async icrc10_supported_standards(): Promise<Array<SupportedStandard>> {
        const result = await this.actor.icrc10_supported_standards();
        return result;
    }
    async icrc28_trusted_origins(): Promise<Icrc28TrustedOriginsResponse> {
        const result = await this.actor.icrc28_trusted_origins();
        return result;
    }
    async isRegistrationOpen(): Promise<boolean> {
        const result = await this.actor.isRegistrationOpen();
        return result;
    }
    async isThereEnoughMemory(): Promise<boolean> {
        const result = await this.actor.isThereEnoughMemory();
        return result;
    }
    async linkInternetIdentityConfirm(arg0: string): Promise<Result_1> {
        const result = await this.actor.linkInternetIdentityConfirm(arg0);
        return from_candid_Result_1_n16(result);
    }
    async linkInternetIdentityRequest(arg0: string, arg1: string): Promise<Result_1> {
        const result = await this.actor.linkInternetIdentityRequest(arg0, arg1);
        return from_candid_Result_1_n16(result);
    }
    async migrateFollowersHashmapsFromHandlesToPrincipalIds(): Promise<Result_5> {
        const result = await this.actor.migrateFollowersHashmapsFromHandlesToPrincipalIds();
        return from_candid_Result_5_n50(result);
    }
    async registerAdmin(arg0: string): Promise<Result_1> {
        const result = await this.actor.registerAdmin(arg0);
        return from_candid_Result_1_n16(result);
    }
    async registerCanister(arg0: string): Promise<Result_1> {
        const result = await this.actor.registerCanister(arg0);
        return from_candid_Result_1_n16(result);
    }
    async registerCgUser(arg0: string): Promise<Result_1> {
        const result = await this.actor.registerCgUser(arg0);
        return from_candid_Result_1_n16(result);
    }
    async registerPlatformOperator(arg0: string): Promise<Result_1> {
        const result = await this.actor.registerPlatformOperator(arg0);
        return from_candid_Result_1_n16(result);
    }
    async registerUser(arg0: string, arg1: string, arg2: string): Promise<RegisterUserReturn> {
        const result = await this.actor.registerUser(arg0, arg1, arg2);
        return from_candid_RegisterUserReturn_n52(result);
    }
    async removePoh(arg0: string): Promise<Result> {
        const result = await this.actor.removePoh(arg0);
        return from_candid_Result_n18(result);
    }
    async removePublication(arg0: PublicationObject__1, arg1: string): Promise<RemovePublicationReturn> {
        const result = await this.actor.removePublication(arg0, arg1);
        return from_candid_RemovePublicationReturn_n53(result);
    }
    async setDailyMaxRegistration(arg0: bigint): Promise<Result_3> {
        const result = await this.actor.setDailyMaxRegistration(arg0);
        return from_candid_Result_3_n21(result);
    }
    async setIsClaimActive(arg0: boolean): Promise<Result_4> {
        const result = await this.actor.setIsClaimActive(arg0);
        return from_candid_Result_4_n48(result);
    }
    async setMaxMemorySize(arg0: bigint): Promise<Result_3> {
        const result = await this.actor.setMaxMemorySize(arg0);
        return from_candid_Result_3_n21(result);
    }
    async setMaxNumberOfClaimableTokens(arg0: bigint): Promise<Result_3> {
        const result = await this.actor.setMaxNumberOfClaimableTokens(arg0);
        return from_candid_Result_3_n21(result);
    }
    async setMaxNumberOfDailyClaimableTokens(arg0: bigint): Promise<Result_3> {
        const result = await this.actor.setMaxNumberOfDailyClaimableTokens(arg0);
        return from_candid_Result_3_n21(result);
    }
    async spendNuaBalance(arg0: string): Promise<void> {
        const result = await this.actor.spendNuaBalance(arg0);
        return result;
    }
    async spendRestrictedTokensForSubscription(arg0: string, arg1: bigint): Promise<Result_2> {
        const result = await this.actor.spendRestrictedTokensForSubscription(arg0, arg1);
        return from_candid_Result_2_n54(result);
    }
    async spendRestrictedTokensForTipping(arg0: string, arg1: string, arg2: bigint): Promise<Result_1> {
        const result = await this.actor.spendRestrictedTokensForTipping(arg0, arg1, arg2);
        return from_candid_Result_1_n16(result);
    }
    async testInstructionSize(): Promise<string> {
        const result = await this.actor.testInstructionSize();
        return result;
    }
    async unblockUserFromClaiming(arg0: string): Promise<Result_1> {
        const result = await this.actor.unblockUserFromClaiming(arg0);
        return from_candid_Result_1_n16(result);
    }
    async unfollowAuthor(arg0: string): Promise<Result> {
        const result = await this.actor.unfollowAuthor(arg0);
        return from_candid_Result_n18(result);
    }
    async unregisterAdmin(arg0: string): Promise<Result_1> {
        const result = await this.actor.unregisterAdmin(arg0);
        return from_candid_Result_1_n16(result);
    }
    async unregisterCanister(arg0: string): Promise<Result_1> {
        const result = await this.actor.unregisterCanister(arg0);
        return from_candid_Result_1_n16(result);
    }
    async unregisterCgUser(arg0: string): Promise<Result_1> {
        const result = await this.actor.unregisterCgUser(arg0);
        return from_candid_Result_1_n16(result);
    }
    async unregisterPlatformOperator(arg0: string): Promise<Result_1> {
        const result = await this.actor.unregisterPlatformOperator(arg0);
        return from_candid_Result_1_n16(result);
    }
    async updateAvatar(arg0: string): Promise<Result> {
        const result = await this.actor.updateAvatar(arg0);
        return from_candid_Result_n18(result);
    }
    async updateBio(arg0: string): Promise<Result> {
        const result = await this.actor.updateBio(arg0);
        return from_candid_Result_n18(result);
    }
    async updateDisplayName(arg0: string): Promise<Result> {
        const result = await this.actor.updateDisplayName(arg0);
        return from_candid_Result_n18(result);
    }
    async updateFontType(arg0: string): Promise<Result> {
        const result = await this.actor.updateFontType(arg0);
        return from_candid_Result_n18(result);
    }
    async updateHandle(arg0: string, arg1: string, arg2: string, arg3: Array<string> | null): Promise<Result> {
        const result = await this.actor.updateHandle(arg0, arg1, arg2, to_candid_opt_n66(arg3));
        return from_candid_Result_n18(result);
    }
    async updateLastLogin(): Promise<void> {
        const result = await this.actor.updateLastLogin();
        return result;
    }
    async updateSocialLinks(arg0: string, arg1: Array<string>): Promise<Result> {
        const result = await this.actor.updateSocialLinks(arg0, arg1);
        return from_candid_Result_n18(result);
    }
    async updateUserDetails(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<string>): Promise<Result> {
        const result = await this.actor.updateUserDetails(arg0, arg1, arg2, arg3, arg4);
        return from_candid_Result_n18(result);
    }
    async validate(arg0: any): Promise<Validate> {
        const result = await this.actor.validate(arg0);
        return from_candid_Validate_n67(result);
    }
    async verifyPoh(arg0: string): Promise<VerifyResult> {
        const result = await this.actor.verifyPoh(arg0);
        return from_candid_VerifyResult_n69(result);
    }
}
function from_candid_AddPublicationReturn_n1(value: _AddPublicationReturn): AddPublicationReturn {
    return from_candid_variant_n2(value);
}
function from_candid_CanisterMetricsData_n34(value: _CanisterMetricsData): CanisterMetricsData {
    return from_candid_variant_n35(value);
}
function from_candid_CanisterMetrics_n32(value: _CanisterMetrics): CanisterMetrics {
    return from_candid_record_n33(value);
}
function from_candid_FollowersPrincipals_n9(value: _FollowersPrincipals): FollowersPrincipals {
    return from_candid_opt_n10(value);
}
function from_candid_Followers_n13(value: _Followers): Followers {
    return from_candid_opt_n10(value);
}
function from_candid_GetHandleByPrincipalReturn_n36(value: _GetHandleByPrincipalReturn): GetHandleByPrincipalReturn {
    return from_candid_variant_n37(value);
}
function from_candid_GetPrincipalByHandleReturn_n44(value: _GetPrincipalByHandleReturn): GetPrincipalByHandleReturn {
    return from_candid_variant_n37(value);
}
function from_candid_List_n12(value: _List): List {
    return from_candid_opt_n10(value);
}
function from_candid_NuaBalanceResult_n43(value: _NuaBalanceResult): NuaBalanceResult {
    return from_candid_variant_n15(value);
}
function from_candid_ReaderSubscriptionDetails_n56(value: _ReaderSubscriptionDetails): ReaderSubscriptionDetails {
    return from_candid_record_n57(value);
}
function from_candid_RegisterUserReturn_n52(value: _RegisterUserReturn): RegisterUserReturn {
    return from_candid_variant_n2(value);
}
function from_candid_RemovePublicationReturn_n53(value: _RemovePublicationReturn): RemovePublicationReturn {
    return from_candid_variant_n2(value);
}
function from_candid_Result_10_n14(value: _Result_10): Result_10 {
    return from_candid_variant_n15(value);
}
function from_candid_Result_11_n25(value: _Result_11): Result_11 {
    return from_candid_variant_n26(value);
}
function from_candid_Result_1_n16(value: _Result_1): Result_1 {
    return from_candid_variant_n17(value);
}
function from_candid_Result_2_n54(value: _Result_2): Result_2 {
    return from_candid_variant_n55(value);
}
function from_candid_Result_3_n21(value: _Result_3): Result_3 {
    return from_candid_variant_n22(value);
}
function from_candid_Result_4_n48(value: _Result_4): Result_4 {
    return from_candid_variant_n49(value);
}
function from_candid_Result_5_n50(value: _Result_5): Result_5 {
    return from_candid_variant_n51(value);
}
function from_candid_Result_6_n23(value: _Result_6): Result_6 {
    return from_candid_variant_n24(value);
}
function from_candid_Result_7_n46(value: _Result_7): Result_7 {
    return from_candid_variant_n47(value);
}
function from_candid_Result_8_n41(value: _Result_8): Result_8 {
    return from_candid_variant_n42(value);
}
function from_candid_Result_9_n38(value: _Result_9): Result_9 {
    return from_candid_variant_n39(value);
}
function from_candid_Result_n18(value: _Result): Result {
    return from_candid_variant_n19(value);
}
function from_candid_SubscriptionEvent_n59(value: _SubscriptionEvent): SubscriptionEvent {
    return from_candid_record_n60(value);
}
function from_candid_SubscriptionTimeInterval_n61(value: _SubscriptionTimeInterval): SubscriptionTimeInterval {
    return from_candid_variant_n62(value);
}
function from_candid_UniquePersonProofProvider_n73(value: _UniquePersonProofProvider): UniquePersonProofProvider {
    return from_candid_variant_n74(value);
}
function from_candid_UniquePersonProof_n71(value: _UniquePersonProof): UniquePersonProof {
    return from_candid_record_n72(value);
}
function from_candid_UserClaimInfo_n5(value: _UserClaimInfo): UserClaimInfo {
    return from_candid_record_n6(value);
}
function from_candid_User__1_n3(value: _User__1): User__1 {
    return from_candid_record_n4(value);
}
function from_candid_User_n20(value: _User): User {
    return from_candid_record_n4(value);
}
function from_candid_Validate_n67(value: _Validate): Validate {
    return from_candid_variant_n68(value);
}
function from_candid_VerifyResult_n69(value: _VerifyResult): VerifyResult {
    return from_candid_variant_n70(value);
}
function from_candid_WriterSubscriptionDetails_n64(value: _WriterSubscriptionDetails): WriterSubscriptionDetails {
    return from_candid_record_n65(value);
}
function from_candid_opt_n10(value: [] | [[string, _List]]): [string, List] | null {
    return value.length === 0 ? null : from_candid_tuple_n11(value[0]);
}
function from_candid_opt_n31(value: [] | [_CanisterMetrics]): CanisterMetrics | null {
    return value.length === 0 ? null : from_candid_CanisterMetrics_n32(value[0]);
}
function from_candid_opt_n45(value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n20(value[0]);
}
function from_candid_opt_n7(value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n33(value: {
    data: _CanisterMetricsData;
}): {
    data: CanisterMetricsData;
} {
    return {
        data: from_candid_CanisterMetricsData_n34(value.data)
    };
}
function from_candid_record_n4(value: {
    bio: string;
    socialChannels: Array<string>;
    followersArray: Array<string>;
    displayName: string;
    followersCount: number;
    nuaTokens: number;
    accountCreated: string;
    publicationsArray: Array<_PublicationObject>;
    claimInfo: _UserClaimInfo;
    website: string;
    isVerified: boolean;
    handle: string;
    followersPrincipals: _FollowersPrincipals;
    followers: _Followers;
    avatar: string;
}): {
    bio: string;
    socialChannels: Array<string>;
    followersArray: Array<string>;
    displayName: string;
    followersCount: number;
    nuaTokens: number;
    accountCreated: string;
    publicationsArray: Array<PublicationObject>;
    claimInfo: UserClaimInfo;
    website: string;
    isVerified: boolean;
    handle: string;
    followersPrincipals: FollowersPrincipals;
    followers: Followers;
    avatar: string;
} {
    return {
        bio: value.bio,
        socialChannels: value.socialChannels,
        followersArray: value.followersArray,
        displayName: value.displayName,
        followersCount: value.followersCount,
        nuaTokens: value.nuaTokens,
        accountCreated: value.accountCreated,
        publicationsArray: value.publicationsArray,
        claimInfo: from_candid_UserClaimInfo_n5(value.claimInfo),
        website: value.website,
        isVerified: value.isVerified,
        handle: value.handle,
        followersPrincipals: from_candid_FollowersPrincipals_n9(value.followersPrincipals),
        followers: from_candid_Followers_n13(value.followers),
        avatar: value.avatar
    };
}
function from_candid_record_n57(value: {
    readerSubscriptions: Array<_SubscriptionEvent>;
    readerNotStoppedSubscriptionsWriters: Array<_WriterSubscriptionDetails>;
    readerPrincipalId: string;
}): {
    readerSubscriptions: Array<SubscriptionEvent>;
    readerNotStoppedSubscriptionsWriters: Array<WriterSubscriptionDetails>;
    readerPrincipalId: string;
} {
    return {
        readerSubscriptions: from_candid_vec_n58(value.readerSubscriptions),
        readerNotStoppedSubscriptionsWriters: from_candid_vec_n63(value.readerNotStoppedSubscriptionsWriters),
        readerPrincipalId: value.readerPrincipalId
    };
}
function from_candid_record_n6(value: {
    isUserBlocked: boolean;
    maxClaimableTokens: string;
    subaccount: [] | [Uint8Array];
    lastClaimDate: [] | [string];
    isClaimActive: boolean;
}): {
    isUserBlocked: boolean;
    maxClaimableTokens: string;
    subaccount?: Uint8Array;
    lastClaimDate?: string;
    isClaimActive: boolean;
} {
    return {
        isUserBlocked: value.isUserBlocked,
        maxClaimableTokens: value.maxClaimableTokens,
        subaccount: record_opt_to_undefined(from_candid_opt_n7(value.subaccount)),
        lastClaimDate: record_opt_to_undefined(from_candid_opt_n8(value.lastClaimDate)),
        isClaimActive: value.isClaimActive
    };
}
function from_candid_record_n60(value: {
    startTime: bigint;
    subscriptionEventId: string;
    endTime: bigint;
    subscriptionTimeInterval: _SubscriptionTimeInterval;
    writerPrincipalId: string;
    paymentFee: string;
    isWriterSubscriptionActive: boolean;
    readerPrincipalId: string;
}): {
    startTime: bigint;
    subscriptionEventId: string;
    endTime: bigint;
    subscriptionTimeInterval: SubscriptionTimeInterval;
    writerPrincipalId: string;
    paymentFee: string;
    isWriterSubscriptionActive: boolean;
    readerPrincipalId: string;
} {
    return {
        startTime: value.startTime,
        subscriptionEventId: value.subscriptionEventId,
        endTime: value.endTime,
        subscriptionTimeInterval: from_candid_SubscriptionTimeInterval_n61(value.subscriptionTimeInterval),
        writerPrincipalId: value.writerPrincipalId,
        paymentFee: value.paymentFee,
        isWriterSubscriptionActive: value.isWriterSubscriptionActive,
        readerPrincipalId: value.readerPrincipalId
    };
}
function from_candid_record_n65(value: {
    writerSubscriptions: Array<_SubscriptionEvent>;
    weeklyFee: [] | [string];
    paymentReceiverPrincipalId: string;
    writerPrincipalId: string;
    lifeTimeFee: [] | [string];
    isSubscriptionActive: boolean;
    annuallyFee: [] | [string];
    monthlyFee: [] | [string];
}): {
    writerSubscriptions: Array<SubscriptionEvent>;
    weeklyFee?: string;
    paymentReceiverPrincipalId: string;
    writerPrincipalId: string;
    lifeTimeFee?: string;
    isSubscriptionActive: boolean;
    annuallyFee?: string;
    monthlyFee?: string;
} {
    return {
        writerSubscriptions: from_candid_vec_n58(value.writerSubscriptions),
        weeklyFee: record_opt_to_undefined(from_candid_opt_n8(value.weeklyFee)),
        paymentReceiverPrincipalId: value.paymentReceiverPrincipalId,
        writerPrincipalId: value.writerPrincipalId,
        lifeTimeFee: record_opt_to_undefined(from_candid_opt_n8(value.lifeTimeFee)),
        isSubscriptionActive: value.isSubscriptionActive,
        annuallyFee: record_opt_to_undefined(from_candid_opt_n8(value.annuallyFee)),
        monthlyFee: record_opt_to_undefined(from_candid_opt_n8(value.monthlyFee))
    };
}
function from_candid_record_n72(value: {
    provider: _UniquePersonProofProvider;
    timestamp: bigint;
}): {
    provider: UniquePersonProofProvider;
    timestamp: bigint;
} {
    return {
        provider: from_candid_UniquePersonProofProvider_n73(value.provider),
        timestamp: value.timestamp
    };
}
function from_candid_tuple_n11(value: [string, _List]): [string, List] {
    return [
        value[0],
        from_candid_List_n12(value[1])
    ];
}
function from_candid_variant_n15(value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n17(value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n19(value: {
    ok: _User;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_User_n20(value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(value: {
    ok: _User__1;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: User__1;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_User__1_n3(value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(value: {
    ok: Array<string>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<string>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n26(value: {
    ok: Array<[string, bigint]>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<[string, bigint]>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n35(value: {
    hourly: Array<_HourlyMetricsData>;
} | {
    daily: Array<_DailyMetricsData>;
}): {
    __kind__: "hourly";
    hourly: Array<HourlyMetricsData>;
} | {
    __kind__: "daily";
    daily: Array<DailyMetricsData>;
} {
    return "hourly" in value ? {
        __kind__: "hourly",
        hourly: value.hourly
    } : "daily" in value ? {
        __kind__: "daily",
        daily: value.daily
    } : value;
}
function from_candid_variant_n37(value: {
    ok: [] | [string];
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string | null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_opt_n8(value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n39(value: {
    ok: Array<_User>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<User>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n40(value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n42(value: {
    ok: Array<_UserListItem>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<UserListItem>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n47(value: {
    ok: _UserListItem;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserListItem;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n49(value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n51(value: {
    ok: [bigint, bigint];
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: [bigint, bigint];
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n55(value: {
    ok: _ReaderSubscriptionDetails;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ReaderSubscriptionDetails;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ReaderSubscriptionDetails_n56(value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n62(value: {
    LifeTime: null;
} | {
    Weekly: null;
} | {
    Monthly: null;
} | {
    Annually: null;
}): SubscriptionTimeInterval {
    return "LifeTime" in value ? SubscriptionTimeInterval.LifeTime : "Weekly" in value ? SubscriptionTimeInterval.Weekly : "Monthly" in value ? SubscriptionTimeInterval.Monthly : "Annually" in value ? SubscriptionTimeInterval.Annually : value;
}
function from_candid_variant_n68(value: {
    Ok: string;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: string;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n70(value: {
    Ok: _UniquePersonProof;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: UniquePersonProof;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_UniquePersonProof_n71(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n74(value: {
    DecideAI: null;
}): UniquePersonProofProvider {
    return "DecideAI" in value ? UniquePersonProofProvider.DecideAI : value;
}
function from_candid_vec_n40(value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n20(x));
}
function from_candid_vec_n58(value: Array<_SubscriptionEvent>): Array<SubscriptionEvent> {
    return value.map((x)=>from_candid_SubscriptionEvent_n59(x));
}
function from_candid_vec_n63(value: Array<_WriterSubscriptionDetails>): Array<WriterSubscriptionDetails> {
    return value.map((x)=>from_candid_WriterSubscriptionDetails_n64(x));
}
function to_candid_GetMetricsParameters_n27(value: GetMetricsParameters): _GetMetricsParameters {
    return to_candid_record_n28(value);
}
function to_candid_MetricsGranularity_n29(value: MetricsGranularity): _MetricsGranularity {
    return to_candid_variant_n30(value);
}
function to_candid_opt_n66(value: Array<string> | null): [] | [Array<string>] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n28(value: {
    dateToMillis: bigint;
    granularity: MetricsGranularity;
    dateFromMillis: bigint;
}): {
    dateToMillis: bigint;
    granularity: _MetricsGranularity;
    dateFromMillis: bigint;
} {
    return {
        dateToMillis: value.dateToMillis,
        granularity: to_candid_MetricsGranularity_n29(value.granularity),
        dateFromMillis: value.dateFromMillis
    };
}
function to_candid_variant_n30(value: MetricsGranularity): {
    hourly: null;
} | {
    daily: null;
} {
    return value == MetricsGranularity.hourly ? {
        hourly: null
    } : value == MetricsGranularity.daily ? {
        daily: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): User {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new User(actor);
}
