/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/Subscription.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export type Result_4 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type Result_2 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export type Result = {
    __kind__: "ok";
    ok: WriterSubscriptionDetails;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: PaymentRequest;
} | {
    __kind__: "err";
    err: string;
};
export interface Icrc28TrustedOriginsResponse {
    trusted_origins: Array<string>;
}
export interface SubscriptionEvent {
    startTime: bigint;
    subscriptionEventId: string;
    endTime: bigint;
    subscriptionTimeInterval: SubscriptionTimeInterval;
    writerPrincipalId: string;
    paymentFee: string;
    isWriterSubscriptionActive: boolean;
    readerPrincipalId: string;
}
export interface ReaderSubscriptionDetails {
    readerSubscriptions: Array<SubscriptionEvent>;
    readerNotStoppedSubscriptionsWriters: Array<WriterSubscriptionDetails>;
    readerPrincipalId: string;
}
export interface SupportedStandard {
    url: string;
    name: string;
}
export interface WriterSubscriptionDetails {
    writerSubscriptions: Array<SubscriptionEvent>;
    weeklyFee?: string;
    paymentReceiverPrincipalId: string;
    writerPrincipalId: string;
    lifeTimeFee?: string;
    isSubscriptionActive: boolean;
    annuallyFee?: string;
    monthlyFee?: string;
}
export type Result_1 = {
    __kind__: "ok";
    ok: ReaderSubscriptionDetails;
} | {
    __kind__: "err";
    err: string;
};
export interface PaymentRequest {
    subscriptionEventId: string;
    subaccount: Uint8Array;
    subscriptionTimeInterval: SubscriptionTimeInterval;
    writerPrincipalId: string;
    expirationDate: bigint;
    paymentFee: string;
    readerPrincipalId: string;
}
export interface UpdateSubscriptionDetailsModel {
    weeklyFee?: bigint;
    lifeTimeFee?: bigint;
    annuallyFee?: bigint;
    monthlyFee?: bigint;
    publicationInformation?: [Principal, string];
}
export enum SubscriptionTimeInterval {
    LifeTime = "LifeTime",
    Weekly = "Weekly",
    Monthly = "Monthly",
    Annually = "Annually"
}
export interface SubscriptionInterface {
    acceptCycles(): Promise<void>;
    availableCycles(): Promise<bigint>;
    checkMyExpiredSubscriptionsNotifications(): Promise<void>;
    completeSubscriptionEvent(arg0: string): Promise<Result_1>;
    createPaymentRequestAsReader(arg0: string, arg1: SubscriptionTimeInterval, arg2: bigint): Promise<Result_3>;
    disperseTokensForSuccessfulSubscription(arg0: string): Promise<Result_4>;
    expiredNotificationsHeartbeatExternal(): Promise<void>;
    getCanisterVersion(): Promise<string>;
    getLatestTimerCall(): Promise<[string, string]>;
    getMaxMemorySize(): Promise<bigint>;
    getMemorySize(): Promise<bigint>;
    getPaymentRequestBySubscriptionEventId(arg0: string): Promise<Result_3>;
    getReaderSubscriptionDetails(): Promise<Result_1>;
    getWriterSubscriptionDetails(arg0: string | null): Promise<Result>;
    getWriterSubscriptionDetailsByPrincipalId(arg0: string): Promise<Result>;
    icrc10_supported_standards(): Promise<Array<SupportedStandard>>;
    icrc28_trusted_origins(): Promise<Icrc28TrustedOriginsResponse>;
    isReaderSubscriber(arg0: string, arg1: string): Promise<boolean>;
    isThereEnoughMemory(): Promise<boolean>;
    isWriterActivatedSubscription(arg0: string): Promise<boolean>;
    pendingStuckTokensHeartbeatExternal(): Promise<void>;
    pendingTokensHeartbeatExternal(): Promise<void>;
    sendNewSubscriptionNotifications(arg0: SubscriptionEvent): Promise<void>;
    sendStopSubscriptionNotification(arg0: string, arg1: string): Promise<void>;
    setMaxMemorySize(arg0: bigint): Promise<Result_2>;
    stopSubscription(arg0: string): Promise<Result_1>;
    updateSubscriptionDetails(arg0: UpdateSubscriptionDetailsModel): Promise<Result>;
}
import type { PaymentRequest as _PaymentRequest, ReaderSubscriptionDetails as _ReaderSubscriptionDetails, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, SubscriptionEvent as _SubscriptionEvent, SubscriptionTimeInterval as _SubscriptionTimeInterval, UpdateSubscriptionDetailsModel as _UpdateSubscriptionDetailsModel, WriterSubscriptionDetails as _WriterSubscriptionDetails } from "./declarations/Subscription.did";
export class Subscription implements SubscriptionInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async acceptCycles(): Promise<void> {
        const result = await this.actor.acceptCycles();
        return result;
    }
    async availableCycles(): Promise<bigint> {
        const result = await this.actor.availableCycles();
        return result;
    }
    async checkMyExpiredSubscriptionsNotifications(): Promise<void> {
        const result = await this.actor.checkMyExpiredSubscriptionsNotifications();
        return result;
    }
    async completeSubscriptionEvent(arg0: string): Promise<Result_1> {
        const result = await this.actor.completeSubscriptionEvent(arg0);
        return from_candid_Result_1_n1(result);
    }
    async createPaymentRequestAsReader(arg0: string, arg1: SubscriptionTimeInterval, arg2: bigint): Promise<Result_3> {
        const result = await this.actor.createPaymentRequestAsReader(arg0, to_candid_SubscriptionTimeInterval_n14(arg1), arg2);
        return from_candid_Result_3_n16(result);
    }
    async disperseTokensForSuccessfulSubscription(arg0: string): Promise<Result_4> {
        const result = await this.actor.disperseTokensForSuccessfulSubscription(arg0);
        return from_candid_Result_4_n20(result);
    }
    async expiredNotificationsHeartbeatExternal(): Promise<void> {
        const result = await this.actor.expiredNotificationsHeartbeatExternal();
        return result;
    }
    async getCanisterVersion(): Promise<string> {
        const result = await this.actor.getCanisterVersion();
        return result;
    }
    async getLatestTimerCall(): Promise<[string, string]> {
        const result = await this.actor.getLatestTimerCall();
        return [
            result[0],
            result[1]
        ];
    }
    async getMaxMemorySize(): Promise<bigint> {
        const result = await this.actor.getMaxMemorySize();
        return result;
    }
    async getMemorySize(): Promise<bigint> {
        const result = await this.actor.getMemorySize();
        return result;
    }
    async getPaymentRequestBySubscriptionEventId(arg0: string): Promise<Result_3> {
        const result = await this.actor.getPaymentRequestBySubscriptionEventId(arg0);
        return from_candid_Result_3_n16(result);
    }
    async getReaderSubscriptionDetails(): Promise<Result_1> {
        const result = await this.actor.getReaderSubscriptionDetails();
        return from_candid_Result_1_n1(result);
    }
    async getWriterSubscriptionDetails(arg0: string | null): Promise<Result> {
        const result = await this.actor.getWriterSubscriptionDetails(to_candid_opt_n22(arg0));
        return from_candid_Result_n23(result);
    }
    async getWriterSubscriptionDetailsByPrincipalId(arg0: string): Promise<Result> {
        const result = await this.actor.getWriterSubscriptionDetailsByPrincipalId(arg0);
        return from_candid_Result_n23(result);
    }
    async icrc10_supported_standards(): Promise<Array<SupportedStandard>> {
        const result = await this.actor.icrc10_supported_standards();
        return result;
    }
    async icrc28_trusted_origins(): Promise<Icrc28TrustedOriginsResponse> {
        const result = await this.actor.icrc28_trusted_origins();
        return result;
    }
    async isReaderSubscriber(arg0: string, arg1: string): Promise<boolean> {
        const result = await this.actor.isReaderSubscriber(arg0, arg1);
        return result;
    }
    async isThereEnoughMemory(): Promise<boolean> {
        const result = await this.actor.isThereEnoughMemory();
        return result;
    }
    async isWriterActivatedSubscription(arg0: string): Promise<boolean> {
        const result = await this.actor.isWriterActivatedSubscription(arg0);
        return result;
    }
    async pendingStuckTokensHeartbeatExternal(): Promise<void> {
        const result = await this.actor.pendingStuckTokensHeartbeatExternal();
        return result;
    }
    async pendingTokensHeartbeatExternal(): Promise<void> {
        const result = await this.actor.pendingTokensHeartbeatExternal();
        return result;
    }
    async sendNewSubscriptionNotifications(arg0: SubscriptionEvent): Promise<void> {
        const result = await this.actor.sendNewSubscriptionNotifications(to_candid_SubscriptionEvent_n25(arg0));
        return result;
    }
    async sendStopSubscriptionNotification(arg0: string, arg1: string): Promise<void> {
        const result = await this.actor.sendStopSubscriptionNotification(arg0, arg1);
        return result;
    }
    async setMaxMemorySize(arg0: bigint): Promise<Result_2> {
        const result = await this.actor.setMaxMemorySize(arg0);
        return from_candid_Result_2_n27(result);
    }
    async stopSubscription(arg0: string): Promise<Result_1> {
        const result = await this.actor.stopSubscription(arg0);
        return from_candid_Result_1_n1(result);
    }
    async updateSubscriptionDetails(arg0: UpdateSubscriptionDetailsModel): Promise<Result> {
        const result = await this.actor.updateSubscriptionDetails(to_candid_UpdateSubscriptionDetailsModel_n29(arg0));
        return from_candid_Result_n23(result);
    }
}
function from_candid_PaymentRequest_n18(value: _PaymentRequest): PaymentRequest {
    return from_candid_record_n19(value);
}
function from_candid_ReaderSubscriptionDetails_n3(value: _ReaderSubscriptionDetails): ReaderSubscriptionDetails {
    return from_candid_record_n4(value);
}
function from_candid_Result_1_n1(value: _Result_1): Result_1 {
    return from_candid_variant_n2(value);
}
function from_candid_Result_2_n27(value: _Result_2): Result_2 {
    return from_candid_variant_n28(value);
}
function from_candid_Result_3_n16(value: _Result_3): Result_3 {
    return from_candid_variant_n17(value);
}
function from_candid_Result_4_n20(value: _Result_4): Result_4 {
    return from_candid_variant_n21(value);
}
function from_candid_Result_n23(value: _Result): Result {
    return from_candid_variant_n24(value);
}
function from_candid_SubscriptionEvent_n6(value: _SubscriptionEvent): SubscriptionEvent {
    return from_candid_record_n7(value);
}
function from_candid_SubscriptionTimeInterval_n8(value: _SubscriptionTimeInterval): SubscriptionTimeInterval {
    return from_candid_variant_n9(value);
}
function from_candid_WriterSubscriptionDetails_n11(value: _WriterSubscriptionDetails): WriterSubscriptionDetails {
    return from_candid_record_n12(value);
}
function from_candid_opt_n13(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(value: {
    writerSubscriptions: Array<_SubscriptionEvent>;
    weeklyFee: [] | [string];
    paymentReceiverPrincipalId: string;
    writerPrincipalId: string;
    lifeTimeFee: [] | [string];
    isSubscriptionActive: boolean;
    annuallyFee: [] | [string];
    monthlyFee: [] | [string];
}): {
    writerSubscriptions: Array<SubscriptionEvent>;
    weeklyFee?: string;
    paymentReceiverPrincipalId: string;
    writerPrincipalId: string;
    lifeTimeFee?: string;
    isSubscriptionActive: boolean;
    annuallyFee?: string;
    monthlyFee?: string;
} {
    return {
        writerSubscriptions: from_candid_vec_n5(value.writerSubscriptions),
        weeklyFee: record_opt_to_undefined(from_candid_opt_n13(value.weeklyFee)),
        paymentReceiverPrincipalId: value.paymentReceiverPrincipalId,
        writerPrincipalId: value.writerPrincipalId,
        lifeTimeFee: record_opt_to_undefined(from_candid_opt_n13(value.lifeTimeFee)),
        isSubscriptionActive: value.isSubscriptionActive,
        annuallyFee: record_opt_to_undefined(from_candid_opt_n13(value.annuallyFee)),
        monthlyFee: record_opt_to_undefined(from_candid_opt_n13(value.monthlyFee))
    };
}
function from_candid_record_n19(value: {
    subscriptionEventId: string;
    subaccount: Uint8Array;
    subscriptionTimeInterval: _SubscriptionTimeInterval;
    writerPrincipalId: string;
    expirationDate: bigint;
    paymentFee: string;
    readerPrincipalId: string;
}): {
    subscriptionEventId: string;
    subaccount: Uint8Array;
    subscriptionTimeInterval: SubscriptionTimeInterval;
    writerPrincipalId: string;
    expirationDate: bigint;
    paymentFee: string;
    readerPrincipalId: string;
} {
    return {
        subscriptionEventId: value.subscriptionEventId,
        subaccount: value.subaccount,
        subscriptionTimeInterval: from_candid_SubscriptionTimeInterval_n8(value.subscriptionTimeInterval),
        writerPrincipalId: value.writerPrincipalId,
        expirationDate: value.expirationDate,
        paymentFee: value.paymentFee,
        readerPrincipalId: value.readerPrincipalId
    };
}
function from_candid_record_n4(value: {
    readerSubscriptions: Array<_SubscriptionEvent>;
    readerNotStoppedSubscriptionsWriters: Array<_WriterSubscriptionDetails>;
    readerPrincipalId: string;
}): {
    readerSubscriptions: Array<SubscriptionEvent>;
    readerNotStoppedSubscriptionsWriters: Array<WriterSubscriptionDetails>;
    readerPrincipalId: string;
} {
    return {
        readerSubscriptions: from_candid_vec_n5(value.readerSubscriptions),
        readerNotStoppedSubscriptionsWriters: from_candid_vec_n10(value.readerNotStoppedSubscriptionsWriters),
        readerPrincipalId: value.readerPrincipalId
    };
}
function from_candid_record_n7(value: {
    startTime: bigint;
    subscriptionEventId: string;
    endTime: bigint;
    subscriptionTimeInterval: _SubscriptionTimeInterval;
    writerPrincipalId: string;
    paymentFee: string;
    isWriterSubscriptionActive: boolean;
    readerPrincipalId: string;
}): {
    startTime: bigint;
    subscriptionEventId: string;
    endTime: bigint;
    subscriptionTimeInterval: SubscriptionTimeInterval;
    writerPrincipalId: string;
    paymentFee: string;
    isWriterSubscriptionActive: boolean;
    readerPrincipalId: string;
} {
    return {
        startTime: value.startTime,
        subscriptionEventId: value.subscriptionEventId,
        endTime: value.endTime,
        subscriptionTimeInterval: from_candid_SubscriptionTimeInterval_n8(value.subscriptionTimeInterval),
        writerPrincipalId: value.writerPrincipalId,
        paymentFee: value.paymentFee,
        isWriterSubscriptionActive: value.isWriterSubscriptionActive,
        readerPrincipalId: value.readerPrincipalId
    };
}
function from_candid_variant_n17(value: {
    ok: _PaymentRequest;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PaymentRequest;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PaymentRequest_n18(value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(value: {
    ok: _ReaderSubscriptionDetails;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ReaderSubscriptionDetails;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ReaderSubscriptionDetails_n3(value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(value: {
    ok: _WriterSubscriptionDetails;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: WriterSubscriptionDetails;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_WriterSubscriptionDetails_n11(value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n28(value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(value: {
    LifeTime: null;
} | {
    Weekly: null;
} | {
    Monthly: null;
} | {
    Annually: null;
}): SubscriptionTimeInterval {
    return "LifeTime" in value ? SubscriptionTimeInterval.LifeTime : "Weekly" in value ? SubscriptionTimeInterval.Weekly : "Monthly" in value ? SubscriptionTimeInterval.Monthly : "Annually" in value ? SubscriptionTimeInterval.Annually : value;
}
function from_candid_vec_n10(value: Array<_WriterSubscriptionDetails>): Array<WriterSubscriptionDetails> {
    return value.map((x)=>from_candid_WriterSubscriptionDetails_n11(x));
}
function from_candid_vec_n5(value: Array<_SubscriptionEvent>): Array<SubscriptionEvent> {
    return value.map((x)=>from_candid_SubscriptionEvent_n6(x));
}
function to_candid_SubscriptionEvent_n25(value: SubscriptionEvent): _SubscriptionEvent {
    return to_candid_record_n26(value);
}
function to_candid_SubscriptionTimeInterval_n14(value: SubscriptionTimeInterval): _SubscriptionTimeInterval {
    return to_candid_variant_n15(value);
}
function to_candid_UpdateSubscriptionDetailsModel_n29(value: UpdateSubscriptionDetailsModel): _UpdateSubscriptionDetailsModel {
    return to_candid_record_n30(value);
}
function to_candid_opt_n22(value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n26(value: {
    startTime: bigint;
    subscriptionEventId: string;
    endTime: bigint;
    subscriptionTimeInterval: SubscriptionTimeInterval;
    writerPrincipalId: string;
    paymentFee: string;
    isWriterSubscriptionActive: boolean;
    readerPrincipalId: string;
}): {
    startTime: bigint;
    subscriptionEventId: string;
    endTime: bigint;
    subscriptionTimeInterval: _SubscriptionTimeInterval;
    writerPrincipalId: string;
    paymentFee: string;
    isWriterSubscriptionActive: boolean;
    readerPrincipalId: string;
} {
    return {
        startTime: value.startTime,
        subscriptionEventId: value.subscriptionEventId,
        endTime: value.endTime,
        subscriptionTimeInterval: to_candid_SubscriptionTimeInterval_n14(value.subscriptionTimeInterval),
        writerPrincipalId: value.writerPrincipalId,
        paymentFee: value.paymentFee,
        isWriterSubscriptionActive: value.isWriterSubscriptionActive,
        readerPrincipalId: value.readerPrincipalId
    };
}
function to_candid_record_n30(value: {
    weeklyFee?: bigint;
    lifeTimeFee?: bigint;
    annuallyFee?: bigint;
    monthlyFee?: bigint;
    publicationInformation?: [Principal, string];
}): {
    weeklyFee: [] | [bigint];
    lifeTimeFee: [] | [bigint];
    annuallyFee: [] | [bigint];
    monthlyFee: [] | [bigint];
    publicationInformation: [] | [[Principal, string]];
} {
    return {
        weeklyFee: value.weeklyFee ? candid_some(value.weeklyFee) : candid_none(),
        lifeTimeFee: value.lifeTimeFee ? candid_some(value.lifeTimeFee) : candid_none(),
        annuallyFee: value.annuallyFee ? candid_some(value.annuallyFee) : candid_none(),
        monthlyFee: value.monthlyFee ? candid_some(value.monthlyFee) : candid_none(),
        publicationInformation: value.publicationInformation ? candid_some(value.publicationInformation) : candid_none()
    };
}
function to_candid_variant_n15(value: SubscriptionTimeInterval): {
    LifeTime: null;
} | {
    Weekly: null;
} | {
    Monthly: null;
} | {
    Annually: null;
} {
    return value == SubscriptionTimeInterval.LifeTime ? {
        LifeTime: null
    } : value == SubscriptionTimeInterval.Weekly ? {
        Weekly: null
    } : value == SubscriptionTimeInterval.Monthly ? {
        Monthly: null
    } : value == SubscriptionTimeInterval.Annually ? {
        Annually: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Subscription {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Subscription(actor);
}
