// @ts-nocheck
/* eslint-disable */

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { Principal } from '@icp-sdk/core/principal';
import { IDL } from '@icp-sdk/core/candid';

export interface GetUserNotificationsResponse {
  'notifications' : Array<Notification>,
  'totalCount' : string,
}
export interface Icrc28TrustedOriginsResponse {
  'trusted_origins' : Array<string>,
}
export interface Notification {
  'id' : string,
  'content' : NotificationContent,
  'read' : boolean,
  'timestamp' : string,
  'notificationReceiverPrincipalId' : string,
}
export type NotificationContent = { 'FaucetClaimAvailable' : null } |
  {
    'TipReceived' : {
      'bucketCanisterId' : string,
      'amountOfTokens' : string,
      'tipSenderPrincipal' : string,
      'publicationPrincipalId' : [] | [string],
      'postTitle' : string,
      'numberOfApplauds' : string,
      'tippedTokenSymbol' : string,
      'postId' : string,
    }
  } |
  {
    'NewArticleByFollowedWriter' : {
      'bucketCanisterId' : string,
      'postWriterPrincipal' : string,
      'postTitle' : string,
      'postId' : string,
    }
  } |
  {
    'AuthorLosesSubscriber' : {
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscriberPrincipalId' : string,
    }
  } |
  {
    'YouSubscribedToAuthor' : {
      'amountOfTokens' : string,
      'subscriptionEndTime' : string,
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscribedWriterPrincipalId' : string,
      'subscriptionStartTime' : string,
      'isPublication' : boolean,
    }
  } |
  {
    'NewCommentOnMyArticle' : {
      'bucketCanisterId' : string,
      'commentId' : string,
      'isReply' : boolean,
      'commentContent' : string,
      'postTitle' : string,
      'commenterPrincipal' : string,
      'postId' : string,
    }
  } |
  { 'VerifyProfile' : null } |
  {
    'YouUnsubscribedFromAuthor' : {
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscribedWriterPrincipalId' : string,
      'isPublication' : boolean,
    }
  } |
  { 'NewFollower' : { 'followerPrincipalId' : string } } |
  {
    'ReaderExpiredSubscription' : {
      'amountOfTokens' : string,
      'subscriptionEndTime' : string,
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscribedWriterPrincipalId' : string,
      'subscriptionStartTime' : string,
      'isPublication' : boolean,
    }
  } |
  {
    'ReplyToMyComment' : {
      'bucketCanisterId' : string,
      'postWriterPrincipal' : string,
      'myCommentId' : string,
      'myCommentContent' : string,
      'replyCommentContent' : string,
      'postTitle' : string,
      'replyCommenterPrincipal' : string,
      'replyCommentId' : string,
      'postId' : string,
    }
  } |
  {
    'PremiumArticleSold' : {
      'bucketCanisterId' : string,
      'amountOfTokens' : string,
      'publicationPrincipalId' : [] | [string],
      'purchasedTokenSymbol' : string,
      'purchaserPrincipal' : string,
      'postTitle' : string,
      'postId' : string,
    }
  } |
  {
    'NewArticleByFollowedTag' : {
      'bucketCanisterId' : string,
      'tagName' : string,
      'postWriterPrincipal' : string,
      'postTitle' : string,
      'postId' : string,
    }
  } |
  {
    'AuthorGainsNewSubscriber' : {
      'amountOfTokens' : string,
      'subscriptionEndTime' : string,
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscriptionStartTime' : string,
      'subscriberPrincipalId' : string,
    }
  };
export type NotificationContent__1 = { 'FaucetClaimAvailable' : null } |
  {
    'TipReceived' : {
      'bucketCanisterId' : string,
      'amountOfTokens' : string,
      'tipSenderPrincipal' : string,
      'publicationPrincipalId' : [] | [string],
      'postTitle' : string,
      'numberOfApplauds' : string,
      'tippedTokenSymbol' : string,
      'postId' : string,
    }
  } |
  {
    'NewArticleByFollowedWriter' : {
      'bucketCanisterId' : string,
      'postWriterPrincipal' : string,
      'postTitle' : string,
      'postId' : string,
    }
  } |
  {
    'AuthorLosesSubscriber' : {
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscriberPrincipalId' : string,
    }
  } |
  {
    'YouSubscribedToAuthor' : {
      'amountOfTokens' : string,
      'subscriptionEndTime' : string,
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscribedWriterPrincipalId' : string,
      'subscriptionStartTime' : string,
      'isPublication' : boolean,
    }
  } |
  {
    'NewCommentOnMyArticle' : {
      'bucketCanisterId' : string,
      'commentId' : string,
      'isReply' : boolean,
      'commentContent' : string,
      'postTitle' : string,
      'commenterPrincipal' : string,
      'postId' : string,
    }
  } |
  { 'VerifyProfile' : null } |
  {
    'YouUnsubscribedFromAuthor' : {
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscribedWriterPrincipalId' : string,
      'isPublication' : boolean,
    }
  } |
  { 'NewFollower' : { 'followerPrincipalId' : string } } |
  {
    'ReaderExpiredSubscription' : {
      'amountOfTokens' : string,
      'subscriptionEndTime' : string,
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscribedWriterPrincipalId' : string,
      'subscriptionStartTime' : string,
      'isPublication' : boolean,
    }
  } |
  {
    'ReplyToMyComment' : {
      'bucketCanisterId' : string,
      'postWriterPrincipal' : string,
      'myCommentId' : string,
      'myCommentContent' : string,
      'replyCommentContent' : string,
      'postTitle' : string,
      'replyCommenterPrincipal' : string,
      'replyCommentId' : string,
      'postId' : string,
    }
  } |
  {
    'PremiumArticleSold' : {
      'bucketCanisterId' : string,
      'amountOfTokens' : string,
      'publicationPrincipalId' : [] | [string],
      'purchasedTokenSymbol' : string,
      'purchaserPrincipal' : string,
      'postTitle' : string,
      'postId' : string,
    }
  } |
  {
    'NewArticleByFollowedTag' : {
      'bucketCanisterId' : string,
      'tagName' : string,
      'postWriterPrincipal' : string,
      'postTitle' : string,
      'postId' : string,
    }
  } |
  {
    'AuthorGainsNewSubscriber' : {
      'amountOfTokens' : string,
      'subscriptionEndTime' : string,
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscriptionStartTime' : string,
      'subscriberPrincipalId' : string,
    }
  };
export type Result = { 'ok' : UserNotificationSettings } |
  { 'err' : string };
export type Result_1 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_2 = { 'ok' : null } |
  { 'err' : string };
export type SubscriptionTimeInterval = { 'LifeTime' : null } |
  { 'Weekly' : null } |
  { 'Monthly' : null } |
  { 'Annually' : null };
export interface SupportedStandard { 'url' : string, 'name' : string }
export interface UserNotificationSettings {
  'premiumArticleSold' : boolean,
  'verifyProfile' : boolean,
  'tipReceived' : boolean,
  'authorGainsNewSubscriber' : boolean,
  'authorLosesSubscriber' : boolean,
  'youSubscribedToAuthor' : boolean,
  'newCommentOnMyArticle' : boolean,
  'replyToMyComment' : boolean,
  'youUnsubscribedFromAuthor' : boolean,
  'newFollower' : boolean,
  'readerExpiredSubscription' : boolean,
  'newArticleByFollowedWriter' : boolean,
  'newArticleByFollowedTag' : boolean,
  'faucetClaimAvailable' : boolean,
}
export interface _SERVICE {
  'acceptCycles' : ActorMethod<[], undefined>,
  'availableCycles' : ActorMethod<[], bigint>,
  'broadcastNotification' : ActorMethod<[NotificationContent__1], Result_2>,
  'createNotification' : ActorMethod<
    [string, NotificationContent__1],
    undefined
  >,
  'createNotifications' : ActorMethod<
    [Array<[string, NotificationContent__1]>],
    undefined
  >,
  'getCanisterVersion' : ActorMethod<[], string>,
  'getMaxMemorySize' : ActorMethod<[], bigint>,
  'getMemorySize' : ActorMethod<[], bigint>,
  'getUserNotificationSettings' : ActorMethod<[], UserNotificationSettings>,
  'getUserNotifications' : ActorMethod<
    [string, string],
    GetUserNotificationsResponse
  >,
  'icrc10_supported_standards' : ActorMethod<[], Array<SupportedStandard>>,
  'icrc28_trusted_origins' : ActorMethod<[], Icrc28TrustedOriginsResponse>,
  'isThereEnoughMemory' : ActorMethod<[], boolean>,
  'markNotificationsAsRead' : ActorMethod<[Array<string>], undefined>,
  'setMaxMemorySize' : ActorMethod<[bigint], Result_1>,
  'updateNotificationSettings' : ActorMethod<
    [UserNotificationSettings],
    Result
  >,
}
export const idlFactory: IDL.InterfaceFactory = ({ IDL }) => {
  const SubscriptionTimeInterval = IDL.Variant({
    'LifeTime' : IDL.Null,
    'Weekly' : IDL.Null,
    'Monthly' : IDL.Null,
    'Annually' : IDL.Null,
  });
  const NotificationContent__1 = IDL.Variant({
    'FaucetClaimAvailable' : IDL.Null,
    'TipReceived' : IDL.Record({
      'bucketCanisterId' : IDL.Text,
      'amountOfTokens' : IDL.Text,
      'tipSenderPrincipal' : IDL.Text,
      'publicationPrincipalId' : IDL.Opt(IDL.Text),
      'postTitle' : IDL.Text,
      'numberOfApplauds' : IDL.Text,
      'tippedTokenSymbol' : IDL.Text,
      'postId' : IDL.Text,
    }),
    'NewArticleByFollowedWriter' : IDL.Record({
      'bucketCanisterId' : IDL.Text,
      'postWriterPrincipal' : IDL.Text,
      'postTitle' : IDL.Text,
      'postId' : IDL.Text,
    }),
    'AuthorLosesSubscriber' : IDL.Record({
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscriberPrincipalId' : IDL.Text,
    }),
    'YouSubscribedToAuthor' : IDL.Record({
      'amountOfTokens' : IDL.Text,
      'subscriptionEndTime' : IDL.Text,
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscribedWriterPrincipalId' : IDL.Text,
      'subscriptionStartTime' : IDL.Text,
      'isPublication' : IDL.Bool,
    }),
    'NewCommentOnMyArticle' : IDL.Record({
      'bucketCanisterId' : IDL.Text,
      'commentId' : IDL.Text,
      'isReply' : IDL.Bool,
      'commentContent' : IDL.Text,
      'postTitle' : IDL.Text,
      'commenterPrincipal' : IDL.Text,
      'postId' : IDL.Text,
    }),
    'VerifyProfile' : IDL.Null,
    'YouUnsubscribedFromAuthor' : IDL.Record({
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscribedWriterPrincipalId' : IDL.Text,
      'isPublication' : IDL.Bool,
    }),
    'NewFollower' : IDL.Record({ 'followerPrincipalId' : IDL.Text }),
    'ReaderExpiredSubscription' : IDL.Record({
      'amountOfTokens' : IDL.Text,
      'subscriptionEndTime' : IDL.Text,
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscribedWriterPrincipalId' : IDL.Text,
      'subscriptionStartTime' : IDL.Text,
      'isPublication' : IDL.Bool,
    }),
    'ReplyToMyComment' : IDL.Record({
      'bucketCanisterId' : IDL.Text,
      'postWriterPrincipal' : IDL.Text,
      'myCommentId' : IDL.Text,
      'myCommentContent' : IDL.Text,
      'replyCommentContent' : IDL.Text,
      'postTitle' : IDL.Text,
      'replyCommenterPrincipal' : IDL.Text,
      'replyCommentId' : IDL.Text,
      'postId' : IDL.Text,
    }),
    'PremiumArticleSold' : IDL.Record({
      'bucketCanisterId' : IDL.Text,
      'amountOfTokens' : IDL.Text,
      'publicationPrincipalId' : IDL.Opt(IDL.Text),
      'purchasedTokenSymbol' : IDL.Text,
      'purchaserPrincipal' : IDL.Text,
      'postTitle' : IDL.Text,
      'postId' : IDL.Text,
    }),
    'NewArticleByFollowedTag' : IDL.Record({
      'bucketCanisterId' : IDL.Text,
      'tagName' : IDL.Text,
      'postWriterPrincipal' : IDL.Text,
      'postTitle' : IDL.Text,
      'postId' : IDL.Text,
    }),
    'AuthorGainsNewSubscriber' : IDL.Record({
      'amountOfTokens' : IDL.Text,
      'subscriptionEndTime' : IDL.Text,
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscriptionStartTime' : IDL.Text,
      'subscriberPrincipalId' : IDL.Text,
    }),
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const UserNotificationSettings = IDL.Record({
    'premiumArticleSold' : IDL.Bool,
    'verifyProfile' : IDL.Bool,
    'tipReceived' : IDL.Bool,
    'authorGainsNewSubscriber' : IDL.Bool,
    'authorLosesSubscriber' : IDL.Bool,
    'youSubscribedToAuthor' : IDL.Bool,
    'newCommentOnMyArticle' : IDL.Bool,
    'replyToMyComment' : IDL.Bool,
    'youUnsubscribedFromAuthor' : IDL.Bool,
    'newFollower' : IDL.Bool,
    'readerExpiredSubscription' : IDL.Bool,
    'newArticleByFollowedWriter' : IDL.Bool,
    'newArticleByFollowedTag' : IDL.Bool,
    'faucetClaimAvailable' : IDL.Bool,
  });
  const NotificationContent = IDL.Variant({
    'FaucetClaimAvailable' : IDL.Null,
    'TipReceived' : IDL.Record({
      'bucketCanisterId' : IDL.Text,
      'amountOfTokens' : IDL.Text,
      'tipSenderPrincipal' : IDL.Text,
      'publicationPrincipalId' : IDL.Opt(IDL.Text),
      'postTitle' : IDL.Text,
      'numberOfApplauds' : IDL.Text,
      'tippedTokenSymbol' : IDL.Text,
      'postId' : IDL.Text,
    }),
    'NewArticleByFollowedWriter' : IDL.Record({
      'bucketCanisterId' : IDL.Text,
      'postWriterPrincipal' : IDL.Text,
      'postTitle' : IDL.Text,
      'postId' : IDL.Text,
    }),
    'AuthorLosesSubscriber' : IDL.Record({
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscriberPrincipalId' : IDL.Text,
    }),
    'YouSubscribedToAuthor' : IDL.Record({
      'amountOfTokens' : IDL.Text,
      'subscriptionEndTime' : IDL.Text,
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscribedWriterPrincipalId' : IDL.Text,
      'subscriptionStartTime' : IDL.Text,
      'isPublication' : IDL.Bool,
    }),
    'NewCommentOnMyArticle' : IDL.Record({
      'bucketCanisterId' : IDL.Text,
      'commentId' : IDL.Text,
      'isReply' : IDL.Bool,
      'commentContent' : IDL.Text,
      'postTitle' : IDL.Text,
      'commenterPrincipal' : IDL.Text,
      'postId' : IDL.Text,
    }),
    'VerifyProfile' : IDL.Null,
    'YouUnsubscribedFromAuthor' : IDL.Record({
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscribedWriterPrincipalId' : IDL.Text,
      'isPublication' : IDL.Bool,
    }),
    'NewFollower' : IDL.Record({ 'followerPrincipalId' : IDL.Text }),
    'ReaderExpiredSubscription' : IDL.Record({
      'amountOfTokens' : IDL.Text,
      'subscriptionEndTime' : IDL.Text,
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscribedWriterPrincipalId' : IDL.Text,
      'subscriptionStartTime' : IDL.Text,
      'isPublication' : IDL.Bool,
    }),
    'ReplyToMyComment' : IDL.Record({
      'bucketCanisterId' : IDL.Text,
      'postWriterPrincipal' : IDL.Text,
      'myCommentId' : IDL.Text,
      'myCommentContent' : IDL.Text,
      'replyCommentContent' : IDL.Text,
      'postTitle' : IDL.Text,
      'replyCommenterPrincipal' : IDL.Text,
      'replyCommentId' : IDL.Text,
      'postId' : IDL.Text,
    }),
    'PremiumArticleSold' : IDL.Record({
      'bucketCanisterId' : IDL.Text,
      'amountOfTokens' : IDL.Text,
      'publicationPrincipalId' : IDL.Opt(IDL.Text),
      'purchasedTokenSymbol' : IDL.Text,
      'purchaserPrincipal' : IDL.Text,
      'postTitle' : IDL.Text,
      'postId' : IDL.Text,
    }),
    'NewArticleByFollowedTag' : IDL.Record({
      'bucketCanisterId' : IDL.Text,
      'tagName' : IDL.Text,
      'postWriterPrincipal' : IDL.Text,
      'postTitle' : IDL.Text,
      'postId' : IDL.Text,
    }),
    'AuthorGainsNewSubscriber' : IDL.Record({
      'amountOfTokens' : IDL.Text,
      'subscriptionEndTime' : IDL.Text,
      'subscriptionTimeInterval' : SubscriptionTimeInterval,
      'subscriptionStartTime' : IDL.Text,
      'subscriberPrincipalId' : IDL.Text,
    }),
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'content' : NotificationContent,
    'read' : IDL.Bool,
    'timestamp' : IDL.Text,
    'notificationReceiverPrincipalId' : IDL.Text,
  });
  const GetUserNotificationsResponse = IDL.Record({
    'notifications' : IDL.Vec(Notification),
    'totalCount' : IDL.Text,
  });
  const SupportedStandard = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
  const Icrc28TrustedOriginsResponse = IDL.Record({
    'trusted_origins' : IDL.Vec(IDL.Text),
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const Result = IDL.Variant({
    'ok' : UserNotificationSettings,
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    'acceptCycles' : IDL.Func([], [], []),
    'availableCycles' : IDL.Func([], [IDL.Nat], ['query']),
    'broadcastNotification' : IDL.Func(
        [NotificationContent__1],
        [Result_2],
        [],
      ),
    'createNotification' : IDL.Func([IDL.Text, NotificationContent__1], [], []),
    'createNotifications' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, NotificationContent__1))],
        [],
        [],
      ),
    'getCanisterVersion' : IDL.Func([], [IDL.Text], ['query']),
    'getMaxMemorySize' : IDL.Func([], [IDL.Nat], ['query']),
    'getMemorySize' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserNotificationSettings' : IDL.Func(
        [],
        [UserNotificationSettings],
        ['query'],
      ),
    'getUserNotifications' : IDL.Func(
        [IDL.Text, IDL.Text],
        [GetUserNotificationsResponse],
        ['query'],
      ),
    'icrc10_supported_standards' : IDL.Func(
        [],
        [IDL.Vec(SupportedStandard)],
        ['query'],
      ),
    'icrc28_trusted_origins' : IDL.Func([], [Icrc28TrustedOriginsResponse], []),
    'isThereEnoughMemory' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationsAsRead' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'setMaxMemorySize' : IDL.Func([IDL.Nat], [Result_1], []),
    'updateNotificationSettings' : IDL.Func(
        [UserNotificationSettings],
        [Result],
        [],
      ),
  });
};

export const init: (args: { IDL: typeof IDL }) => IDL.Type[] = ({ IDL }) => {
  return [];
};
