/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/IcpLedger.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface AccountBalanceArgs {
    account: AccountIdentifier;
}
export type Operation = {
    __kind__: "Burn";
    Burn: {
        from: AccountIdentifier;
        amount: Tokens;
    };
} | {
    __kind__: "Mint";
    Mint: {
        to: AccountIdentifier;
        amount: Tokens;
    };
} | {
    __kind__: "Transfer";
    Transfer: {
        to: AccountIdentifier;
        fee: Tokens;
        from: AccountIdentifier;
        amount: Tokens;
    };
};
export interface Tokens {
    e8s: bigint;
}
export interface Archives {
    archives: Array<Archive>;
}
export interface BlockRange {
    /**
     * A prefix of the requested block range.
     * The index of the first block is equal to [GetBlocksArgs.from].
     * 
     * Note that the number of blocks might be less than the requested
     * [GetBlocksArgs.len] for various reasons, for example:
     * 
     * 1. The query might have hit the replica with an outdated state
     * that doesn't have the full block range yet.
     * 2. The requested range is too large to fit into a single reply.
     * 
     * NOTE: the list of blocks can be empty if:
     * 1. [GetBlocksArgs.len] was zero.
     * 2. [GetBlocksArgs.from] was larger than the last block known to the canister.
     */
    blocks: Array<Block>;
}
/**
 * An arbitrary number associated with a transaction.
 * The caller can set it in a `transfer` call as a correlation identifier.
 */
export type Memo = bigint;
export interface GetBlocksArgs {
    /**
     * The index of the first block to fetch.
     */
    start: BlockIndex;
    /**
     * Max number of blocks to fetch.
     */
    length: bigint;
}
/**
 * Sequence number of a block produced by the ledger.
 */
export type BlockIndex = bigint;
export interface Archive {
    canister_id: Principal;
}
export interface TransferArgs {
    /**
     * The destination account.
     * If the transfer is successful, the balance of this address increases by `amount`.
     */
    to: AccountIdentifier;
    /**
     * The amount that the caller pays for the transaction.
     * Must be 10000 e8s.
     */
    fee: Tokens;
    /**
     * Transaction memo.
     * See comments for the `Memo` type.
     */
    memo: Memo;
    /**
     * The subaccount from which the caller wants to transfer funds.
     * If null, the ledger uses the default (all zeros) subaccount to compute the source address.
     * See comments for the `SubAccount` type.
     */
    from_subaccount?: SubAccount;
    /**
     * The point in time when the caller created this request.
     * If null, the ledger uses current IC time as the timestamp.
     */
    created_at_time?: TimeStamp;
    /**
     * The amount that the caller wants to transfer to the destination address.
     */
    amount: Tokens;
}
export interface Transaction {
    memo: Memo;
    operation?: Operation;
    created_at_time: TimeStamp;
}
export type QueryArchiveResult = {
    __kind__: "Ok";
    /**
     * Successfully fetched zero or more blocks.
     */
    Ok: BlockRange;
} | {
    __kind__: "Err";
    /**
     * The [GetBlocksArgs] request was invalid.
     */
    Err: QueryArchiveError;
};
export interface QueryBlocksResponse {
    /**
     * System certificate for the hash of the latest block in the chain.
     * Only present if `query_blocks` is called in a non-replicated query context.
     */
    certificate?: Uint8Array;
    /**
     * List of blocks that were available in the ledger when it processed the call.
     * 
     * The blocks form a contiguous range, with the first block having index
     * [first_block_index] (see below), and the last block having index
     * [first_block_index] + len(blocks) - 1.
     * 
     * The block range can be an arbitrary sub-range of the originally requested range.
     */
    blocks: Array<Block>;
    /**
     * The total number of blocks in the chain.
     * If the chain length is positive, the index of the last block is `chain_len - 1`.
     */
    chain_length: bigint;
    /**
     * The index of the first block in "blocks".
     * If the blocks vector is empty, the exact value of this field is not specified.
     */
    first_block_index: BlockIndex;
    /**
     * Encoding of instructions for fetching archived blocks whose indices fall into the
     * requested range.
     * 
     * For each entry `e` in [archived_blocks], `[e.from, e.from + len)` is a sub-range
     * of the originally requested block range.
     */
    archived_blocks: Array<{
        /**
         * The function that should be called to fetch the archived blocks.
         * The range of the blocks accessible using this function is given by [from]
         * and [len] fields above.
         */
        callback: [Principal, string];
        /**
         * The index of the first archived block that can be fetched using the callback.
         */
        start: BlockIndex;
        /**
         * The number of blocks that can be fetch using the callback.
         */
        length: bigint;
    }>;
}
/**
 * AccountIdentifier is a 32-byte array.
 * The first 4 bytes is big-endian encoding of a CRC32 checksum of the last 28 bytes.
 */
export type AccountIdentifier = Uint8Array;
export type TransferResult = {
    __kind__: "Ok";
    Ok: BlockIndex;
} | {
    __kind__: "Err";
    Err: TransferError;
};
export interface TransferFeeArg {
}
/**
 * Subaccount is an arbitrary 32-byte byte array.
 * Ledger uses subaccounts to compute the source address, which enables one
 * principal to control multiple ledger accounts.
 */
export type SubAccount = Uint8Array;
export type QueryArchiveFn = (arg0: GetBlocksArgs) => Promise<QueryArchiveResult>;
export interface Block {
    transaction: Transaction;
    timestamp: TimeStamp;
    parent_hash?: Uint8Array;
}
export interface TransferFee {
    /**
     * The fee to pay to perform a transfer
     */
    transfer_fee: Tokens;
}
export type QueryArchiveError = {
    __kind__: "BadFirstBlockIndex";
    /**
     * [GetBlocksArgs.from] argument was smaller than the first block
     * served by the canister that received the request.
     */
    BadFirstBlockIndex: {
        requested_index: BlockIndex;
        first_valid_index: BlockIndex;
    };
} | {
    __kind__: "Other";
    /**
     * Reserved for future use.
     */
    Other: {
        error_message: string;
        error_code: bigint;
    };
};
export interface TimeStamp {
    timestamp_nanos: bigint;
}
export type TransferError = {
    __kind__: "TxTooOld";
    /**
     * The request is too old.
     * The ledger only accepts requests created within 24 hours window.
     * This is a non-recoverable error.
     */
    TxTooOld: {
        allowed_window_nanos: bigint;
    };
} | {
    __kind__: "BadFee";
    /**
     * The fee that the caller specified in the transfer request was not the one that ledger expects.
     * The caller can change the transfer fee to the `expected_fee` and retry the request.
     */
    BadFee: {
        expected_fee: Tokens;
    };
} | {
    __kind__: "TxDuplicate";
    /**
     * The ledger has already executed the request.
     * `duplicate_of` field is equal to the index of the block containing the original transaction.
     */
    TxDuplicate: {
        duplicate_of: BlockIndex;
    };
} | {
    __kind__: "TxCreatedInFuture";
    /**
     * The caller specified `created_at_time` that is too far in future.
     * The caller can retry the request later.
     */
    TxCreatedInFuture: null;
} | {
    __kind__: "InsufficientFunds";
    /**
     * The account specified by the caller doesn't have enough funds.
     */
    InsufficientFunds: {
        balance: Tokens;
    };
};
export interface IcpLedgerInterface {
    /**
     * Returns the amount of Tokens on the specified account.
     */
    account_balance(arg0: AccountBalanceArgs): Promise<Tokens>;
    /**
     * Returns the existing archive canisters information.
     */
    archives(): Promise<Archives>;
    /**
     * Returns token decimals.
     */
    decimals(): Promise<{
        decimals: number;
    }>;
    /**
     * Returns token name.
     */
    name(): Promise<{
        name: string;
    }>;
    /**
     * Queries blocks in the specified range.
     */
    query_blocks(arg0: GetBlocksArgs): Promise<QueryBlocksResponse>;
    /**
     * Returns token symbol.
     */
    symbol_(): Promise<{
        symbol: string;
    }>;
    /**
     * Transfers tokens from a subaccount of the caller to the destination address.
     * The source address is computed from the principal of the caller and the specified subaccount.
     * When successful, returns the index of the block containing the transaction.
     */
    transfer(arg0: TransferArgs): Promise<TransferResult>;
    /**
     * Returns the current transfer_fee.
     */
    transfer_fee(arg0: TransferFeeArg): Promise<TransferFee>;
}
import type { AccountIdentifier as _AccountIdentifier, Block as _Block, BlockIndex as _BlockIndex, Memo as _Memo, Operation as _Operation, QueryBlocksResponse as _QueryBlocksResponse, SubAccount as _SubAccount, TimeStamp as _TimeStamp, Tokens as _Tokens, Transaction as _Transaction, TransferArgs as _TransferArgs, TransferError as _TransferError, TransferResult as _TransferResult } from "./declarations/IcpLedger.did";
export class IcpLedger implements IcpLedgerInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async account_balance(arg0: AccountBalanceArgs): Promise<Tokens> {
        const result = await this.actor.account_balance(arg0);
        return result;
    }
    async archives(): Promise<Archives> {
        const result = await this.actor.archives();
        return result;
    }
    async decimals(): Promise<{
        decimals: number;
    }> {
        const result = await this.actor.decimals();
        return result;
    }
    async name(): Promise<{
        name: string;
    }> {
        const result = await this.actor.name();
        return result;
    }
    async query_blocks(arg0: GetBlocksArgs): Promise<QueryBlocksResponse> {
        const result = await this.actor.query_blocks(arg0);
        return from_candid_QueryBlocksResponse_n1(result);
    }
    async symbol_(): Promise<{
        symbol: string;
    }> {
        const result = await this.actor.symbol();
        return result;
    }
    async transfer(arg0: TransferArgs): Promise<TransferResult> {
        const result = await this.actor.transfer(to_candid_TransferArgs_n12(arg0));
        return from_candid_TransferResult_n14(result);
    }
    async transfer_fee(arg0: TransferFeeArg): Promise<TransferFee> {
        const result = await this.actor.transfer_fee(arg0);
        return result;
    }
}
function from_candid_Block_n5(value: _Block): Block {
    return from_candid_record_n6(value);
}
function from_candid_Operation_n10(value: _Operation): Operation {
    return from_candid_variant_n11(value);
}
function from_candid_QueryBlocksResponse_n1(value: _QueryBlocksResponse): QueryBlocksResponse {
    return from_candid_record_n2(value);
}
function from_candid_Transaction_n7(value: _Transaction): Transaction {
    return from_candid_record_n8(value);
}
function from_candid_TransferError_n16(value: _TransferError): TransferError {
    return from_candid_variant_n17(value);
}
function from_candid_TransferResult_n14(value: _TransferResult): TransferResult {
    return from_candid_variant_n15(value);
}
function from_candid_opt_n3(value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(value: [] | [_Operation]): Operation | null {
    return value.length === 0 ? null : from_candid_Operation_n10(value[0]);
}
function from_candid_record_n2(value: {
    certificate: [] | [Uint8Array];
    blocks: Array<_Block>;
    chain_length: bigint;
    first_block_index: _BlockIndex;
    archived_blocks: Array<{
        callback: [Principal, string];
        start: _BlockIndex;
        length: bigint;
    }>;
}): {
    certificate?: Uint8Array;
    blocks: Array<Block>;
    chain_length: bigint;
    first_block_index: BlockIndex;
    archived_blocks: Array<{
        callback: [Principal, string];
        start: BlockIndex;
        length: bigint;
    }>;
} {
    return {
        certificate: record_opt_to_undefined(from_candid_opt_n3(value.certificate)),
        blocks: from_candid_vec_n4(value.blocks),
        chain_length: value.chain_length,
        first_block_index: value.first_block_index,
        archived_blocks: value.archived_blocks
    };
}
function from_candid_record_n6(value: {
    transaction: _Transaction;
    timestamp: _TimeStamp;
    parent_hash: [] | [Uint8Array];
}): {
    transaction: Transaction;
    timestamp: TimeStamp;
    parent_hash?: Uint8Array;
} {
    return {
        transaction: from_candid_Transaction_n7(value.transaction),
        timestamp: value.timestamp,
        parent_hash: record_opt_to_undefined(from_candid_opt_n3(value.parent_hash))
    };
}
function from_candid_record_n8(value: {
    memo: _Memo;
    operation: [] | [_Operation];
    created_at_time: _TimeStamp;
}): {
    memo: Memo;
    operation?: Operation;
    created_at_time: TimeStamp;
} {
    return {
        memo: value.memo,
        operation: record_opt_to_undefined(from_candid_opt_n9(value.operation)),
        created_at_time: value.created_at_time
    };
}
function from_candid_variant_n11(value: {
    Burn: {
        from: _AccountIdentifier;
        amount: _Tokens;
    };
} | {
    Mint: {
        to: _AccountIdentifier;
        amount: _Tokens;
    };
} | {
    Transfer: {
        to: _AccountIdentifier;
        fee: _Tokens;
        from: _AccountIdentifier;
        amount: _Tokens;
    };
}): {
    __kind__: "Burn";
    Burn: {
        from: AccountIdentifier;
        amount: Tokens;
    };
} | {
    __kind__: "Mint";
    Mint: {
        to: AccountIdentifier;
        amount: Tokens;
    };
} | {
    __kind__: "Transfer";
    Transfer: {
        to: AccountIdentifier;
        fee: Tokens;
        from: AccountIdentifier;
        amount: Tokens;
    };
} {
    return "Burn" in value ? {
        __kind__: "Burn",
        Burn: value.Burn
    } : "Mint" in value ? {
        __kind__: "Mint",
        Mint: value.Mint
    } : "Transfer" in value ? {
        __kind__: "Transfer",
        Transfer: value.Transfer
    } : value;
}
function from_candid_variant_n15(value: {
    Ok: _BlockIndex;
} | {
    Err: _TransferError;
}): {
    __kind__: "Ok";
    Ok: BlockIndex;
} | {
    __kind__: "Err";
    Err: TransferError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_TransferError_n16(value.Err)
    } : value;
}
function from_candid_variant_n17(value: {
    TxTooOld: {
        allowed_window_nanos: bigint;
    };
} | {
    BadFee: {
        expected_fee: _Tokens;
    };
} | {
    TxDuplicate: {
        duplicate_of: _BlockIndex;
    };
} | {
    TxCreatedInFuture: null;
} | {
    InsufficientFunds: {
        balance: _Tokens;
    };
}): {
    __kind__: "TxTooOld";
    TxTooOld: {
        allowed_window_nanos: bigint;
    };
} | {
    __kind__: "BadFee";
    BadFee: {
        expected_fee: Tokens;
    };
} | {
    __kind__: "TxDuplicate";
    TxDuplicate: {
        duplicate_of: BlockIndex;
    };
} | {
    __kind__: "TxCreatedInFuture";
    TxCreatedInFuture: null;
} | {
    __kind__: "InsufficientFunds";
    InsufficientFunds: {
        balance: Tokens;
    };
} {
    return "TxTooOld" in value ? {
        __kind__: "TxTooOld",
        TxTooOld: value.TxTooOld
    } : "BadFee" in value ? {
        __kind__: "BadFee",
        BadFee: value.BadFee
    } : "TxDuplicate" in value ? {
        __kind__: "TxDuplicate",
        TxDuplicate: value.TxDuplicate
    } : "TxCreatedInFuture" in value ? {
        __kind__: "TxCreatedInFuture",
        TxCreatedInFuture: value.TxCreatedInFuture
    } : "InsufficientFunds" in value ? {
        __kind__: "InsufficientFunds",
        InsufficientFunds: value.InsufficientFunds
    } : value;
}
function from_candid_vec_n4(value: Array<_Block>): Array<Block> {
    return value.map((x)=>from_candid_Block_n5(x));
}
function to_candid_TransferArgs_n12(value: TransferArgs): _TransferArgs {
    return to_candid_record_n13(value);
}
function to_candid_record_n13(value: {
    to: AccountIdentifier;
    fee: Tokens;
    memo: Memo;
    from_subaccount?: SubAccount;
    created_at_time?: TimeStamp;
    amount: Tokens;
}): {
    to: _AccountIdentifier;
    fee: _Tokens;
    memo: _Memo;
    from_subaccount: [] | [_SubAccount];
    created_at_time: [] | [_TimeStamp];
    amount: _Tokens;
} {
    return {
        to: value.to,
        fee: value.fee,
        memo: value.memo,
        from_subaccount: value.from_subaccount ? candid_some(value.from_subaccount) : candid_none(),
        created_at_time: value.created_at_time ? candid_some(value.created_at_time) : candid_none(),
        amount: value.amount
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): IcpLedger {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new IcpLedger(actor);
}
