/* eslint-disable */
// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { Principal } from '@icp-sdk/core/principal';
import { IDL } from '@icp-sdk/core/candid';

export type AccountIdentifier = string;
export type AccountIdentifier__1 = string;
export type AssetHandle = string;
export type AssetId = number;
export type AssetType = { 'other' : string } |
  { 'canister' : { 'id' : AssetId, 'canister' : string } } |
  { 'direct' : Uint32Array };
export type Balance = bigint;
export interface BalanceRequest { 'token' : TokenIdentifier, 'user' : User }
export type BalanceResponse = { 'ok' : Balance } |
  { 'err' : CommonError__1 };
export type Balance__1 = bigint;
export type ChunkId = number;
export type CommonError = { 'InvalidToken' : TokenIdentifier } |
  { 'Other' : string };
export type CommonError__1 = { 'InvalidToken' : TokenIdentifier } |
  { 'Other' : string };
export interface EXTNFT {
  'acceptCycles' : ActorMethod<[], undefined>,
  'addAsset' : ActorMethod<
    [AssetHandle, number, string, string, string],
    undefined
  >,
  'addThumbnail' : ActorMethod<[AssetHandle, Uint8Array], undefined>,
  'adminKillHeartbeat' : ActorMethod<[], undefined>,
  'adminStartHeartbeat' : ActorMethod<[], undefined>,
  'allSettlements' : ActorMethod<
    [],
    Array<
      [
        TokenIndex,
        {
          'subaccount' : SubAccount__1,
          'seller' : Principal,
          'buyer' : AccountIdentifier__1,
          'price' : bigint,
        },
      ]
    >
  >,
  'availableCycles' : ActorMethod<[], bigint>,
  'balance' : ActorMethod<[BalanceRequest], BalanceResponse>,
  'bearer' : ActorMethod<[TokenIdentifier__1], Result_7>,
  'details' : ActorMethod<[TokenIdentifier__1], Result_10>,
  'ext_addAssetCanister' : ActorMethod<[], undefined>,
  'ext_assetAdd' : ActorMethod<
    [AssetHandle, string, string, AssetType, bigint],
    undefined
  >,
  'ext_assetExists' : ActorMethod<[AssetHandle], boolean>,
  'ext_assetFits' : ActorMethod<[boolean, bigint], boolean>,
  'ext_assetStream' : ActorMethod<[AssetHandle, Uint8Array, boolean], boolean>,
  'ext_balance' : ActorMethod<[BalanceRequest], BalanceResponse>,
  'ext_bearer' : ActorMethod<[TokenIdentifier__1], Result_7>,
  'ext_capInit' : ActorMethod<[], undefined>,
  'ext_expired' : ActorMethod<[], Array<[AccountIdentifier__1, SubAccount__1]>>,
  'ext_extensions' : ActorMethod<[], Array<Extension>>,
  'ext_marketplaceList' : ActorMethod<[ListRequest], Result_3>,
  'ext_marketplaceListings' : ActorMethod<
    [],
    Array<[TokenIndex, Listing, Metadata__1]>
  >,
  'ext_marketplacePurchase' : ActorMethod<
    [TokenIdentifier__1, bigint, AccountIdentifier__1],
    Result_9
  >,
  'ext_marketplaceSettle' : ActorMethod<[AccountIdentifier__1], Result_3>,
  'ext_marketplaceStats' : ActorMethod<
    [],
    [bigint, bigint, bigint, bigint, bigint, bigint, bigint]
  >,
  'ext_marketplaceTransactions' : ActorMethod<[], Array<Transaction>>,
  'ext_metadata' : ActorMethod<[TokenIdentifier__1], Result_8>,
  'ext_mint' : ActorMethod<
    [Array<[AccountIdentifier__1, Metadata__1]>],
    Uint32Array
  >,
  'ext_mint_helper' : ActorMethod<[Array<AccountIdentifier__1>], Uint32Array>,
  'ext_payments' : ActorMethod<[], Array<[AccountIdentifier__1, Payment]>>,
  'ext_saleClose' : ActorMethod<[], boolean>,
  'ext_saleCurrent' : ActorMethod<[], [] | [Sale]>,
  'ext_saleEnd' : ActorMethod<[], boolean>,
  'ext_saleOpen' : ActorMethod<
    [Array<SalePricingGroup>, SaleRemaining, Array<AccountIdentifier__1>],
    boolean
  >,
  'ext_salePause' : ActorMethod<[], boolean>,
  'ext_salePurchase' : ActorMethod<
    [bigint, bigint, bigint, AccountIdentifier__1],
    Result_5
  >,
  'ext_saleResume' : ActorMethod<[], boolean>,
  'ext_saleSettings' : ActorMethod<[AccountIdentifier__1], [] | [SaleDetails]>,
  'ext_saleSettle' : ActorMethod<[AccountIdentifier__1], Result_4>,
  'ext_saleTransactions' : ActorMethod<[], Array<SaleTransaction>>,
  'ext_saleUpdate' : ActorMethod<
    [
      [] | [Array<SalePricingGroup>],
      [] | [SaleRemaining],
      [] | [Array<AccountIdentifier__1>],
    ],
    boolean
  >,
  'ext_setCollectionMetadata' : ActorMethod<[string, string], undefined>,
  'ext_setMarketplaceOpen' : ActorMethod<[Time], undefined>,
  'ext_setRoyalty' : ActorMethod<
    [Array<[AccountIdentifier__1, bigint]>],
    undefined
  >,
  'ext_setSaleRoyalty' : ActorMethod<[AccountIdentifier__1], undefined>,
  'ext_transfer' : ActorMethod<[TransferRequest], TransferResponse>,
  'extdata_supply' : ActorMethod<[TokenIdentifier__1], Result_2>,
  'extensions' : ActorMethod<[], Array<Extension>>,
  'failedSales' : ActorMethod<[], Array<[AccountIdentifier__1, SubAccount__1]>>,
  'getAvailableToken' : ActorMethod<[], PremiumArticleSellingInformation>,
  'getMetadata' : ActorMethod<[], Array<[TokenIndex, MetadataLegacy]>>,
  'getRegistry' : ActorMethod<[], Array<[TokenIndex, AccountIdentifier__1]>>,
  'getTokens' : ActorMethod<[], Array<[TokenIndex, MetadataLegacy]>>,
  'heartbeat_assetCanisters' : ActorMethod<[], undefined>,
  'heartbeat_capEvents' : ActorMethod<[], undefined>,
  'heartbeat_disbursements' : ActorMethod<[], undefined>,
  'heartbeat_external' : ActorMethod<[], undefined>,
  'heartbeat_isRunning' : ActorMethod<[], boolean>,
  'heartbeat_paymentSettlements' : ActorMethod<[], undefined>,
  'heartbeat_pending' : ActorMethod<[], Array<[string, bigint]>>,
  'heartbeat_start' : ActorMethod<[], undefined>,
  'heartbeat_stop' : ActorMethod<[], undefined>,
  'http_request' : ActorMethod<[HttpRequest], HttpResponse>,
  'http_request_streaming_callback' : ActorMethod<
    [HttpStreamingCallbackToken],
    HttpStreamingCallbackResponse
  >,
  'http_request_update' : ActorMethod<[HttpRequest], HttpResponse>,
  'isHeartbeatRunning' : ActorMethod<[], boolean>,
  'list' : ActorMethod<[ListRequest], Result_3>,
  'listings' : ActorMethod<[], Array<[TokenIndex, Listing, MetadataLegacy]>>,
  'lock' : ActorMethod<
    [TokenIdentifier__1, bigint, AccountIdentifier__1, SubAccount__1],
    Result_7
  >,
  'marketplaceTransactionsAndTotalSupply' : ActorMethod<
    [],
    TransactionsAndSupply
  >,
  'metadata' : ActorMethod<[TokenIdentifier__1], Result_6>,
  'reserve' : ActorMethod<
    [bigint, bigint, AccountIdentifier__1, SubAccount__1],
    Result_5
  >,
  'retreive' : ActorMethod<[AccountIdentifier__1], Result_4>,
  'saleTransactions' : ActorMethod<[], Array<SaleTransaction>>,
  'salesSettings' : ActorMethod<[AccountIdentifier__1], SaleSettings>,
  'setConfigData' : ActorMethod<[InitNftCanisterData], Result_4>,
  'settle' : ActorMethod<[TokenIdentifier__1], Result_3>,
  'settlements' : ActorMethod<
    [],
    Array<[TokenIndex, AccountIdentifier__1, bigint]>
  >,
  'stats' : ActorMethod<
    [],
    [bigint, bigint, bigint, bigint, bigint, bigint, bigint]
  >,
  'supply' : ActorMethod<[TokenIdentifier__1], Result_2>,
  'tokens' : ActorMethod<[AccountIdentifier__1], Result_1>,
  'tokens_ext' : ActorMethod<[AccountIdentifier__1], Result>,
  'transactions' : ActorMethod<[], Array<Transaction>>,
  'transfer' : ActorMethod<[TransferRequest], TransferResponse>,
}
export type Extension = string;
export type HeaderField = [string, string];
export interface HttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<HeaderField>,
}
export interface HttpResponse {
  'body' : Uint8Array,
  'headers' : Array<HeaderField>,
  'upgrade' : boolean,
  'streaming_strategy' : [] | [HttpStreamingStrategy],
  'status_code' : number,
}
export interface HttpStreamingCallbackResponse {
  'token' : [] | [HttpStreamingCallbackToken],
  'body' : Uint8Array,
}
export interface HttpStreamingCallbackToken {
  'key' : string,
  'sha256' : [] | [Uint8Array],
  'index' : bigint,
  'content_encoding' : string,
}
export type HttpStreamingStrategy = {
    'Callback' : {
      'token' : HttpStreamingCallbackToken,
      'callback' : [Principal, string],
    }
  };
export interface InitNftCanisterData {
  'thumbnail' : string,
  'initialMintingAddresses' : Array<string>,
  'metadata' : Metadata,
  'writerPrincipal' : Principal,
  'admins' : Array<Principal>,
  'icpPrice' : bigint,
  'royalty' : Array<[string, bigint]>,
  'maxSupply' : bigint,
  'marketplaceOpen' : Time__1,
  'collectionName' : string,
  'postId' : string,
}
export interface ListRequest {
  'token' : TokenIdentifier__1,
  'from_subaccount' : [] | [SubAccount__1],
  'price' : [] | [bigint],
}
export interface Listing {
  'locked' : [] | [Time],
  'seller' : Principal,
  'price' : bigint,
}
export type Memo = Uint8Array;
export type Metadata = {
    'fungible' : {
      'decimals' : number,
      'metadata' : [] | [MetadataContainer],
      'name' : string,
      'symbol' : string,
    }
  } |
  {
    'nonfungible' : {
      'thumbnail' : string,
      'asset' : string,
      'metadata' : [] | [MetadataContainer],
      'name' : string,
    }
  };
export type MetadataContainer = { 'blob' : Uint8Array } |
  { 'data' : Array<MetadataValue> } |
  { 'json' : string };
export type MetadataContainer__1 = { 'blob' : Uint8Array } |
  { 'data' : Array<MetadataValue__1> } |
  { 'json' : string };
export type MetadataLegacy = {
    'fungible' : {
      'decimals' : number,
      'metadata' : [] | [Uint8Array],
      'name' : string,
      'symbol' : string,
    }
  } |
  { 'nonfungible' : { 'metadata' : [] | [Uint8Array] } };
export type MetadataValue = [
  string,
  { 'nat' : bigint } |
    { 'blob' : Uint8Array } |
    { 'nat8' : number } |
    { 'text' : string },
];
export type MetadataValue__1 = [
  string,
  { 'nat' : bigint } |
    { 'blob' : Uint8Array } |
    { 'nat8' : number } |
    { 'text' : string },
];
export type Metadata__1 = {
    'fungible' : {
      'decimals' : number,
      'metadata' : [] | [MetadataContainer__1],
      'name' : string,
      'symbol' : string,
    }
  } |
  {
    'nonfungible' : {
      'thumbnail' : string,
      'asset' : string,
      'metadata' : [] | [MetadataContainer__1],
      'name' : string,
    }
  };
export interface Payment {
  'expires' : Time,
  'subaccount' : SubAccount__1,
  'payer' : AccountIdentifier__1,
  'amount' : bigint,
  'purchase' : PaymentType,
}
export type PaymentType = { 'nft' : TokenIndex } |
  { 'nfts' : Uint32Array } |
  { 'sale' : bigint };
export interface PremiumArticleSellingInformation {
  'tokenSenderAccounts' : Array<AccountIdentifier__1>,
  'currentSupply' : bigint,
  'availableTokenIndex' : [] | [TokenIndex],
  'price' : bigint,
  'maxSupply' : bigint,
  'sellerAccount' : AccountIdentifier__1,
  'postId' : string,
}
export type Result = {
    'ok' : Array<[TokenIndex, [] | [Listing], [] | [Uint8Array]]>
  } |
  { 'err' : CommonError };
export type Result_1 = { 'ok' : Uint32Array } |
  { 'err' : CommonError };
export type Result_10 = { 'ok' : [AccountIdentifier__1, [] | [Listing]] } |
  { 'err' : CommonError };
export type Result_2 = { 'ok' : Balance__1 } |
  { 'err' : CommonError };
export type Result_3 = { 'ok' : null } |
  { 'err' : CommonError };
export type Result_4 = { 'ok' : null } |
  { 'err' : string };
export type Result_5 = { 'ok' : [AccountIdentifier__1, bigint] } |
  { 'err' : string };
export type Result_6 = { 'ok' : MetadataLegacy } |
  { 'err' : CommonError };
export type Result_7 = { 'ok' : AccountIdentifier__1 } |
  { 'err' : CommonError };
export type Result_8 = { 'ok' : Metadata__1 } |
  { 'err' : CommonError };
export type Result_9 = { 'ok' : [AccountIdentifier__1, bigint] } |
  { 'err' : CommonError };
export interface Sale {
  'end' : Time,
  'groups' : Array<SalePricingGroup>,
  'start' : Time,
  'quantity' : bigint,
  'remaining' : SaleRemaining,
}
export interface SaleDetailGroup {
  'id' : bigint,
  'end' : Time,
  'name' : string,
  'available' : boolean,
  'pricing' : Array<[bigint, bigint]>,
  'start' : Time,
}
export interface SaleDetails {
  'end' : Time,
  'groups' : Array<SaleDetailGroup>,
  'start' : Time,
  'quantity' : bigint,
  'remaining' : bigint,
}
export interface SalePricingGroup {
  'end' : Time,
  'participants' : Array<AccountIdentifier__1>,
  'name' : string,
  'limit' : [bigint, bigint],
  'pricing' : Array<[bigint, bigint]>,
  'start' : Time,
}
export type SaleRemaining = { 'retain' : null } |
  { 'burn' : null } |
  { 'send' : AccountIdentifier__1 };
export interface SaleSettings {
  'startTime' : Time,
  'whitelist' : boolean,
  'totalToSell' : bigint,
  'sold' : bigint,
  'bulkPricing' : Array<[bigint, bigint]>,
  'whitelistTime' : Time,
  'salePrice' : bigint,
  'remaining' : bigint,
  'price' : bigint,
}
export interface SaleTransaction {
  'time' : Time,
  'seller' : Principal,
  'tokens' : Uint32Array,
  'buyer' : AccountIdentifier__1,
  'price' : bigint,
}
export type SubAccount = Uint8Array;
export type SubAccount__1 = Uint8Array;
export type Time = bigint;
export type Time__1 = bigint;
export type TokenIdentifier = string;
export type TokenIdentifier__1 = string;
export type TokenIndex = number;
export interface Transaction {
  'token' : TokenIndex,
  'time' : Time,
  'seller' : AccountIdentifier__1,
  'buyer' : AccountIdentifier__1,
  'price' : bigint,
}
export interface TransactionsAndSupply {
  'tokenSenderAccounts' : Array<AccountIdentifier__1>,
  'initialSupply' : bigint,
  'currentSupply' : bigint,
  'icpPrice' : bigint,
  'transactions' : Array<Transaction>,
  'maxSupply' : bigint,
  'sellerAccount' : AccountIdentifier__1,
  'postId' : string,
}
export interface TransferRequest {
  'to' : User,
  'token' : TokenIdentifier,
  'notify' : boolean,
  'from' : User,
  'memo' : Memo,
  'subaccount' : [] | [SubAccount],
  'amount' : Balance,
}
export type TransferResponse = { 'ok' : Balance } |
  {
    'err' : { 'CannotNotify' : AccountIdentifier } |
      { 'InsufficientBalance' : null } |
      { 'InvalidToken' : TokenIdentifier } |
      { 'Rejected' : null } |
      { 'Unauthorized' : AccountIdentifier } |
      { 'Other' : string }
  };
export type User = { 'principal' : Principal } |
  { 'address' : AccountIdentifier };
export interface _SERVICE extends EXTNFT {}
export const idlFactory: IDL.InterfaceFactory = ({ IDL }) => {
  const AssetHandle = IDL.Text;
  const TokenIndex = IDL.Nat32;
  const SubAccount__1 = IDL.Vec(IDL.Nat8);
  const AccountIdentifier__1 = IDL.Text;
  const TokenIdentifier = IDL.Text;
  const AccountIdentifier = IDL.Text;
  const User = IDL.Variant({
    'principal' : IDL.Principal,
    'address' : AccountIdentifier,
  });
  const BalanceRequest = IDL.Record({
    'token' : TokenIdentifier,
    'user' : User,
  });
  const Balance = IDL.Nat;
  const CommonError__1 = IDL.Variant({
    'InvalidToken' : TokenIdentifier,
    'Other' : IDL.Text,
  });
  const BalanceResponse = IDL.Variant({
    'ok' : Balance,
    'err' : CommonError__1,
  });
  const TokenIdentifier__1 = IDL.Text;
  const CommonError = IDL.Variant({
    'InvalidToken' : TokenIdentifier,
    'Other' : IDL.Text,
  });
  const Result_7 = IDL.Variant({
    'ok' : AccountIdentifier__1,
    'err' : CommonError,
  });
  const Time = IDL.Int;
  const Listing = IDL.Record({
    'locked' : IDL.Opt(Time),
    'seller' : IDL.Principal,
    'price' : IDL.Nat64,
  });
  const Result_10 = IDL.Variant({
    'ok' : IDL.Tuple(AccountIdentifier__1, IDL.Opt(Listing)),
    'err' : CommonError,
  });
  const AssetId = IDL.Nat32;
  const ChunkId = IDL.Nat32;
  const AssetType = IDL.Variant({
    'other' : IDL.Text,
    'canister' : IDL.Record({ 'id' : AssetId, 'canister' : IDL.Text }),
    'direct' : IDL.Vec(ChunkId),
  });
  const Extension = IDL.Text;
  const ListRequest = IDL.Record({
    'token' : TokenIdentifier__1,
    'from_subaccount' : IDL.Opt(SubAccount__1),
    'price' : IDL.Opt(IDL.Nat64),
  });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : CommonError });
  const MetadataValue__1 = IDL.Tuple(
    IDL.Text,
    IDL.Variant({
      'nat' : IDL.Nat,
      'blob' : IDL.Vec(IDL.Nat8),
      'nat8' : IDL.Nat8,
      'text' : IDL.Text,
    }),
  );
  const MetadataContainer__1 = IDL.Variant({
    'blob' : IDL.Vec(IDL.Nat8),
    'data' : IDL.Vec(MetadataValue__1),
    'json' : IDL.Text,
  });
  const Metadata__1 = IDL.Variant({
    'fungible' : IDL.Record({
      'decimals' : IDL.Nat8,
      'metadata' : IDL.Opt(MetadataContainer__1),
      'name' : IDL.Text,
      'symbol' : IDL.Text,
    }),
    'nonfungible' : IDL.Record({
      'thumbnail' : IDL.Text,
      'asset' : IDL.Text,
      'metadata' : IDL.Opt(MetadataContainer__1),
      'name' : IDL.Text,
    }),
  });
  const Result_9 = IDL.Variant({
    'ok' : IDL.Tuple(AccountIdentifier__1, IDL.Nat64),
    'err' : CommonError,
  });
  const Transaction = IDL.Record({
    'token' : TokenIndex,
    'time' : Time,
    'seller' : AccountIdentifier__1,
    'buyer' : AccountIdentifier__1,
    'price' : IDL.Nat64,
  });
  const Result_8 = IDL.Variant({ 'ok' : Metadata__1, 'err' : CommonError });
  const PaymentType = IDL.Variant({
    'nft' : TokenIndex,
    'nfts' : IDL.Vec(TokenIndex),
    'sale' : IDL.Nat64,
  });
  const Payment = IDL.Record({
    'expires' : Time,
    'subaccount' : SubAccount__1,
    'payer' : AccountIdentifier__1,
    'amount' : IDL.Nat64,
    'purchase' : PaymentType,
  });
  const SalePricingGroup = IDL.Record({
    'end' : Time,
    'participants' : IDL.Vec(AccountIdentifier__1),
    'name' : IDL.Text,
    'limit' : IDL.Tuple(IDL.Nat64, IDL.Nat64),
    'pricing' : IDL.Vec(IDL.Tuple(IDL.Nat64, IDL.Nat64)),
    'start' : Time,
  });
  const SaleRemaining = IDL.Variant({
    'retain' : IDL.Null,
    'burn' : IDL.Null,
    'send' : AccountIdentifier__1,
  });
  const Sale = IDL.Record({
    'end' : Time,
    'groups' : IDL.Vec(SalePricingGroup),
    'start' : Time,
    'quantity' : IDL.Nat,
    'remaining' : SaleRemaining,
  });
  const Result_5 = IDL.Variant({
    'ok' : IDL.Tuple(AccountIdentifier__1, IDL.Nat64),
    'err' : IDL.Text,
  });
  const SaleDetailGroup = IDL.Record({
    'id' : IDL.Nat,
    'end' : Time,
    'name' : IDL.Text,
    'available' : IDL.Bool,
    'pricing' : IDL.Vec(IDL.Tuple(IDL.Nat64, IDL.Nat64)),
    'start' : Time,
  });
  const SaleDetails = IDL.Record({
    'end' : Time,
    'groups' : IDL.Vec(SaleDetailGroup),
    'start' : Time,
    'quantity' : IDL.Nat,
    'remaining' : IDL.Nat,
  });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const SaleTransaction = IDL.Record({
    'time' : Time,
    'seller' : IDL.Principal,
    'tokens' : IDL.Vec(TokenIndex),
    'buyer' : AccountIdentifier__1,
    'price' : IDL.Nat64,
  });
  const Memo = IDL.Vec(IDL.Nat8);
  const SubAccount = IDL.Vec(IDL.Nat8);
  const TransferRequest = IDL.Record({
    'to' : User,
    'token' : TokenIdentifier,
    'notify' : IDL.Bool,
    'from' : User,
    'memo' : Memo,
    'subaccount' : IDL.Opt(SubAccount),
    'amount' : Balance,
  });
  const TransferResponse = IDL.Variant({
    'ok' : Balance,
    'err' : IDL.Variant({
      'CannotNotify' : AccountIdentifier,
      'InsufficientBalance' : IDL.Null,
      'InvalidToken' : TokenIdentifier,
      'Rejected' : IDL.Null,
      'Unauthorized' : AccountIdentifier,
      'Other' : IDL.Text,
    }),
  });
  const Balance__1 = IDL.Nat;
  const Result_2 = IDL.Variant({ 'ok' : Balance__1, 'err' : CommonError });
  const PremiumArticleSellingInformation = IDL.Record({
    'tokenSenderAccounts' : IDL.Vec(AccountIdentifier__1),
    'currentSupply' : IDL.Nat,
    'availableTokenIndex' : IDL.Opt(TokenIndex),
    'price' : IDL.Nat,
    'maxSupply' : IDL.Nat,
    'sellerAccount' : AccountIdentifier__1,
    'postId' : IDL.Text,
  });
  const MetadataLegacy = IDL.Variant({
    'fungible' : IDL.Record({
      'decimals' : IDL.Nat8,
      'metadata' : IDL.Opt(IDL.Vec(IDL.Nat8)),
      'name' : IDL.Text,
      'symbol' : IDL.Text,
    }),
    'nonfungible' : IDL.Record({ 'metadata' : IDL.Opt(IDL.Vec(IDL.Nat8)) }),
  });
  const HeaderField = IDL.Tuple(IDL.Text, IDL.Text);
  const HttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HeaderField),
  });
  const HttpStreamingCallbackToken = IDL.Record({
    'key' : IDL.Text,
    'sha256' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'index' : IDL.Nat,
    'content_encoding' : IDL.Text,
  });
  const HttpStreamingCallbackResponse = IDL.Record({
    'token' : IDL.Opt(HttpStreamingCallbackToken),
    'body' : IDL.Vec(IDL.Nat8),
  });
  const HttpStreamingStrategy = IDL.Variant({
    'Callback' : IDL.Record({
      'token' : HttpStreamingCallbackToken,
      'callback' : IDL.Func(
          [HttpStreamingCallbackToken],
          [HttpStreamingCallbackResponse],
          ['query'],
        ),
    }),
  });
  const HttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HeaderField),
    'upgrade' : IDL.Bool,
    'streaming_strategy' : IDL.Opt(HttpStreamingStrategy),
    'status_code' : IDL.Nat16,
  });
  const TransactionsAndSupply = IDL.Record({
    'tokenSenderAccounts' : IDL.Vec(AccountIdentifier__1),
    'initialSupply' : IDL.Nat,
    'currentSupply' : IDL.Nat,
    'icpPrice' : IDL.Nat,
    'transactions' : IDL.Vec(Transaction),
    'maxSupply' : IDL.Nat,
    'sellerAccount' : AccountIdentifier__1,
    'postId' : IDL.Text,
  });
  const Result_6 = IDL.Variant({ 'ok' : MetadataLegacy, 'err' : CommonError });
  const SaleSettings = IDL.Record({
    'startTime' : Time,
    'whitelist' : IDL.Bool,
    'totalToSell' : IDL.Nat,
    'sold' : IDL.Nat,
    'bulkPricing' : IDL.Vec(IDL.Tuple(IDL.Nat64, IDL.Nat64)),
    'whitelistTime' : Time,
    'salePrice' : IDL.Nat64,
    'remaining' : IDL.Nat,
    'price' : IDL.Nat64,
  });
  const MetadataValue = IDL.Tuple(
    IDL.Text,
    IDL.Variant({
      'nat' : IDL.Nat,
      'blob' : IDL.Vec(IDL.Nat8),
      'nat8' : IDL.Nat8,
      'text' : IDL.Text,
    }),
  );
  const MetadataContainer = IDL.Variant({
    'blob' : IDL.Vec(IDL.Nat8),
    'data' : IDL.Vec(MetadataValue),
    'json' : IDL.Text,
  });
  const Metadata = IDL.Variant({
    'fungible' : IDL.Record({
      'decimals' : IDL.Nat8,
      'metadata' : IDL.Opt(MetadataContainer),
      'name' : IDL.Text,
      'symbol' : IDL.Text,
    }),
    'nonfungible' : IDL.Record({
      'thumbnail' : IDL.Text,
      'asset' : IDL.Text,
      'metadata' : IDL.Opt(MetadataContainer),
      'name' : IDL.Text,
    }),
  });
  const Time__1 = IDL.Int;
  const InitNftCanisterData = IDL.Record({
    'thumbnail' : IDL.Text,
    'initialMintingAddresses' : IDL.Vec(IDL.Text),
    'metadata' : Metadata,
    'writerPrincipal' : IDL.Principal,
    'admins' : IDL.Vec(IDL.Principal),
    'icpPrice' : IDL.Nat,
    'royalty' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat64)),
    'maxSupply' : IDL.Nat,
    'marketplaceOpen' : Time__1,
    'collectionName' : IDL.Text,
    'postId' : IDL.Text,
  });
  const Result_1 = IDL.Variant({
    'ok' : IDL.Vec(TokenIndex),
    'err' : CommonError,
  });
  const Result = IDL.Variant({
    'ok' : IDL.Vec(
      IDL.Tuple(TokenIndex, IDL.Opt(Listing), IDL.Opt(IDL.Vec(IDL.Nat8)))
    ),
    'err' : CommonError,
  });
  const EXTNFT = IDL.Service({
    'acceptCycles' : IDL.Func([], [], []),
    'addAsset' : IDL.Func(
        [AssetHandle, IDL.Nat32, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addThumbnail' : IDL.Func([AssetHandle, IDL.Vec(IDL.Nat8)], [], []),
    'adminKillHeartbeat' : IDL.Func([], [], []),
    'adminStartHeartbeat' : IDL.Func([], [], []),
    'allSettlements' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              TokenIndex,
              IDL.Record({
                'subaccount' : SubAccount__1,
                'seller' : IDL.Principal,
                'buyer' : AccountIdentifier__1,
                'price' : IDL.Nat64,
              }),
            )
          ),
        ],
        ['query'],
      ),
    'availableCycles' : IDL.Func([], [IDL.Nat], ['query']),
    'balance' : IDL.Func([BalanceRequest], [BalanceResponse], ['query']),
    'bearer' : IDL.Func([TokenIdentifier__1], [Result_7], ['query']),
    'details' : IDL.Func([TokenIdentifier__1], [Result_10], ['query']),
    'ext_addAssetCanister' : IDL.Func([], [], []),
    'ext_assetAdd' : IDL.Func(
        [AssetHandle, IDL.Text, IDL.Text, AssetType, IDL.Nat],
        [],
        [],
      ),
    'ext_assetExists' : IDL.Func([AssetHandle], [IDL.Bool], ['query']),
    'ext_assetFits' : IDL.Func([IDL.Bool, IDL.Nat], [IDL.Bool], ['query']),
    'ext_assetStream' : IDL.Func(
        [AssetHandle, IDL.Vec(IDL.Nat8), IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'ext_balance' : IDL.Func([BalanceRequest], [BalanceResponse], ['query']),
    'ext_bearer' : IDL.Func([TokenIdentifier__1], [Result_7], ['query']),
    'ext_capInit' : IDL.Func([], [], []),
    'ext_expired' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(AccountIdentifier__1, SubAccount__1))],
        ['query'],
      ),
    'ext_extensions' : IDL.Func([], [IDL.Vec(Extension)], ['query']),
    'ext_marketplaceList' : IDL.Func([ListRequest], [Result_3], []),
    'ext_marketplaceListings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TokenIndex, Listing, Metadata__1))],
        ['query'],
      ),
    'ext_marketplacePurchase' : IDL.Func(
        [TokenIdentifier__1, IDL.Nat64, AccountIdentifier__1],
        [Result_9],
        [],
      ),
    'ext_marketplaceSettle' : IDL.Func([AccountIdentifier__1], [Result_3], []),
    'ext_marketplaceStats' : IDL.Func(
        [],
        [IDL.Nat64, IDL.Nat64, IDL.Nat64, IDL.Nat64, IDL.Nat, IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'ext_marketplaceTransactions' : IDL.Func(
        [],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'ext_metadata' : IDL.Func([TokenIdentifier__1], [Result_8], ['query']),
    'ext_mint' : IDL.Func(
        [IDL.Vec(IDL.Tuple(AccountIdentifier__1, Metadata__1))],
        [IDL.Vec(TokenIndex)],
        [],
      ),
    'ext_mint_helper' : IDL.Func(
        [IDL.Vec(AccountIdentifier__1)],
        [IDL.Vec(TokenIndex)],
        [],
      ),
    'ext_payments' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(AccountIdentifier__1, Payment))],
        ['query'],
      ),
    'ext_saleClose' : IDL.Func([], [IDL.Bool], []),
    'ext_saleCurrent' : IDL.Func([], [IDL.Opt(Sale)], ['query']),
    'ext_saleEnd' : IDL.Func([], [IDL.Bool], []),
    'ext_saleOpen' : IDL.Func(
        [
          IDL.Vec(SalePricingGroup),
          SaleRemaining,
          IDL.Vec(AccountIdentifier__1),
        ],
        [IDL.Bool],
        [],
      ),
    'ext_salePause' : IDL.Func([], [IDL.Bool], []),
    'ext_salePurchase' : IDL.Func(
        [IDL.Nat, IDL.Nat64, IDL.Nat64, AccountIdentifier__1],
        [Result_5],
        [],
      ),
    'ext_saleResume' : IDL.Func([], [IDL.Bool], []),
    'ext_saleSettings' : IDL.Func(
        [AccountIdentifier__1],
        [IDL.Opt(SaleDetails)],
        ['query'],
      ),
    'ext_saleSettle' : IDL.Func([AccountIdentifier__1], [Result_4], []),
    'ext_saleTransactions' : IDL.Func(
        [],
        [IDL.Vec(SaleTransaction)],
        ['query'],
      ),
    'ext_saleUpdate' : IDL.Func(
        [
          IDL.Opt(IDL.Vec(SalePricingGroup)),
          IDL.Opt(SaleRemaining),
          IDL.Opt(IDL.Vec(AccountIdentifier__1)),
        ],
        [IDL.Bool],
        [],
      ),
    'ext_setCollectionMetadata' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'ext_setMarketplaceOpen' : IDL.Func([Time], [], []),
    'ext_setRoyalty' : IDL.Func(
        [IDL.Vec(IDL.Tuple(AccountIdentifier__1, IDL.Nat64))],
        [],
        [],
      ),
    'ext_setSaleRoyalty' : IDL.Func([AccountIdentifier__1], [], ['oneway']),
    'ext_transfer' : IDL.Func([TransferRequest], [TransferResponse], []),
    'extdata_supply' : IDL.Func([TokenIdentifier__1], [Result_2], ['query']),
    'extensions' : IDL.Func([], [IDL.Vec(Extension)], ['query']),
    'failedSales' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(AccountIdentifier__1, SubAccount__1))],
        ['query'],
      ),
    'getAvailableToken' : IDL.Func(
        [],
        [PremiumArticleSellingInformation],
        ['query'],
      ),
    'getMetadata' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TokenIndex, MetadataLegacy))],
        ['query'],
      ),
    'getRegistry' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TokenIndex, AccountIdentifier__1))],
        ['query'],
      ),
    'getTokens' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TokenIndex, MetadataLegacy))],
        ['query'],
      ),
    'heartbeat_assetCanisters' : IDL.Func([], [], []),
    'heartbeat_capEvents' : IDL.Func([], [], []),
    'heartbeat_disbursements' : IDL.Func([], [], []),
    'heartbeat_external' : IDL.Func([], [], []),
    'heartbeat_isRunning' : IDL.Func([], [IDL.Bool], ['query']),
    'heartbeat_paymentSettlements' : IDL.Func([], [], []),
    'heartbeat_pending' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'heartbeat_start' : IDL.Func([], [], []),
    'heartbeat_stop' : IDL.Func([], [], []),
    'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
    'http_request_streaming_callback' : IDL.Func(
        [HttpStreamingCallbackToken],
        [HttpStreamingCallbackResponse],
        ['query'],
      ),
    'http_request_update' : IDL.Func([HttpRequest], [HttpResponse], []),
    'isHeartbeatRunning' : IDL.Func([], [IDL.Bool], ['query']),
    'list' : IDL.Func([ListRequest], [Result_3], []),
    'listings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TokenIndex, Listing, MetadataLegacy))],
        ['query'],
      ),
    'lock' : IDL.Func(
        [TokenIdentifier__1, IDL.Nat64, AccountIdentifier__1, SubAccount__1],
        [Result_7],
        [],
      ),
    'marketplaceTransactionsAndTotalSupply' : IDL.Func(
        [],
        [TransactionsAndSupply],
        ['query'],
      ),
    'metadata' : IDL.Func([TokenIdentifier__1], [Result_6], ['query']),
    'reserve' : IDL.Func(
        [IDL.Nat64, IDL.Nat64, AccountIdentifier__1, SubAccount__1],
        [Result_5],
        [],
      ),
    'retreive' : IDL.Func([AccountIdentifier__1], [Result_4], []),
    'saleTransactions' : IDL.Func([], [IDL.Vec(SaleTransaction)], ['query']),
    'salesSettings' : IDL.Func(
        [AccountIdentifier__1],
        [SaleSettings],
        ['query'],
      ),
    'setConfigData' : IDL.Func([InitNftCanisterData], [Result_4], []),
    'settle' : IDL.Func([TokenIdentifier__1], [Result_3], []),
    'settlements' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TokenIndex, AccountIdentifier__1, IDL.Nat64))],
        ['query'],
      ),
    'stats' : IDL.Func(
        [],
        [IDL.Nat64, IDL.Nat64, IDL.Nat64, IDL.Nat64, IDL.Nat, IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'supply' : IDL.Func([TokenIdentifier__1], [Result_2], ['query']),
    'tokens' : IDL.Func([AccountIdentifier__1], [Result_1], ['query']),
    'tokens_ext' : IDL.Func([AccountIdentifier__1], [Result], ['query']),
    'transactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'transfer' : IDL.Func([TransferRequest], [TransferResponse], []),
  });
  
  return EXTNFT;
};

export const init: (args: { IDL: typeof IDL }) => IDL.Type[] = ({ IDL }) => {
  return [];
};
