/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/IcpIndex.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export type Operation = {
    __kind__: "Approve";
    Approve: {
        fee: Tokens;
        from: string;
        allowance: Tokens;
        expires_at?: TimeStamp;
        spender: string;
    };
} | {
    __kind__: "Burn";
    Burn: {
        from: string;
        amount: Tokens;
    };
} | {
    __kind__: "Mint";
    Mint: {
        to: string;
        amount: Tokens;
    };
} | {
    __kind__: "Transfer";
    Transfer: {
        to: string;
        fee: Tokens;
        from: string;
        amount: Tokens;
    };
} | {
    __kind__: "TransferFrom";
    TransferFrom: {
        to: string;
        fee: Tokens;
        from: string;
        amount: Tokens;
        spender: string;
    };
};
export interface Account {
    owner: Principal;
    subaccount?: Uint8Array;
}
export interface GetAccountIdentifierTransactionsArgs {
    max_results: bigint;
    start?: bigint;
    account_identifier: string;
}
export interface GetBlocksResponse {
    blocks: Array<Uint8Array>;
    chain_length: bigint;
}
export interface TransactionWithId {
    id: bigint;
    transaction: Transaction;
}
export interface GetBlocksRequest {
    start: bigint;
    length: bigint;
}
export interface GetAccountIdentifierTransactionsError {
    message: string;
}
export interface Transaction {
    memo: bigint;
    icrc1_memo?: Uint8Array;
    operation: Operation;
    created_at_time?: TimeStamp;
}
export interface GetAccountTransactionsArgs {
    /**
     * Maximum number of transactions to fetch.
     */
    max_results: bigint;
    /**
     * The txid of the last transaction seen by the client.
     * If None then the results will start from the most recent
     * txid.
     */
    start?: bigint;
    account: Account;
}
export type GetAccountIdentifierTransactionsResult = {
    __kind__: "Ok";
    Ok: GetAccountIdentifierTransactionsResponse;
} | {
    __kind__: "Err";
    Err: GetAccountIdentifierTransactionsError;
};
export interface HttpResponse {
    body: Uint8Array;
    headers: Array<[string, string]>;
    status_code: number;
}
export interface GetAccountIdentifierTransactionsResponse {
    balance: bigint;
    transactions: Array<TransactionWithId>;
    oldest_tx_id?: bigint;
}
export interface Status {
    num_blocks_synced: bigint;
}
export interface InitArg {
    ledger_id: Principal;
}
export interface HttpRequest {
    url: string;
    method: string;
    body: Uint8Array;
    headers: Array<[string, string]>;
}
export interface TimeStamp {
    timestamp_nanos: bigint;
}
export interface Tokens {
    e8s: bigint;
}
export interface IcpIndexInterface {
    get_account_identifier_balance(arg0: string): Promise<bigint>;
    get_account_identifier_transactions(arg0: GetAccountIdentifierTransactionsArgs): Promise<GetAccountIdentifierTransactionsResult>;
    get_account_transactions(arg0: GetAccountTransactionsArgs): Promise<GetAccountIdentifierTransactionsResult>;
    get_blocks(arg0: GetBlocksRequest): Promise<GetBlocksResponse>;
    http_request(arg0: HttpRequest): Promise<HttpResponse>;
    icrc1_balance_of(arg0: Account): Promise<bigint>;
    ledger_id(): Promise<Principal>;
    status(): Promise<Status>;
}
import type { Account as _Account, GetAccountIdentifierTransactionsArgs as _GetAccountIdentifierTransactionsArgs, GetAccountIdentifierTransactionsError as _GetAccountIdentifierTransactionsError, GetAccountIdentifierTransactionsResponse as _GetAccountIdentifierTransactionsResponse, GetAccountIdentifierTransactionsResult as _GetAccountIdentifierTransactionsResult, GetAccountTransactionsArgs as _GetAccountTransactionsArgs, Operation as _Operation, TimeStamp as _TimeStamp, Tokens as _Tokens, Transaction as _Transaction, TransactionWithId as _TransactionWithId } from "./declarations/IcpIndex.did";
export class IcpIndex implements IcpIndexInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async get_account_identifier_balance(arg0: string): Promise<bigint> {
        const result = await this.actor.get_account_identifier_balance(arg0);
        return result;
    }
    async get_account_identifier_transactions(arg0: GetAccountIdentifierTransactionsArgs): Promise<GetAccountIdentifierTransactionsResult> {
        const result = await this.actor.get_account_identifier_transactions(to_candid_GetAccountIdentifierTransactionsArgs_n1(arg0));
        return from_candid_GetAccountIdentifierTransactionsResult_n3(result);
    }
    async get_account_transactions(arg0: GetAccountTransactionsArgs): Promise<GetAccountIdentifierTransactionsResult> {
        const result = await this.actor.get_account_transactions(to_candid_GetAccountTransactionsArgs_n18(arg0));
        return from_candid_GetAccountIdentifierTransactionsResult_n3(result);
    }
    async get_blocks(arg0: GetBlocksRequest): Promise<GetBlocksResponse> {
        const result = await this.actor.get_blocks(arg0);
        return result;
    }
    async http_request(arg0: HttpRequest): Promise<HttpResponse> {
        const result = await this.actor.http_request(arg0);
        return result;
    }
    async icrc1_balance_of(arg0: Account): Promise<bigint> {
        const result = await this.actor.icrc1_balance_of(to_candid_Account_n20(arg0));
        return result;
    }
    async ledger_id(): Promise<Principal> {
        const result = await this.actor.ledger_id();
        return result;
    }
    async status(): Promise<Status> {
        const result = await this.actor.status();
        return result;
    }
}
function from_candid_GetAccountIdentifierTransactionsResponse_n5(value: _GetAccountIdentifierTransactionsResponse): GetAccountIdentifierTransactionsResponse {
    return from_candid_record_n6(value);
}
function from_candid_GetAccountIdentifierTransactionsResult_n3(value: _GetAccountIdentifierTransactionsResult): GetAccountIdentifierTransactionsResult {
    return from_candid_variant_n4(value);
}
function from_candid_Operation_n13(value: _Operation): Operation {
    return from_candid_variant_n14(value);
}
function from_candid_TransactionWithId_n8(value: _TransactionWithId): TransactionWithId {
    return from_candid_record_n9(value);
}
function from_candid_Transaction_n10(value: _Transaction): Transaction {
    return from_candid_record_n11(value);
}
function from_candid_opt_n12(value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(value: [] | [_TimeStamp]): TimeStamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(value: {
    memo: bigint;
    icrc1_memo: [] | [Uint8Array];
    operation: _Operation;
    created_at_time: [] | [_TimeStamp];
}): {
    memo: bigint;
    icrc1_memo?: Uint8Array;
    operation: Operation;
    created_at_time?: TimeStamp;
} {
    return {
        memo: value.memo,
        icrc1_memo: record_opt_to_undefined(from_candid_opt_n12(value.icrc1_memo)),
        operation: from_candid_Operation_n13(value.operation),
        created_at_time: record_opt_to_undefined(from_candid_opt_n16(value.created_at_time))
    };
}
function from_candid_record_n15(value: {
    fee: _Tokens;
    from: string;
    allowance: _Tokens;
    expires_at: [] | [_TimeStamp];
    spender: string;
}): {
    fee: Tokens;
    from: string;
    allowance: Tokens;
    expires_at?: TimeStamp;
    spender: string;
} {
    return {
        fee: value.fee,
        from: value.from,
        allowance: value.allowance,
        expires_at: record_opt_to_undefined(from_candid_opt_n16(value.expires_at)),
        spender: value.spender
    };
}
function from_candid_record_n6(value: {
    balance: bigint;
    transactions: Array<_TransactionWithId>;
    oldest_tx_id: [] | [bigint];
}): {
    balance: bigint;
    transactions: Array<TransactionWithId>;
    oldest_tx_id?: bigint;
} {
    return {
        balance: value.balance,
        transactions: from_candid_vec_n7(value.transactions),
        oldest_tx_id: record_opt_to_undefined(from_candid_opt_n17(value.oldest_tx_id))
    };
}
function from_candid_record_n9(value: {
    id: bigint;
    transaction: _Transaction;
}): {
    id: bigint;
    transaction: Transaction;
} {
    return {
        id: value.id,
        transaction: from_candid_Transaction_n10(value.transaction)
    };
}
function from_candid_variant_n14(value: {
    Approve: {
        fee: _Tokens;
        from: string;
        allowance: _Tokens;
        expires_at: [] | [_TimeStamp];
        spender: string;
    };
} | {
    Burn: {
        from: string;
        amount: _Tokens;
    };
} | {
    Mint: {
        to: string;
        amount: _Tokens;
    };
} | {
    Transfer: {
        to: string;
        fee: _Tokens;
        from: string;
        amount: _Tokens;
    };
} | {
    TransferFrom: {
        to: string;
        fee: _Tokens;
        from: string;
        amount: _Tokens;
        spender: string;
    };
}): {
    __kind__: "Approve";
    Approve: {
        fee: Tokens;
        from: string;
        allowance: Tokens;
        expires_at?: TimeStamp;
        spender: string;
    };
} | {
    __kind__: "Burn";
    Burn: {
        from: string;
        amount: Tokens;
    };
} | {
    __kind__: "Mint";
    Mint: {
        to: string;
        amount: Tokens;
    };
} | {
    __kind__: "Transfer";
    Transfer: {
        to: string;
        fee: Tokens;
        from: string;
        amount: Tokens;
    };
} | {
    __kind__: "TransferFrom";
    TransferFrom: {
        to: string;
        fee: Tokens;
        from: string;
        amount: Tokens;
        spender: string;
    };
} {
    return "Approve" in value ? {
        __kind__: "Approve",
        Approve: from_candid_record_n15(value.Approve)
    } : "Burn" in value ? {
        __kind__: "Burn",
        Burn: value.Burn
    } : "Mint" in value ? {
        __kind__: "Mint",
        Mint: value.Mint
    } : "Transfer" in value ? {
        __kind__: "Transfer",
        Transfer: value.Transfer
    } : "TransferFrom" in value ? {
        __kind__: "TransferFrom",
        TransferFrom: value.TransferFrom
    } : value;
}
function from_candid_variant_n4(value: {
    Ok: _GetAccountIdentifierTransactionsResponse;
} | {
    Err: _GetAccountIdentifierTransactionsError;
}): {
    __kind__: "Ok";
    Ok: GetAccountIdentifierTransactionsResponse;
} | {
    __kind__: "Err";
    Err: GetAccountIdentifierTransactionsError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_GetAccountIdentifierTransactionsResponse_n5(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n7(value: Array<_TransactionWithId>): Array<TransactionWithId> {
    return value.map((x)=>from_candid_TransactionWithId_n8(x));
}
function to_candid_Account_n20(value: Account): _Account {
    return to_candid_record_n21(value);
}
function to_candid_GetAccountIdentifierTransactionsArgs_n1(value: GetAccountIdentifierTransactionsArgs): _GetAccountIdentifierTransactionsArgs {
    return to_candid_record_n2(value);
}
function to_candid_GetAccountTransactionsArgs_n18(value: GetAccountTransactionsArgs): _GetAccountTransactionsArgs {
    return to_candid_record_n19(value);
}
function to_candid_record_n19(value: {
    max_results: bigint;
    start?: bigint;
    account: Account;
}): {
    max_results: bigint;
    start: [] | [bigint];
    account: _Account;
} {
    return {
        max_results: value.max_results,
        start: value.start ? candid_some(value.start) : candid_none(),
        account: to_candid_Account_n20(value.account)
    };
}
function to_candid_record_n2(value: {
    max_results: bigint;
    start?: bigint;
    account_identifier: string;
}): {
    max_results: bigint;
    start: [] | [bigint];
    account_identifier: string;
} {
    return {
        max_results: value.max_results,
        start: value.start ? candid_some(value.start) : candid_none(),
        account_identifier: value.account_identifier
    };
}
function to_candid_record_n21(value: {
    owner: Principal;
    subaccount?: Uint8Array;
}): {
    owner: Principal;
    subaccount: [] | [Uint8Array];
} {
    return {
        owner: value.owner,
        subaccount: value.subaccount ? candid_some(value.subaccount) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): IcpIndex {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new IcpIndex(actor);
}
