/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/CkBtcIndex.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface InitArg {
    ledger_id: Principal;
}
export interface Account {
    owner: Principal;
    subaccount?: SubAccount;
}
export interface TransactionWithId {
    id: BlockIndex;
    transaction: Transaction;
}
export interface GetBlocksResponse {
    blocks: Array<Block>;
    chain_length: bigint;
}
export interface Mint {
    to: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
}
export interface GetTransactions {
    balance: Tokens;
    transactions: Array<TransactionWithId>;
    /**
     * The txid of the oldest transaction the account has
     */
    oldest_tx_id?: BlockIndex;
}
export type GetTransactionsResult = {
    __kind__: "Ok";
    Ok: GetTransactions;
} | {
    __kind__: "Err";
    Err: GetTransactionsErr;
};
export interface GetBlocksRequest {
    start: bigint;
    length: bigint;
}
export interface ListSubaccountsArgs {
    owner: Principal;
    start?: SubAccount;
}
export interface Status {
    num_blocks_synced: BlockIndex;
}
export type BlockIndex = bigint;
export type IndexArg = {
    __kind__: "Upgrade";
    Upgrade: UpgradeArg;
} | {
    __kind__: "Init";
    Init: InitArg;
};
export interface Burn {
    from: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
    spender?: Account;
}
export interface Transaction {
    burn?: Burn;
    kind: string;
    mint?: Mint;
    approve?: Approve;
    timestamp: bigint;
    transfer?: Transfer;
}
export interface Approve {
    fee?: bigint;
    from: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
    expected_allowance?: bigint;
    expires_at?: bigint;
    spender: Account;
}
export interface Transfer {
    to: Account;
    fee?: bigint;
    from: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
    spender?: Account;
}
export interface GetAccountTransactionsArgs {
    /**
     * Maximum number of transactions to fetch.
     */
    max_results: bigint;
    /**
     * The txid of the last transaction seen by the client.
     * If None then the results will start from the most recent
     * txid.
     */
    start?: BlockIndex;
    account: Account;
}
export type SubAccount = Uint8Array;
export interface GetTransactionsErr {
    message: string;
}
export interface FeeCollectorRanges {
    ranges: Array<[Account, Array<[BlockIndex, BlockIndex]>]>;
}
export type Block = Value;
export type Value = {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Map_;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Nat64";
    Nat64: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Array";
    Array: Array<Value>;
};
export type Map_ = Array<[string, Value]>;
export type Tokens = bigint;
export interface UpgradeArg {
    ledger_id?: Principal;
}
export interface CkBtcIndexInterface {
    get_account_transactions(arg0: GetAccountTransactionsArgs): Promise<GetTransactionsResult>;
    get_blocks(arg0: GetBlocksRequest): Promise<GetBlocksResponse>;
    get_fee_collectors_ranges(): Promise<FeeCollectorRanges>;
    icrc1_balance_of(arg0: Account): Promise<Tokens>;
    ledger_id(): Promise<Principal>;
    list_subaccounts(arg0: ListSubaccountsArgs): Promise<Array<SubAccount>>;
    status(): Promise<Status>;
}
import type { Account as _Account, Approve as _Approve, Block as _Block, BlockIndex as _BlockIndex, Burn as _Burn, FeeCollectorRanges as _FeeCollectorRanges, GetAccountTransactionsArgs as _GetAccountTransactionsArgs, GetBlocksResponse as _GetBlocksResponse, GetTransactions as _GetTransactions, GetTransactionsErr as _GetTransactionsErr, GetTransactionsResult as _GetTransactionsResult, ListSubaccountsArgs as _ListSubaccountsArgs, Map as _Map, Mint as _Mint, SubAccount as _SubAccount, Tokens as _Tokens, Transaction as _Transaction, TransactionWithId as _TransactionWithId, Transfer as _Transfer, Value as _Value } from "./declarations/CkBtcIndex.did";
export class CkBtcIndex implements CkBtcIndexInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async get_account_transactions(arg0: GetAccountTransactionsArgs): Promise<GetTransactionsResult> {
        const result = await this.actor.get_account_transactions(to_candid_GetAccountTransactionsArgs_n1(arg0));
        return from_candid_GetTransactionsResult_n5(result);
    }
    async get_blocks(arg0: GetBlocksRequest): Promise<GetBlocksResponse> {
        const result = await this.actor.get_blocks(arg0);
        return from_candid_GetBlocksResponse_n34(result);
    }
    async get_fee_collectors_ranges(): Promise<FeeCollectorRanges> {
        const result = await this.actor.get_fee_collectors_ranges();
        return from_candid_FeeCollectorRanges_n44(result);
    }
    async icrc1_balance_of(arg0: Account): Promise<Tokens> {
        const result = await this.actor.icrc1_balance_of(to_candid_Account_n3(arg0));
        return result;
    }
    async ledger_id(): Promise<Principal> {
        const result = await this.actor.ledger_id();
        return result;
    }
    async list_subaccounts(arg0: ListSubaccountsArgs): Promise<Array<SubAccount>> {
        const result = await this.actor.list_subaccounts(to_candid_ListSubaccountsArgs_n48(arg0));
        return result;
    }
    async status(): Promise<Status> {
        const result = await this.actor.status();
        return result;
    }
}
function from_candid_Account_n17(value: _Account): Account {
    return from_candid_record_n18(value);
}
function from_candid_Approve_n27(value: _Approve): Approve {
    return from_candid_record_n28(value);
}
function from_candid_Block_n37(value: _Block): Block {
    return from_candid_variant_n38(value);
}
function from_candid_Burn_n15(value: _Burn): Burn {
    return from_candid_record_n16(value);
}
function from_candid_FeeCollectorRanges_n44(value: _FeeCollectorRanges): FeeCollectorRanges {
    return from_candid_record_n45(value);
}
function from_candid_GetBlocksResponse_n34(value: _GetBlocksResponse): GetBlocksResponse {
    return from_candid_record_n35(value);
}
function from_candid_GetTransactionsResult_n5(value: _GetTransactionsResult): GetTransactionsResult {
    return from_candid_variant_n6(value);
}
function from_candid_GetTransactions_n7(value: _GetTransactions): GetTransactions {
    return from_candid_record_n8(value);
}
function from_candid_Map_n39(value: _Map): Map_ {
    return from_candid_vec_n40(value);
}
function from_candid_Mint_n24(value: _Mint): Mint {
    return from_candid_record_n25(value);
}
function from_candid_TransactionWithId_n10(value: _TransactionWithId): TransactionWithId {
    return from_candid_record_n11(value);
}
function from_candid_Transaction_n12(value: _Transaction): Transaction {
    return from_candid_record_n13(value);
}
function from_candid_Transfer_n31(value: _Transfer): Transfer {
    return from_candid_record_n32(value);
}
function from_candid_Value_n42(value: _Value): Value {
    return from_candid_variant_n38(value);
}
function from_candid_opt_n14(value: [] | [_Burn]): Burn | null {
    return value.length === 0 ? null : from_candid_Burn_n15(value[0]);
}
function from_candid_opt_n19(value: [] | [_SubAccount]): SubAccount | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(value: [] | [_Account]): Account | null {
    return value.length === 0 ? null : from_candid_Account_n17(value[0]);
}
function from_candid_opt_n23(value: [] | [_Mint]): Mint | null {
    return value.length === 0 ? null : from_candid_Mint_n24(value[0]);
}
function from_candid_opt_n26(value: [] | [_Approve]): Approve | null {
    return value.length === 0 ? null : from_candid_Approve_n27(value[0]);
}
function from_candid_opt_n29(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(value: [] | [_Transfer]): Transfer | null {
    return value.length === 0 ? null : from_candid_Transfer_n31(value[0]);
}
function from_candid_opt_n33(value: [] | [_BlockIndex]): BlockIndex | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(value: {
    id: _BlockIndex;
    transaction: _Transaction;
}): {
    id: BlockIndex;
    transaction: Transaction;
} {
    return {
        id: value.id,
        transaction: from_candid_Transaction_n12(value.transaction)
    };
}
function from_candid_record_n13(value: {
    burn: [] | [_Burn];
    kind: string;
    mint: [] | [_Mint];
    approve: [] | [_Approve];
    timestamp: bigint;
    transfer: [] | [_Transfer];
}): {
    burn?: Burn;
    kind: string;
    mint?: Mint;
    approve?: Approve;
    timestamp: bigint;
    transfer?: Transfer;
} {
    return {
        burn: record_opt_to_undefined(from_candid_opt_n14(value.burn)),
        kind: value.kind,
        mint: record_opt_to_undefined(from_candid_opt_n23(value.mint)),
        approve: record_opt_to_undefined(from_candid_opt_n26(value.approve)),
        timestamp: value.timestamp,
        transfer: record_opt_to_undefined(from_candid_opt_n30(value.transfer))
    };
}
function from_candid_record_n16(value: {
    from: _Account;
    memo: [] | [Uint8Array];
    created_at_time: [] | [bigint];
    amount: bigint;
    spender: [] | [_Account];
}): {
    from: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
    spender?: Account;
} {
    return {
        from: from_candid_Account_n17(value.from),
        memo: record_opt_to_undefined(from_candid_opt_n20(value.memo)),
        created_at_time: record_opt_to_undefined(from_candid_opt_n21(value.created_at_time)),
        amount: value.amount,
        spender: record_opt_to_undefined(from_candid_opt_n22(value.spender))
    };
}
function from_candid_record_n18(value: {
    owner: Principal;
    subaccount: [] | [_SubAccount];
}): {
    owner: Principal;
    subaccount?: SubAccount;
} {
    return {
        owner: value.owner,
        subaccount: record_opt_to_undefined(from_candid_opt_n19(value.subaccount))
    };
}
function from_candid_record_n25(value: {
    to: _Account;
    memo: [] | [Uint8Array];
    created_at_time: [] | [bigint];
    amount: bigint;
}): {
    to: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
} {
    return {
        to: from_candid_Account_n17(value.to),
        memo: record_opt_to_undefined(from_candid_opt_n20(value.memo)),
        created_at_time: record_opt_to_undefined(from_candid_opt_n21(value.created_at_time)),
        amount: value.amount
    };
}
function from_candid_record_n28(value: {
    fee: [] | [bigint];
    from: _Account;
    memo: [] | [Uint8Array];
    created_at_time: [] | [bigint];
    amount: bigint;
    expected_allowance: [] | [bigint];
    expires_at: [] | [bigint];
    spender: _Account;
}): {
    fee?: bigint;
    from: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
    expected_allowance?: bigint;
    expires_at?: bigint;
    spender: Account;
} {
    return {
        fee: record_opt_to_undefined(from_candid_opt_n29(value.fee)),
        from: from_candid_Account_n17(value.from),
        memo: record_opt_to_undefined(from_candid_opt_n20(value.memo)),
        created_at_time: record_opt_to_undefined(from_candid_opt_n21(value.created_at_time)),
        amount: value.amount,
        expected_allowance: record_opt_to_undefined(from_candid_opt_n29(value.expected_allowance)),
        expires_at: record_opt_to_undefined(from_candid_opt_n21(value.expires_at)),
        spender: from_candid_Account_n17(value.spender)
    };
}
function from_candid_record_n32(value: {
    to: _Account;
    fee: [] | [bigint];
    from: _Account;
    memo: [] | [Uint8Array];
    created_at_time: [] | [bigint];
    amount: bigint;
    spender: [] | [_Account];
}): {
    to: Account;
    fee?: bigint;
    from: Account;
    memo?: Uint8Array;
    created_at_time?: bigint;
    amount: bigint;
    spender?: Account;
} {
    return {
        to: from_candid_Account_n17(value.to),
        fee: record_opt_to_undefined(from_candid_opt_n29(value.fee)),
        from: from_candid_Account_n17(value.from),
        memo: record_opt_to_undefined(from_candid_opt_n20(value.memo)),
        created_at_time: record_opt_to_undefined(from_candid_opt_n21(value.created_at_time)),
        amount: value.amount,
        spender: record_opt_to_undefined(from_candid_opt_n22(value.spender))
    };
}
function from_candid_record_n35(value: {
    blocks: Array<_Block>;
    chain_length: bigint;
}): {
    blocks: Array<Block>;
    chain_length: bigint;
} {
    return {
        blocks: from_candid_vec_n36(value.blocks),
        chain_length: value.chain_length
    };
}
function from_candid_record_n45(value: {
    ranges: Array<[_Account, Array<[_BlockIndex, _BlockIndex]>]>;
}): {
    ranges: Array<[Account, Array<[BlockIndex, BlockIndex]>]>;
} {
    return {
        ranges: from_candid_vec_n46(value.ranges)
    };
}
function from_candid_record_n8(value: {
    balance: _Tokens;
    transactions: Array<_TransactionWithId>;
    oldest_tx_id: [] | [_BlockIndex];
}): {
    balance: Tokens;
    transactions: Array<TransactionWithId>;
    oldest_tx_id?: BlockIndex;
} {
    return {
        balance: value.balance,
        transactions: from_candid_vec_n9(value.transactions),
        oldest_tx_id: record_opt_to_undefined(from_candid_opt_n33(value.oldest_tx_id))
    };
}
function from_candid_tuple_n41(value: [string, _Value]): [string, Value] {
    return [
        value[0],
        from_candid_Value_n42(value[1])
    ];
}
function from_candid_tuple_n47(value: [_Account, Array<[_BlockIndex, _BlockIndex]>]): [Account, Array<[BlockIndex, BlockIndex]>] {
    return [
        from_candid_Account_n17(value[0]),
        value[1]
    ];
}
function from_candid_variant_n38(value: {
    Int: bigint;
} | {
    Map: _Map;
} | {
    Nat: bigint;
} | {
    Nat64: bigint;
} | {
    Blob: Uint8Array;
} | {
    Text: string;
} | {
    Array: Array<_Value>;
}): {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Map_;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Nat64";
    Nat64: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Array";
    Array: Array<Value>;
} {
    return "Int" in value ? {
        __kind__: "Int",
        Int: value.Int
    } : "Map" in value ? {
        __kind__: "Map",
        Map: from_candid_Map_n39(value.Map)
    } : "Nat" in value ? {
        __kind__: "Nat",
        Nat: value.Nat
    } : "Nat64" in value ? {
        __kind__: "Nat64",
        Nat64: value.Nat64
    } : "Blob" in value ? {
        __kind__: "Blob",
        Blob: value.Blob
    } : "Text" in value ? {
        __kind__: "Text",
        Text: value.Text
    } : "Array" in value ? {
        __kind__: "Array",
        Array: from_candid_vec_n43(value.Array)
    } : value;
}
function from_candid_variant_n6(value: {
    Ok: _GetTransactions;
} | {
    Err: _GetTransactionsErr;
}): {
    __kind__: "Ok";
    Ok: GetTransactions;
} | {
    __kind__: "Err";
    Err: GetTransactionsErr;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: from_candid_GetTransactions_n7(value.Ok)
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n36(value: Array<_Block>): Array<Block> {
    return value.map((x)=>from_candid_Block_n37(x));
}
function from_candid_vec_n40(value: Array<[string, _Value]>): Array<[string, Value]> {
    return value.map((x)=>from_candid_tuple_n41(x));
}
function from_candid_vec_n43(value: Array<_Value>): Array<Value> {
    return value.map((x)=>from_candid_Value_n42(x));
}
function from_candid_vec_n46(value: Array<[_Account, Array<[_BlockIndex, _BlockIndex]>]>): Array<[Account, Array<[BlockIndex, BlockIndex]>]> {
    return value.map((x)=>from_candid_tuple_n47(x));
}
function from_candid_vec_n9(value: Array<_TransactionWithId>): Array<TransactionWithId> {
    return value.map((x)=>from_candid_TransactionWithId_n10(x));
}
function to_candid_Account_n3(value: Account): _Account {
    return to_candid_record_n4(value);
}
function to_candid_GetAccountTransactionsArgs_n1(value: GetAccountTransactionsArgs): _GetAccountTransactionsArgs {
    return to_candid_record_n2(value);
}
function to_candid_ListSubaccountsArgs_n48(value: ListSubaccountsArgs): _ListSubaccountsArgs {
    return to_candid_record_n49(value);
}
function to_candid_record_n2(value: {
    max_results: bigint;
    start?: BlockIndex;
    account: Account;
}): {
    max_results: bigint;
    start: [] | [_BlockIndex];
    account: _Account;
} {
    return {
        max_results: value.max_results,
        start: value.start ? candid_some(value.start) : candid_none(),
        account: to_candid_Account_n3(value.account)
    };
}
function to_candid_record_n4(value: {
    owner: Principal;
    subaccount?: SubAccount;
}): {
    owner: Principal;
    subaccount: [] | [_SubAccount];
} {
    return {
        owner: value.owner,
        subaccount: value.subaccount ? candid_some(value.subaccount) : candid_none()
    };
}
function to_candid_record_n49(value: {
    owner: Principal;
    start?: SubAccount;
}): {
    owner: Principal;
    start: [] | [_SubAccount];
} {
    return {
        owner: value.owner,
        start: value.start ? candid_some(value.start) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): CkBtcIndex {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new CkBtcIndex(actor);
}
